name = "Masters_Thesis"
authors = ["Vidianos Giannitsis"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DrWatson = "2.13.0"
julia = "1.9.0"
