#+TITLE: Συνθήκες Λειτουργίας Ενζυμικής Υδρόλυσης
#+AUTHOR: Βιδιάνος Γιαννίτσης
#+cite_export: csl american-chemical-society.csl

* Προεπεξεργασία
Πριν την ενζυμική υδρόλυση, χρειάζονται κάποια άλλα στάδια. Πρώτα πρέπει τα τρόφιμα να μπουν σε blender για να γίνουν λεπτόκοκκα στερεά τα οποία είναι πιο εύκολα στον χειρισμό. Έπειτα, συνήθως διαλύονται σε νερό ή σε αναλογία 1:1 [cite:@usmaniMinimizingHazardousImpact2021; @moonEnzymaticHydrolysisFoodWaste2011] ή μέχρι το διάλυμα να έχει \( 10 \% \) στερεά [cite:@chenProcessDesignTechnoeconomic2022] . Κάποιοι έκαναν και λιποδιαχωρισμό για να μην έχουν τα λίπη στο υπόστρωμα τους αλλά να τα αξιοποιήσουν διαφορετικά [cite:@chenProcessDesignTechnoeconomic2022] . Μετά από αυτά, μπορεί να γίνει η ενζυμική υδρόλυση. 

* Ένζυμα που χρησιμοποιούνται
Για να βγούν συμπεράσματα για τα ένζυμα και τις συνθήκες που χρησιμοποιούνται εξετάστηκαν 25 πειράματα από 3 reviews και 6 άρθρα [cite:@cekmeceliogluKineticModelingEnzymatic2013; @chenProcessDesignTechnoeconomic2022; @moonEnzymaticHydrolysisFoodWaste2011; @moonEnzymaticHydrolysisFood2009; @zhangValorizationFoodWaste2020; @zhangAnaerobicFermentationPretreated2021; @anwarsaeedConciseReviewEthanol2018; @usmaniMinimizingHazardousImpact2021; @maUtmostBioenergyConversion2018a] .

Γενικά, σχεδόν όλες οι μελέτες χρησιμοποιήσαν κάποιες υδατανθρακάσες. Ορισμένοι χρησιμοποιήσαν έτοιμα εμπορικά μίγματα υδατανθρακασών (πχ το ένζυμο Viscozyme της εταιρείας Novozyme) [cite:@moonEnzymaticHydrolysisFoodWaste2011; @moonEnzymaticHydrolysisFood2009] ενώ άλλοι έκαναν πιο συγκεκριμένη επιλογή. Τα 3 βασικά ένζυμα που χρησιμοποιήθηκαν ήταν η αμυλογλυκοζιδάση, η α-αμυλάση και η γλυκοαμυλάση. Η α-αμυλάση έχει ως σκοπό την διάσπαση των μεγάλων αλυσίδων αμύλου σε μικρότερους υδρογονάνθρακες, ενώ η αμυλογλυκοζιδάση και η γλυκοαμυλάση σπάνε αυτά τα μικρότερα μόρια σε γλυκόζη. Ακόμη, ορισμένες μελέτες χρησιμοποιήσαν και κυτταρινάσες [cite:@cekmeceliogluKineticModelingEnzymatic2013] ή πεκτινάσες [cite:@zhangValorizationFoodWaste2020] για διάσπαση της λιγνοκυτταρινικής βιομάζας που μπορεί να υπάρχει στα υπολείμματα. Πέρα από αυτές, αρκετοί χρησιμοποιήσαν και προτεάσες για να διασπάσουν τις πρωτείνες στα τρόφιμα σε χρήσιμα αμινοξέα [cite:@moonEnzymaticHydrolysisFoodWaste2011; @chenProcessDesignTechnoeconomic2022; @maUtmostBioenergyConversion2018a; @anwarsaeedConciseReviewEthanol2018; @usmaniMinimizingHazardousImpact2021] . Η τελευταία κατηγορία ενζύμων που χρησιμοποιήθηκε είναι οι λιπάσες, οι οποίες διασπάνε τις λιπαρές ενώσεις στα τρόφιμα [cite:@moonEnzymaticHydrolysisFoodWaste2011] . Όμως οι περισσότερες μελέτες δεν τις συμπεριέλαβαν.

Τα περισσότερα πειράματα έγιναν προσθέτοντας ταυτόχρονα όλα τα ένζυμα, αλλά ορισμένα έγιναν σε δύο στάδια. Σε αυτά, το πρώτο στάδιο ήταν πάντα η προσθήκη α-αμυλάσης για την διάσπαση του πολυμερούς σε μικρότερα κομμάτια ώστε μετά τα άλλα ένζυμα να δράσουν πιο γρήγορα και αποτελεσματικά. Επίσης, η χρήση δύο σταδίων επιτρέπει την επιλογή των βέλτιστων συνθηκών του εκάστοτε ενζύμου. Με την επιλογή αυτή, κάποια πειράματα είχαν καλύτερα αποτελέσματα [cite:@cekmeceliogluKineticModelingEnzymatic2013; @zhangValorizationFoodWaste2020; @zhangAnaerobicFermentationPretreated2021] .

* Συνθήκες λειτουργίας
Οι παραμέτροι "εισόδου" του προβλήματος είναι για τα περισσότερα πειράματα η δόση του ενζύμου, η θερμοκρασία, το pH, η ανάδευση και ο χρόνος παραμονής. Η δόση του ενζύμου είναι αρκετά διαφορετική από πείραμα σε πείραμα και είναι σίγουρα μία από τις παραμέτρους που αξίζει να ρυθμίσουμε. Η θερμοκρασία και το pH δεν είναι σε μεγάλο εύρος τιμών. Η θερμοκρασία είναι σχεδόν αποκλειστικά στους 50-60 \( ^oC \) με τις τιμές 50 και 55 \( ^oC \) να είναι οι συχνότερες ενώ το pH είναι μεταξύ 4.5-5.5 σε σχεδόν κάθε μελέτη. Καθώς τα τρόφιμα είναι ήδη λίγο όξινα συνήθως, αυτό σημαίνει ότι μάλλον δεν απαιτείται ρύθμιση του pH και δεν έχει ιδιαίτερη σημασία η εξέταση διαφορετικών τιμών.

Για την ανάδευση, πολλά πειράματα δεν την αναφέρουν καν, αλλά από αυτούς που την αναφέρουν, οι τιμές 100 και 150 rpm είναι συχνές [cite:@moonEnzymaticHydrolysisFoodWaste2011; @moonEnzymaticHydrolysisFood2009; @cekmeceliogluKineticModelingEnzymatic2013; @maUtmostBioenergyConversion2018a; @usmaniMinimizingHazardousImpact2021] . Μία μελέτη ανέφερε και γρηγορότερη ανάδευση στα 500 rpm [cite:@chenProcessDesignTechnoeconomic2022] . Πιθανόν να αξίζει περαιτέρω πειραματισμός στο πεδίο αυτό.

Σχετικά με τον χρόνο παραμονής, είναι συχνά 24 ώρες, με κάποια πειράματα να δοκιμάζουν και πιο γρήγορες υδρολύσεις (3-12 ώρες). Ακόμη, κάποιοι λένε πως το δείγμα αφέθηκε για 24 ώρες, αλλά βρέθηκε ότι και μέσα σε 10 έχει φτάσει σε ικανοποιητική μετατροπή [cite:@moonEnzymaticHydrolysisFoodWaste2011] .

* Μεταβλητές εξόδου
Οι τρείς μεταβλητές που μετριούνται σχεδόν αποκλειστικά είναι η μείωση στα VSS, η γλυκόζη και τα αναγωγικά σάκχαρα. Η μέτρηση του VSS είναι η πιο εύκολη και μπορεί να χρησιμοποιηθεί για να δούμε την πρόοδο της υδρόλυσης, αλλά η "απόδοση" της μετρήθηκε από τα περισσότερα πειράματα αναφέροντας πόσα g/l γλυκόζη ή γενικότερα αναγωγικά σάκχαρα περιέχονται στο τελικό υδρόλυμα.

\pagebreak
* Βιβλιογραφία
#+print_bibliography:
