#+TITLE: Αναλύσεις και Αποτελέσματα για την λάσπη Tasty
#+AUTHOR: Β. Γιαννίτσης, Δ. Θεοδόση Παλιμέρη

* Στερεά
Μετρήθηκαν τα ολικά και πτητικά στερεά, καθώς και τα ολικά και πτητικά αιωρούμενα στερεά της λάσπης. Τα TS ήταν 4.3 g/kg και τα VS 2.0 g/kg. Ο λόγος VS/TS ήταν 0.465.

Τα TSS ήταν 3.09 g/kg και τα VSS 1.54 g/kg. Ο λόγος VSS/TSS ήταν 0.5.

* pH και Αλκαλικότητα
Το pH της λάσπης ήταν 7.5 και η αλκαλικότητα της προσδιορίστηκε ως \(1100~ \frac{mg CaCO_3}{L} \) με ογκομέτρηση με θειικό οξύ 0.1 N. 

* Παραγωγή Μεθανίου με Οξικό Οξύ
Κατά την τροφοδοσία με οξικό οξύ, η λάσπη αυτή παρήγαγε 29.8 mL μεθάνιο. Η ειδική μεθανογόνος δραστικότητα (SMA) της λάσπης ήταν \(870.8 ~ \frac{\text{mL μεθανίου}}{\text{g VS} \cdot \text{hour}} \), η οποία προσδιορίστηκε μέσω προσαρμογής των δεδομένων σε ένα τροποποιημένο μοντέλο Gompertz

\[ P(t) = P_{\max } \exp \left( - \exp \left[ \frac{R_{\max }e (λ-t)}{P_{\max }} + 1 \right] \right) \]
όπου P(t) η παραγωγή μεθανίου την στιγμή t, P_max η μέγιστη ποσότητα μεθανίου που μπορεί να παραχθεί από το υπόστρωμα αυτό, R_max ο ειδικός ρυθμός παραγωγής μεθανίου, λ ο χρόνος καθυστέρησης και e η σταθερά Euler. Ο χρόνος καθυστέρησης για το πείραμα αυτό ήταν μηδενικός.

* Παραγωγή Μεθανίου με Υδρόλυμα Υπολειμμάτων Τροφών
Κατά την τροφοδοσία 2 διαφορετικών υδρολυμάτων προερχόμενα από υπολείμματα τροφών, η λάσπη αυτή παρήγαγε 7.3 και 5.8 mL μεθάνιο. Η ειδική μεθανογόνος δραστικότητα της λάσπης για τα πειράματα αυτά ήταν \(4.296 \text{ και } 3.192 \frac{\text{mL μεθανίου}}{\text{g VS} \cdot \text{day}}\) αντίστοιχα. Ο χρόνος καθυστέρησης στα 2 πειράματα ήταν 15.07 και 6.86 ώρες.

Παρακάτω φαίνεται και το διάγραμμα της συνολικής παραγωγής μεθανίου από τα πειράματα αυτά

#+ATTR_ORG: :width 700px
#+CAPTION: Συνολική Παραγωγή Μεθανίου από Υδρολύματα με λάσπη Tasty
[[../plots/BMPs/methane_orca_s3_comp.svg]]

* pH μετά την Αναερόβια Χώνευση
Μετρήθηκε το pH του κάθε αντιδραστήρα μετά τα πειράματα αυτά. Ο αντιδραστήρας που τροφοδοτήθηκε με οξικό είχε pH 4.33, αλλά παρότι μειώθηκε πολύ το pH του από την τροφοδοσία του οξικού, παρήγαγε καλή ποσότητα μεθανίου. Οι αντιδραστήρες που τροφοδοτήθηκαν με υδρολύματα είχαν pH 9.24 και 9.00 αντίστοιχα.
