#+TITLE: Θεωρητικό Μέρος - Απόβλητα Τροφών και Ενζυμική Υδρόλυση
\renewcommand{\abstractname}{Περίληψη}
\renewcommand{\tablename}{Πίνακας}
\renewcommand{\figurename}{Σχήμα}
\renewcommand\listingscaption{Κώδικας}
#+cite_export: csl american-chemical-society.csl
#+AUTHOR: Βιδιάνος Γιαννίτσης

* Απόβλητα Τροφών
Τα απόβλητα τροφών αποτελούν μία από τις σημαντικότερες κατηγορίες αποβλήτων. Ο οργανισμός τροφίμων και αγρονομίας των ηνωμένων πολιτείων (FAO) υπολογίζει πως περίπου το 1/3 της παγκόσμιας παραγωγής φαγητού (περίπου 1.3 δισεκατομμύριοι τόνοι ετησίως) απορρίπτεται, σπαταλόντας το \( 38 \% \) της συνολικής ενέργειας που δαπανούν οι βιομηχανίες τροφίμων για την δημιουργία του και οδηγώντας σε μία οικονομική απώλεια της τάξης των 936 δισεκατομμυρίων δολλαρίων [cite:@ishangulyyevUnderstandingFoodLoss2019]. Περίπου το \( 56 \% \) αυτού είναι σε ανεπτυγμένες χώρες, όπου η πλειοψηφία (περίπου \( 40 \% \)) είναι στο στάδιο της κατανάλωσης, ενώ στις λιγότερο ανεπτυγμένες οι απώλειες είναι σε μεγάλο ποσοστό στην συγκομιδή και την επεξεργασία λόγω οικονομικών και τεχνολογικών περιορισμών αλλά και κακών εγκακαταστάσεων [cite:@ishangulyyevUnderstandingFoodLoss2019] . Ακόμη, σύμφωνα με ειδικούς, αυτές οι ποσότητες δείχνουν αυξητική τάση [cite:@ishangulyyevUnderstandingFoodLoss2019; @wuPotentialityRecoveringBioresource2022] . Όμως, τα απόβλητα αυτά είναι πολύ πλούσια σε οργανική ύλη η οποία θα μπορούσε να αξιοποιηθεί.

Η απόρριψη των τροφίμων αυτών δημιουργεί προβλήματα σε κάθε πυλώνα της βιωσιμότητας. Από κοινωνικής άποψης, είναι ανεπίτρεπτο τα απόβλητα τροφών στο στάδιο της κατανάλωσης σε ανεπτυγμένες χώρες να είναι περίπου ίδιο με την συνολική παραγωγή τροφίμων σε υποανάπτυκτες χώρες, όπου το πρόβλημα του υποσιτισμού είναι ιδιαίτερα συχνό [cite:@ishangulyyevUnderstandingFoodLoss2019] . Από περιβαλλοντικής άποψης, τα απόβλητα αυτά είναι σε τόσο μεγάλη ποσότητα που η διαχείριση τους με συμβατικές μεθόδους (πχ απόρριψη ή αποτέφρωση) δημιουργεί σοβαρά περιβαλλοντικά προβλήματα [cite:@wuPotentialityRecoveringBioresource2022; @ishangulyyevUnderstandingFoodLoss2019; @zhangValorizationFoodWaste2020]. Πιο συγκεκριμένα, το ετήσιο αποτύπωμα άνθρακα που δημιουργείται μόνο λόγω των αποβλήτων αυτών υπολογίζεται περίπου στους 3.3 δισεκατομμύριους τόνους CO_{2} eq [cite:@taheriEffectPretreatmentTechniques2021]. Αλλά και από οικονομικής άποψης, σπαταλάται τόση ενέργεια για την δημιουργία τους και λίγο λιγότερο από την μισή πάει χαμένη, ενώ αυτά τα απόβλητα θα μπορούσαν να χρησιμοποιηθούν ως μία νέα πρώτη ύλη και έτσι όχι μόνο να μην υπάρχει οικονομική απώλεια λόγω αυτών, αλλά να επιφέρουν και σημαντικό οικονομικό όφελος.

** Τεχνικές αξιοποίησης των αποβλήτων τροφών
Στην βιβλιογραφία, υπάρχουν πάρα πολλές τεχνικές αξιοποίησης των αποβλήτων αυτών. Οι πιο σύνηθεις είναι τεχνικές όπως η κομποστοποίηση, η οποία παράγει ένα εδαφοβελτιωτικό προιόν, το κομπόστ [cite:@cerdaCompostingFoodWastes2018], η αναερόβια χώνευση, η οποία παράγει βιοαέριο, ένα μίγμα μεθανίου και διοξειδίου του άνθρακα που μπορεί να χρησιμοποιηθεί ως βιοκαύσιμο στην ίδια λογική με το φυσικό αέριο [cite:@moonEnzymaticHydrolysisFoodWaste2011; @maUtmostBioenergyConversion2018] και η αλκοολική ζύμωση, η οποία παράγει βιοαιθανόλη, η οποία είναι επίσης πολύ χρήσιμη ως βιοκαύσιμο [cite:@roukasFoodIndustryWastes2022; @anwarsaeedConciseReviewEthanol2018]. Η χρήση του απόβλητου αυτού σημαίνει ένα πολύ φθηνό υπόστρωμα για τις διεργασίες αυτές, αλλά ένα υπόστρωμα πολύ πλούσιο σε σάκχαρα και πρωτείνες τα οποία είναι ιδιαίτερα σημαντικά για τις διεργασίες αυτές.

Πέρα από αυτές τις τεχνικές, υπάρχουν και άλλες που έχουν μελετηθεί αρκετά στη βιβλιογραφία όπως η παραγωγή υδρογόνου είτε με την βιολογική διεργασία της σκοτεινής ζύμωσης [cite:@hanBiohydrogenProductionEnzymatic2016] ή με την θερμική διεργασία της αεριοποίησης [cite:@murugesanFoodWasteValorisation2022; @usmaniMinimizingHazardousImpact2021]. H ζύμωση ακετόνης-βουτανόλης-αιθανόλης (γνωστή και ως διεργασία Weizmann) [cite:@zhangAnaerobicFermentationPretreated2021] ή η παραγωγή βιοπλαστικών για την αντικατάσταση των συμβατικών πλαστικών [cite:@rajeshbanuReviewFoodWaste2023] .

Η τεχνική που θα παρουσιαστεί στη μελέτη αυτή είναι η αναερόβια χώνευση.

* Προεπεξεργασία
Ένα πρόβλημα που υπάρχει όμως στα απόβλητα τροφίμων είναι πως είναι απόβλητα τα οποία είναι αρκετά ανομοιογενή. Επίσης, αποτελούνται κυρίως από πολυμερή τα οποία δεν είναι άμεσα ζυμώσιμα. Για αυτό, στις περισσότερες περιπτώσεις προτείνεται να γίνει ένα στάδιο προεπεξεργασίας στα τρόφιμα.

Για να γίνουν πιο ομοιογενή, προτείνεται συνήθως ο τεμαχισμός και η ανάμειξη τους. Έτσι, έχουμε μία λεπτόκοκκη, ημιστερεή πούλπα η οποία μπορεί πιο εύκολα να αναδευτεί και να επιτύχει ομοιογένια. Αυτό γίνεται με κάποιο μπλέντερ συνήθως. Μετά από αυτό, είναι συχνό να περάσουν και από ένα κόσκινο (συνήθως 1-3 mm) για να συγκρατηθούν πιθανά χοντρόκοκκα κομμάτια που δεν είναι επιθυμητά στην υδρόλυση. Βέβαια, ανάλογα με την σύνθεση τους, υπάρχει πιθανότητα να μην είναι εύκολο να γίνει αυτό και να υπάρχει πολύ μεγάλη απώλεια στο κόσκινο [cite:@moonEnzymaticHydrolysisFoodWaste2011; @chenProcessDesignTechnoeconomic2022] .

Ακόμη και στην περίπτωση αυτή όμως, μιλάμε για ένα μίγμα το οποίο έχει πολλά στερεά. Καθώς πολλές από τις διεργασίες που ακολουθούν λειτουργούν καλύτερα σε υδατικά διαλύματα, είναι αρκετά συχνό πριν ακολουθήσει κάποια άλλη διεργασία να κάνουμε αραίωση του αποβλήτου σε νερό. Αυτό γίνεται συνήθως ή με κάποια αναλογία (πχ 1:1 ή 1:2 με νερό) ή μέχρι μία συγκεκριμένη ποσότητα στερεών (πχ \( 10 \%  \) της συνολικής μάζας) [cite:@chenProcessDesignTechnoeconomic2022; @moonEnzymaticHydrolysisFoodWaste2011; @hanBiohydrogenProductionEnzymatic2016] .

** Υδρόλυση
Μετά από αυτά τα στάδια, τα απόβλητα μπορούν να χρησιμοποιηθούν σε πολλές από τις παραπάνω διεργασίες. Βέβαια, όπως προαναφέρθηκε, δεν είναι άμεσα ζυμώσιμα καθώς αποτελούνται κυρίως από πολυμερή όπως το άμυλο ή διάφορες πρωτείνες. Κάποιες διεργασίες όπως η αναερόβια χώνευση μπορούν να ξεπεράσουν το πρόβλημα αυτό καθώς μπορούν να κάνουν την υδρόλυση μαζί με τα υπόλοιπα στάδια της διεργασίας. Σε κάποιες άλλες όπως η αλκοολική ζύμωση, αυτό δεν είναι εφικτό και η υδρόλυση πρέπει να γίνει ξεχωριστά. Βέβαια, ακόμη και σε αυτές που μπορεί να γίνει μέσα στη διεργασία, η ξεχωριστή υδρόλυση επιφέρει κάποια σημαντικά πλεονεκτήματα όπως επιτάχυνση της διεργασίας και συχνά αύξηση της απόδοσης της [cite:@maUtmostBioenergyConversion2018; @wuPotentialityRecoveringBioresource2022] .

Υπάρχουν διάφορες τεχνικές υδρόλυσης όπως η θερμική, η χημική, ή η ενζυμική. Η θερμική βασίζεται στην θερμική διάσπαση των πολυμερών στα μονομερή τους, όμως, αρχικά απαιτεί μεγάλη ποσότητα ενέργειας και επίσης παράγει και προιόντα θερμικής αποσύνθεσης, τα οποία μπορεί να είναι τοξικά προς μικροοργανισμούς [cite:@maUtmostBioenergyConversion2018]. Για αυτό, γενικά αποφεύγεται η θερμική επεξεργασία, εκτός από την περίπτωση της δύσκολα διασπάσημης λιγνοκυτταρινικής βιομάζας, η οποία την απαιτεί όχι για να σπάσει τα πολυμερή, αλλά για να διαταράξει την δομή του υλικού και να μπορεί κάποια άλλη μέθοδο να τα σπάσει [cite:@fernandez-bolanosSteamexplosionOliveStones2001]. Τα απόβλητα τροφών όμως δεν υπάγονται στην κατηγορία αυτή.

Η χημική προεπεξεργασία διακρίνεται σε δύο βασικές κατηγορίες, την όξινη και την αλκαλική. Βασικό χαρακτηριστικό και των δύο είναι ότι χρησιμοποιούν ακραίες τιμές του pH για να προκαλέσουν κατάρρευση στην πολυμερική αλυσίδα και να απελευθερωθούν μονομερή και ολιγομερή. Λύνει το πρόβλημα του κόστους χρησιμοποιώντας κοινότυπα και φθηνά χημικά και κάνει την διεργασία αρκετά πιο αποτελεσματική. Βέβαια τοξικά παραπροιόντα μπορούν να παραχθούν και από την διεργασία και για αυτό η απόδοση της δεν είναι τόσο υψηλή [cite:@hanBiohydrogenProductionEnzymatic2016; @maUtmostBioenergyConversion2018].

Η ενζυμική υδρόλυση χρησιμοποιεί ένζυμα τα οποία είναι εξειδικευμένα στην διάσπαση των πολυμερών αυτών καθώς και των ολιγομερών τους. Για αυτό, είναι εξαιρετικά αποτελεσματική και δεν παράγει καθόλου παραπροιόντα. Επίσης, απαιτεί ήπιες συνθήκες, δηλαδή ατμοσφαιρική πίεση και θερμοκρασία συνήθως στην περιοχή των 50-60 \( ^oC \) [cite:@maUtmostBioenergyConversion2018; @hanBiohydrogenProductionEnzymatic2016]. Το βασικό της πρόβλημα είναι πως παρόλο που χρειάζεται μικρή ποσότητα ενζύμων, αυτά είναι πολύ ακριβά το οποίο ανεβάζει το κόστος της διεργασίας σημαντικά. Βέβαια, μία πρόσφατη μελέτη έδειξε πως επειδή είναι πολύ πιο αποτελεσματική διεργασία, μπορεί να αυξήσει την παραγωγή του επιθυμητού προιόντος και ως αποτέλεσμα από την πώληση του, το καθαρό κέρδος να είναι περισσότερο επειδή η διεργασία γίνεται χωρίς καθόλου τοξικά παραπροιόντα και άρα πάρα πολύ καλή απόδοση [cite:@zhangValorizationFoodWaste2020]. Για αυτούς τους λόγους, η τεχνική αυτή θεωρείται η πιο συχνή μέθοδος υδρόλυσης.

Κάποιες μελέτες έχουν δοκιμάσει όμως και κάποιες πιο προτωποριακές τεχνικές όπως οι υπέρηχοι και τα μικροκύματα. Τα μικροκύματα αυξάνουν την κινητική ενέργεια του διαλύματος επιτρέποντας του να φτάσει στο σημείο βρασμού του πολύ γρήγορα, προσωμοιάζοντας μία θερμική μέθοδο, βέβαια, δεν προτείνεται για επεξεργασία αποβλήτων τροφών επειδή δεν πετυχαίνει ιδιαίτερα υψηλή απόδοση [cite:@maUtmostBioenergyConversion2018] . Η χρήση υπέρηχων δημιουργεί ελεύθερες ρίζες υδροξυλίου και υδρογόνου οι οποίες είναι πάρα πολύ αντιδραστικές και μπορούν να διασπάσουν πολύ αποτελεσματικά τα πολυμερή. Αναφέρεται πως δεν είναι όσο αποτελεσματική όσο άλλες τεχνικές από μόνη της [cite:@maUtmostBioenergyConversion2018] όμως, σε συνδυασμό με τεχνικές όπως η ενζυμική υδρόλυση, παίζει επικουρικό ρόλο και βελτιώνει σημαντικά την απόδοση της υδρόλυσης  [cite:@sureshProcessIntensificationComparison2020; @usmaniMinimizingHazardousImpact2021]. Μάλιστα, μία πιο αναλυτική μελέτη πάνω στην αλληλεπίδραση αυτή [cite:@liUltrasonicPretreatmentFood2019] έδειξε πως οι υπέρηχοι μπορούν να αυξήσουν την απόδοση σε γλυκόζη κατά \( 10 \% \) περίπου και ταυτόχρονα να μειώσουν τον απαιτούμενο χρόνο περίπου στο μισό. Βέβαια, η προσθήκη του βήματος αυτού αυξάνει το κόστος της διεργασίας. Όμως, λόγω της σημαντικής μείωσης του χρόνου - ο οποίος σε ένα συνεχές σύστημα είναι ανάλογος της ποσότητας των ενζύμου - μπορεί να μειωθεί σημαντικά το κόστος της διεργασίας καθώς τα ένζυμα είναι το ακριβότερο κομμάτι της διεργασίας αυτής. Οπότε η χρήση τεχνικών όπως αυτή, επικουρικά της υδρόλυσης μπορεί να επιφέρει σημαντικά πλεονεκτήματα.

* Ενζυμική Υδρόλυση
Για τους λόγους που προαναφέρθηκαν, στην παρούσα μελέτη επιλέχθηκε η χρήση ενζυμικής υδρόλυσης ως προεπεξεργασία. Για να επιλέχθουν οι βέλτιστες συνθήκες λειτουργίας της διεργασίας, έγινε μία βιβλιογραφική ανασκόπηση από προηγούμενες μελέτες και αυτή χρησιμοποιήθηκε ως σημείο έναρξης για το πειραματικό κομμάτι της εργασίας. Εξετάστηκαν 25 πειράματα από 3 reviews και 6 άρθρα [cite:@maUtmostBioenergyConversion2018; @usmaniMinimizingHazardousImpact2021; @anwarsaeedConciseReviewEthanol2018; @zhangAnaerobicFermentationPretreated2021; @zhangValorizationFoodWaste2020; @moonEnzymaticHydrolysisFoodWaste2011; @moonEnzymaticHydrolysisFood2009; @chenProcessDesignTechnoeconomic2022; @cekmeceliogluKineticModelingEnzymatic2013] .

** Ένζυμα
Γενικά, σχεδόν όλες οι μελέτες χρησιμοποιήσαν κάποιες υδατανθρακάσες. Ορισμένοι χρησιμοποιήσαν έτοιμα εμπορικά μίγματα υδατανθρακασών (πχ το ένζυμο Viscozyme της εταιρείας Novozyme) [cite:@moonEnzymaticHydrolysisFoodWaste2011; @moonEnzymaticHydrolysisFood2009] ενώ άλλοι έκαναν πιο συγκεκριμένη επιλογή. Τα 3 βασικά ένζυμα που χρησιμοποιήθηκαν ήταν η αμυλογλυκοζιδάση, η α-αμυλάση και η γλυκοαμυλάση. Η α-αμυλάση έχει ως σκοπό την διάσπαση των μεγάλων αλυσίδων αμύλου σε μικρότερους υδρογονάνθρακες, ενώ η αμυλογλυκοζιδάση και η γλυκοαμυλάση σπάνε αυτά τα μικρότερα μόρια σε γλυκόζη. Ακόμη, ορισμένες μελέτες χρησιμοποιήσαν και κυτταρινάσες [cite:@cekmeceliogluKineticModelingEnzymatic2013] ή πεκτινάσες [cite:@zhangValorizationFoodWaste2020] για διάσπαση της λιγνοκυτταρινικής βιομάζας που μπορεί να υπάρχει στα υπολείμματα. Πέρα από αυτές, αρκετοί χρησιμοποιήσαν και προτεάσες για να διασπάσουν τις πρωτείνες στα τρόφιμα σε χρήσιμα αμινοξέα [cite:@moonEnzymaticHydrolysisFoodWaste2011; @chenProcessDesignTechnoeconomic2022; @maUtmostBioenergyConversion2018; @anwarsaeedConciseReviewEthanol2018; @usmaniMinimizingHazardousImpact2021] . Η τελευταία κατηγορία ενζύμων που χρησιμοποιήθηκε είναι οι λιπάσες, οι οποίες διασπάνε τις λιπαρές ενώσεις στα τρόφιμα [cite:@moonEnzymaticHydrolysisFoodWaste2011] . Όμως οι περισσότερες μελέτες δεν τις συμπεριέλαβαν, είτε επειδή δεν το θεώρησαν αρκετά σημαντικό ή επειδή στην προεπεξεργασία είχαν κάνει λιποδιαχωρισμό και εκμεταλλεύτηκαν διαφορετικά τα λίπη [cite:@chenProcessDesignTechnoeconomic2022] .  

Τα περισσότερα πειράματα έγιναν προσθέτοντας ταυτόχρονα όλα τα ένζυμα, αλλά ορισμένα έγιναν σε δύο στάδια. Σε αυτά, το πρώτο στάδιο ήταν πάντα η προσθήκη α-αμυλάσης για την διάσπαση του πολυμερούς σε μικρότερα κομμάτια ώστε μετά τα άλλα ένζυμα να δράσουν πιο γρήγορα και αποτελεσματικά. Επίσης, η χρήση δύο σταδίων επιτρέπει την επιλογή των βέλτιστων συνθηκών του εκάστοτε ενζύμου. Με την επιλογή αυτή, κάποια πειράματα είχαν καλύτερα αποτελέσματα [cite:@cekmeceliogluKineticModelingEnzymatic2013; @zhangValorizationFoodWaste2020; @zhangAnaerobicFermentationPretreated2021] .

** Συνθήκες Λειτουργίας
Οι παραμέτροι "εισόδου" του προβλήματος είναι για τα περισσότερα πειράματα η δόση του ενζύμου, η θερμοκρασία, το pH, η ανάδευση και ο χρόνος παραμονής. Η δόση του ενζύμου είναι αρκετά διαφορετική από πείραμα σε πείραμα και είναι σίγουρα μία από τις παραμέτρους που πρέπει να γίνει πειραματισμός για να αποφασιστεί η βέλτιστη τιμή της. Η θερμοκρασία και το pH δεν είναι σε μεγάλο εύρος τιμών. Η θερμοκρασία είναι σχεδόν αποκλειστικά στους 50-60 \( ^oC \) με τις τιμές 50 και 55 \( ^oC \) να είναι οι συχνότερες ενώ το pH είναι μεταξύ 4.5-5.5 σε σχεδόν κάθε μελέτη. Καθώς τα τρόφιμα είναι ήδη λίγο όξινα συνήθως, αυτό σημαίνει ότι μάλλον δεν απαιτείται ρύθμιση του pH και δεν έχει ιδιαίτερη σημασία η εξέταση διαφορετικών τιμών.

Για την ανάδευση, πολλά πειράματα δεν την αναφέρουν καν, αλλά από αυτούς που την αναφέρουν, οι τιμές 100 και 150 rpm είναι συχνές [cite:@moonEnzymaticHydrolysisFoodWaste2011; @moonEnzymaticHydrolysisFood2009; @cekmeceliogluKineticModelingEnzymatic2013; @maUtmostBioenergyConversion2018; @usmaniMinimizingHazardousImpact2021] . Μία μελέτη ανέφερε και γρηγορότερη ανάδευση στα 500 rpm [cite:@chenProcessDesignTechnoeconomic2022] .

Σχετικά με τον χρόνο παραμονής, είναι συχνά 24 ώρες, με κάποια πειράματα να δοκιμάζουν και πιο γρήγορες υδρολύσεις (3-12 ώρες). Ακόμη, κάποιοι λένε πως το δείγμα αφέθηκε για 24 ώρες, αλλά βρέθηκε ότι και μέσα σε 10 έχει φτάσει σε ικανοποιητική μετατροπή [cite:@moonEnzymaticHydrolysisFoodWaste2011] .

** Μεταβλητές Εξόδου
Οι τρείς μεταβλητές που μετριούνται συνήθως στην διεργασία αυτή είναι η μείωση στα VSS, η γλυκόζη και τα αναγωγικά σάκχαρα. Η μέτρηση του VSS είναι η πιο εύκολη και μπορεί να χρησιμοποιηθεί για να δούμε την πρόοδο της υδρόλυσης, αλλά η "απόδοση" της μετρήθηκε από τα περισσότερα πειράματα αναφέροντας πόσα g/l γλυκόζη ή γενικότερα αναγωγικά σάκχαρα περιέχονται στο τελικό υδρόλυμα.

* Βιβλιογραφία
#+print_bibliography:
