#+TITLE: Analysis of Variance of HPLC Data

\begin{abstract}
Έχουμε πάρει πολλά δεδομένα από την HPLC για διάφορες συγκεντρώσεις σε κάθε πείραμα. Ένα καλό ερώτημα το οποίο δεν έχουμε εξετάσει είναι κατά πόσο είναι στατιστικά σημαντική η προσθήκη του μιξ γενικά ή και ξεχωριστά από το ένα επίπεδο στο άλλο. Σκοπός του αρχείου αυτού είναι να εξετάσει κάτι τέτοιο με χρήση της ANOVA.
\end{abstract}

* Dependencies
Αρχικά, όπως και στα άλλα notebooks, πρέπει να κάνουμε load κάποια dependencies τα οποία θα χρειαστούμε για αυτό το code base.

#+NAME: dependencies
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test_preprocessing.jl

  using DrWatson
  @quickactivate "Masters_Thesis"
  include(srcdir("filenames.jl"))
  using CSV, DataFrames, Statistics, Distributions

#+END_SRC

* Φόρτωση των δεδομένων
Έπειτα, πρέπει να διαβάσουμε τα CSVs με τα δεδομένα για να μπορέσουμε να κάνουμε την ανάλυση μας.

#+NAME: data_reading
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test_preprocessing.jl

  # Read all the data
  exp_35 = "10_11"
  exp_40 = "28_11"
  mix_amount = ["0", "1", "2", "4", "8"]

  # Experiment @35 C
  df35_0 = CSV.read(get_conc_csv(exp_35, mix_amount[1]), DataFrame)
  df35_1 = CSV.read(get_conc_csv(exp_35, mix_amount[2]), DataFrame)
  df35_2 = CSV.read(get_conc_csv(exp_35, mix_amount[3]), DataFrame)
  df35_4 = CSV.read(get_conc_csv(exp_35, mix_amount[4]), DataFrame)
  df35_8 = CSV.read(get_conc_csv(exp_35, mix_amount[5]), DataFrame)

  # Experiment @40 C
  df40_0 = CSV.read(get_conc_csv(exp_40, mix_amount[1]), DataFrame)
  df40_1 = CSV.read(get_conc_csv(exp_40, mix_amount[2]), DataFrame)
  df40_2 = CSV.read(get_conc_csv(exp_40, mix_amount[3]), DataFrame)
  df40_4 = CSV.read(get_conc_csv(exp_40, mix_amount[4]), DataFrame)
  df40_8 = CSV.read(get_conc_csv(exp_40, mix_amount[5]), DataFrame)

#+END_SRC

#+RESULTS: data_reading
#+begin_example
17×8 DataFrame
 Row │ Time   Sucrose    Glucose    Fructose  Lactate   Acetate   Propionate   ⋯
     │ Int64  Float64    Float64    Float64   Float64   Float64   Float64      ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │     0  1.35836    0.984291   2.1892    0.777989  0.515341    0.402087   ⋯
   2 │     1  1.15216    0.829136   1.80418   0.645266  0.433893    0.348323
   3 │     5  1.79113    1.18396    2.14795   0.770491  0.507007    0.431528
   4 │    24  1.51746    1.42083    2.16927   0.794013  0.566514    0.542862
   5 │    26  1.06816    0.950233   1.94116   0.761713  0.51341     0.523717   ⋯
   6 │    28  0.953606   0.0280055  1.75975   0.900778  0.596115    0.562465
   7 │    46  0.0194654  0.0208154  1.68201   1.24803   0.775296    0.687859
   8 │    48  0.0234614  0.0        1.62864   1.19914   0.751814    0.677251
  ⋮  │   ⋮        ⋮          ⋮         ⋮         ⋮         ⋮          ⋮        ⋱
  11 │    72  0.0        0.0        1.55341   0.938808  0.849385    0.742872   ⋯
  12 │    74  0.0        0.0        1.71011   1.0129    1.00473     0.831225
  13 │    94  0.0        0.0        1.72527   0.726517  1.16993     0.915695
  14 │    96  0.0        0.0        1.53916   0.616309  1.07972     0.836887
  15 │    98  0.0        0.0        1.63866   0.620383  1.15156     0.892041   ⋯
  16 │   167  0.0        0.0        0.717977  0.29702   1.43722     1.17576
  17 │   171  0.0        0.0        0.790572  0.656899  1.45461     1.23779
                                                     1 column and 2 rows omitted
#+end_example

* Επεξεργασία πρωτογενών δεδομένων
Βέβαια, δεν θέλουμε αυτούς τους πίνακες. Αρχικά θέλουμε να συγκρίνουμε τις 5 ποσότητες σε κάθε θερμοκρασία, οπότε θέλουμε τα vector των τελικών συγκεντρώσεων κάθε ένωσης.

#+NAME: data_processing
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test_preprocessing.jl

  # Take the maximum instead of defaulting for the last element as we
  # know ethanol is consumed so the last isn't the maximum which is the
  # one we are interested in.
  prod35_0 = map(maximum, eachcol(df35_0[:, 5:8]))
  prod35_1 = map(maximum, eachcol(df35_1[:, 5:8]))
  prod35_2 = map(maximum, eachcol(df35_2[:, 5:8]))
  prod35_4 = map(maximum, eachcol(df35_4[:, 5:8]))
  prod35_8 = map(maximum, eachcol(df35_8[:, 5:8]))

  prod40_0 = map(maximum, eachcol(df40_0[:, 5:8]))
  prod40_1 = map(maximum, eachcol(df40_1[:, 5:8]))
  prod40_2 = map(maximum, eachcol(df40_2[:, 5:8]))
  prod40_4 = map(maximum, eachcol(df40_4[:, 5:8]))
  prod40_8 = map(maximum, eachcol(df40_8[:, 5:8]))

  prod45_1 = map(maximum, eachcol(df45_1[:, 5:8]))
  prod45_2 = map(maximum, eachcol(df45_2[:, 5:8]))

  prod_35 = hcat(prod35_0, prod35_1, prod35_2, prod35_4, prod35_8)
  prod_40 = hcat(prod40_0, prod40_1, prod40_2, prod40_4, prod40_8)

  # Collect the 4 vectors which have the output variable in every condition
  lact_mean_35 = prod_35[1,:]
  acet_mean_35 = prod_35[2,:]
  prop_mean_35 = prod_35[3,:]
  eth_mean_35 = prod_35[4,:]

  lact_mean_40 = prod_40[1,:]
  acet_mean_40 = prod_40[2,:]
  prop_mean_40 = prod_40[3,:]
  eth_mean_40 = prod_40[4,:]

#+END_SRC

#+RESULTS: data_processing
: 5-element Vector{Float64}:
:  0.5066985805374675
:  0.4648568653625852
:  0.49108650090491535
:  0.4551414662652275
:  0.4238722874331631

* Δημιουργία ψευδο-κατανομής των δεδομένων
Για να κάνουμε ANOVA χρειάζεται κάθε μέτρηση να έχει ένα sample size μεγαλύτερο του 1 (και εφόσον κάνουμε στατιστική ανάλυση, τυπικά θέλουμε πάνω από 5 για στατιστικά σημαντικά αποτελέσματα). Δεν μπορούμε να κάνουμε το πείραμα τόσες φορές, οπότε χρειαζόμαστε έναν μηχανισμό για να φτιάξουμε δεδομένα.

Ένα claim το οποίο δεν είναι κακό είναι ότι αν κάναμε πολλές φορές το πείραμα, τα αποτελέσματα θα ακολουθούσαν κανονική κατανομή. Οπότε, με έναν μέσο όρο και μία τυπική απόκλιση, μπορούμε να φτιάξουμε δεδομένα τα οποία θα είναι περίπου σωστά και να τρέξουμε με αυτά την ANOVA. Οι μέσοι όροι θα είναι προφανώς οι τιμές που θα έχουμε παρατηρήσει. Για τις τυπικές αποκλίσεις θέλουμε κάτι άλλο. Με βάση τα στοιχεία που έχουμε, μία εύλογη εκτίμηση είναι να πούμε πως ξέρουμε ότι στην αρχή είχαμε 5 υποτίθεται ίδια δείγματα. Οπότε όποια διαφορά έχουν οφείλεται στην τυπική απόκλιση του δείγματος. Οπότε, ας υποθέσουμε ότι το variance που έχουν αυτά θα το έχουν και τα προιόντα και ας κάνουμε κατανομές αυτές τις τυπικές αποκλίσεις.

** Pre-processing
Για να πάρουμε τα δεδομένα ακολουθούμε μία παρόμοια λογική με παραπάνω και μόλις βρούμε τα διανύσματα που θέλουμε υπολογίζουμε τo standard deviation τους.

#+NAME: input_stdev
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test_preprocessing.jl

  input35_0 = Vector(df35_0[1, 5:8])
  input35_1 = Vector(df35_1[1, 5:8])
  input35_2 = Vector(df35_2[1, 5:8])
  input35_4 = Vector(df35_4[1, 5:8])
  input35_8 = Vector(df35_8[1, 5:8])

  input40_0 = Vector(df40_0[1, 5:8])
  input40_1 = Vector(df40_1[1, 5:8])
  input40_2 = Vector(df40_2[1, 5:8])
  input40_4 = Vector(df40_4[1, 5:8])
  input40_8 = Vector(df40_8[1, 5:8])

  input_35 = hcat(input35_0, input35_1, input35_2, input35_4, input35_8)
  input_40 = hcat(input40_0, input40_1, input40_2, input40_4, input40_8)

  # Collect the 4 vectors which have the input variables in every
  # condition
  lact_input_35 = input_35[1,:]
  acet_input_35 = input_35[2,:]
  prop_input_35 = input_35[3,:]
  eth_input_35 = input_35[4,:]

  lact_input_40 = input_40[1,:]
  acet_input_40 = input_40[2,:]
  prop_input_40 = input_40[3,:]
  eth_input_40 = input_40[4,:]

  # Calculate standard deviations of samples
  lact_std_35 = std(lact_input_35)
  acet_std_35 = std(acet_input_35)
  prop_std_35 = std(prop_input_35)
  eth_std_35 = std(eth_input_35)

  lact_std_40 = std(lact_input_40)
  acet_std_40 = std(acet_input_40)
  prop_std_40 = std(prop_input_40)
  eth_std_40 = std(eth_input_40)
#+END_SRC

#+RESULTS: input_stdev
: 0.014531929680207578

** Δημιουργία των κατανομών
Έχοντας την τυπική απόκλιση και τον μέσο όρο μπορούμε να φτιάξουμε τις κατανομές. Χάριν ευκολίας, θα φτιαχτούν vectorized κατανομές.

#+NAME: distribution_definitions
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test_preprocessing.jl

  lact_dist_35 = [Normal(lact_mean_35[i], lact_std_35) for i in 1:length(lact_mean_35)]
  acet_dist_35 = [Normal(acet_mean_35[i], acet_std_35) for i in 1:length(acet_mean_35)]
  prop_dist_35 = [Normal(prop_mean_35[i], prop_std_35) for i in 1:length(prop_mean_35)]
  eth_dist_35 = [Normal(eth_mean_35[i], eth_std_35) for i in 1:length(eth_mean_35)]

  lact_dist_40 = [Normal(lact_mean_40[i], lact_std_40) for i in 1:length(lact_mean_40)]
  acet_dist_40 = [Normal(acet_mean_40[i], acet_std_40) for i in 1:length(acet_mean_40)]
  prop_dist_40 = [Normal(prop_mean_40[i], prop_std_40) for i in 1:length(prop_mean_40)]
  eth_dist_40 = [Normal(eth_mean_40[i], eth_std_40) for i in 1:length(eth_mean_40)]

#+END_SRC

#+RESULTS: distribution_definitions
: 5-element Vector{Normal{Float64}}:
:  Normal{Float64}(μ=0.5066985805374675, σ=0.014531929680207578)
:  Normal{Float64}(μ=0.4648568653625852, σ=0.014531929680207578)
:  Normal{Float64}(μ=0.49108650090491535, σ=0.014531929680207578)
:  Normal{Float64}(μ=0.4551414662652275, σ=0.014531929680207578)
:  Normal{Float64}(μ=0.4238722874331631, σ=0.014531929680207578)

** Sampling
Έχοντας τις κατανομές, μπορούμε να κάνουμε sample έναν αριθμό από δείγματα για να τρέξουμε την ANOVA. Εφόσον έχουμε την δυνατότητα να πάρουμε όσα samples θέλουμε, μπορούμε να βάλουμε και μεγάλα νούμερα, αλλά για παράδειγμα 20 δείγματα είναι μάλλον ένα καλό νούμερο.

#+NAME: sampling
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test_preprocessing.jl

  samples = 20
  lact_samples_35 = [rand(lact_dist_35[i], samples) for i in 1:length(lact_mean_35)]
  acet_samples_35 = [rand(acet_dist_35[i], samples) for i in 1:length(acet_mean_35)]
  prop_samples_35 = [rand(prop_dist_35[i], samples) for i in 1:length(prop_mean_35)]
  eth_samples_35 = [rand(eth_dist_35[i], samples) for i in 1:length(eth_mean_35)]

  lact_samples_40 = [rand(lact_dist_40[i], samples) for i in 1:length(lact_mean_40)]
  acet_samples_40 = [rand(acet_dist_40[i], samples) for i in 1:length(acet_mean_40)]
  prop_samples_40 = [rand(prop_dist_40[i], samples) for i in 1:length(prop_mean_40)]
  eth_samples_40 = [rand(eth_dist_40[i], samples) for i in 1:length(eth_mean_40)]

#+END_SRC

#+RESULTS: sampling
: 5-element Vector{Vector{Float64}}:
:  [0.49868747265866653, 0.4869343197770326, 0.5157334778753895, 0.5128735756232315, 0.5005028155075176, 0.48958906441704886, 0.4801573347399146, 0.4991816035400777, 0.5032963210721053, 0.5137558608107206, 0.5007474394505066, 0.5148199738497963, 0.4950327163879213, 0.4798104208580435, 0.522120555780145, 0.5158938901875638, 0.516183700840565, 0.4830689229379774, 0.5042507185938094, 0.5130668453562083]
:  [0.4650713867242923, 0.4963371658594932, 0.46075453194872, 0.4818074021646951, 0.4661132434692044, 0.45849112459014957, 0.45478618377326574, 0.4702445472055113, 0.462597102304449, 0.4884472368297681, 0.4679448363556905, 0.46924284570524216, 0.48007196454724466, 0.46938794930539607, 0.49045188035596304, 0.48730022498014375, 0.49593691902479903, 0.45190810190304315, 0.4643560021120398, 0.4954741709345398]
:  [0.5016269247272017, 0.48543179769256234, 0.49364536451733415, 0.47652074640160896, 0.48531253424716364, 0.5197766658623957, 0.4988860879097682, 0.47874263209632795, 0.5254412601034922, 0.5010896983555859, 0.48933990966784424, 0.4920837617288359, 0.505075214635014, 0.4971993104534569, 0.4945317527854313, 0.4838746009410711, 0.49564705047249874, 0.5041972118207785, 0.4787651122907324, 0.5008921618945169]
:  [0.4608312264715753, 0.4590227691142619, 0.4298668627217868, 0.41512159809453886, 0.45581456680596416, 0.45347752484849463, 0.45444696945230517, 0.4307105190804349, 0.44587981606257804, 0.4710798832121142, 0.4779481999256904, 0.45689049802853526, 0.4605879618359982, 0.4366698156107729, 0.4517025808808985, 0.44332846734203823, 0.4676100109514397, 0.4848796676030306, 0.4654749919645743, 0.46994019159722916]
:  [0.42102166874648345, 0.42036784799169524, 0.40101808946323414, 0.39943135128707286, 0.39741508054682617, 0.4212458946586835, 0.41255466724727513, 0.41065082835178546, 0.4101203173345793, 0.4229427439792658, 0.4256893063651016, 0.4233047523426158, 0.43104935853442333, 0.4097915557501248, 0.43204113755448686, 0.43013008037753947, 0.4062311713612946, 0.4477049709648432, 0.4266369221785621, 0.4090072513204785]

* ANOVA
Έχοντας κάνει sample έχουμε τώρα κάποια διανύσματα όπου τα καθένα έχει 20 παρατηρήσεις και μπορεί να γίνει μία ANOVA για να δείξει σε ποιά από τα 8 συστήματα (4 προιόντα, 2 θερμοκρασίες) έπαιξε όντως ρόλο η προσθήκη του μιξ και σε ποιά δεν φαίνεται να έπαιξε. Αρχικά, γράφουμε ένα function που κάνει implement την ANOVA.

#+NAME: anova
#+BEGIN_SRC julia :noweb no-export :tangle ../scripts/hypothesis_test.jl

  <<dependencies>>
  include(scriptsdir("hypothesis_test_preprocessing.jl"))

  function manualANOVA(allData)
      nArray = length.(allData)
      d = length(nArray)

      xBarTotal = mean(vcat(allData...))
      xBarArray = mean.(allData)

      ssBetween = sum( [nArray[i]*(xBarArray[i] - xBarTotal)^2 for i in 1:d] )
      ssWithin = sum([sum([(ob - xBarArray[i])^2 for ob in allData[i]])
				  for i in 1:d])
      dfBetween = d-1
      dfError = sum(nArray)-d

      msBetween = ssBetween/dfBetween
      msError = ssWithin/dfError
      fStat = msBetween/msError
      pval = ccdf(FDist(dfBetween,dfError),fStat)
      return fStat, pval
  end

#+END_SRC

#+RESULTS: anova
: manualANOVA (generic function with 1 method)

και έπειτα το εφαρμόζουμε στα 8 διανύσματα που παράξαμε πριν. Το output θα είναι η τιμή του f-statistic καθώς και το p-value. Τυπικά σε μία ANOVA, αν το f-statistic είναι κοντά στο 1 δεν μπορούμε να απορρίψουμε την υπόθεση H_0 η οποία λέει πως δεν έπαιξε ρόλο η προσθήκη του mix αλλά έγινε τυχαία. Το p-value μας λέει με τι βεβαιότητα απορρίπτουμε ή όχι την υπόθεση.

#+NAME: anova_results
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test.jl

  lact_anova_35 = manualANOVA(lact_samples_35)
  acet_anova_35 = manualANOVA(acet_samples_35)
  prop_anova_35 = manualANOVA(prop_samples_35)
  eth_anova_35 = manualANOVA(eth_samples_35)

  lact_anova_40 = manualANOVA(lact_samples_40)
  acet_anova_40 = manualANOVA(acet_samples_40)
  prop_anova_40 = manualANOVA(prop_samples_40)
  eth_anova_40 = manualANOVA(eth_samples_40)

  anova_35 = reshape([lact_anova_35..., acet_anova_35..., prop_anova_35..., eth_anova_35...], 2, 4)
  anova_40 = reshape([lact_anova_40..., acet_anova_40..., prop_anova_40..., eth_anova_40...], 2, 4)

#+END_SRC

#+RESULTS: anova_results
: 2×4 Matrix{Float64}:
:  483.049        8.13106     30.4874       115.817
:    3.38583e-62  1.10655e-5   2.55448e-16    1.18415e-35

Από τα αποτελέσματα αυτά, είναι εμφανές πως η ποσότητα του mix που προστίθεται είναι σίγουρα σημαντική επειδή όλα τα p-values είναι πάρα πολύ χαμηλά.

Μπορούμε επίσης να τα αποθηκεύσουμε σε έναν ωραίο πίνακα:

#+NAME: anova_tables
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test.jl

  names = ["Lactate_35", "Acetate_35", "Propionate_35", "Ethanol_35", "Lactate_40", "Acetate_40", "Propionate_40", "Ethanol_40"]
  anova_data = hcat(anova_35, anova_40)

  anova_table = Tables.table(hcat(names, anova_data'), header = [:Test, :FStatistic, :pValue])
  CSV.write(datadir("exp_pro", "anova_35_40.csv"), anova_table)
  DataFrame(anova_table)

#+END_SRC

#+RESULTS: anova_tables
#+begin_example
8×3 DataFrame
 Row │ Test           FStatistic  pValue      
     │ Any            Any         Any         
─────┼────────────────────────────────────────
   1 │ Lactate_35     271.031     4.92964e-51
   2 │ Acetate_35     317.189     4.97686e-54
   3 │ Propionate_35  105.405     4.63088e-34
   4 │ Ethanol_35     172.554     1.15034e-42
   5 │ Lactate_40     483.049     3.38583e-62
   6 │ Acetate_40     8.13106     1.10655e-5
   7 │ Propionate_40  30.4874     2.55448e-16
   8 │ Ethanol_40     115.817     1.18415e-35
#+end_example

* Άλλα hypothesis tests
** ANOVA σε 2 mL και πάνω
Από τα διαγράμματα που είχαμε κάνει, είχε παρατηρηθεί πως ενδέχεται να μην έχει νόημα να βάλουμε πάνω από 2 ml του mix. Στους 35, η συμπεριφορά που παρατηρήθηκε ήταν καθαρά αρνητική ενώ στους 40 σε πολλά φάνηκε να είναι περίπου αμελητέα αν όχι αρνητική. Οπότε, έχει νόημα να κάνουμε anova και εδώ για να δούμε τι βγάζει.

#+NAME: ANOVA_2_plus
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test.jl

  lact_anova_35_2plus = manualANOVA(lact_samples_35[3:5])
  acet_anova_35_2plus = manualANOVA(acet_samples_35[3:5])
  prop_anova_35_2plus = manualANOVA(prop_samples_35[3:5])
  eth_anova_35_2plus = manualANOVA(eth_samples_35[3:5])

  lact_anova_40_2plus = manualANOVA(lact_samples_40[3:5])
  acet_anova_40_2plus = manualANOVA(acet_samples_40[3:5])
  prop_anova_40_2plus = manualANOVA(prop_samples_40[3:5])
  eth_anova_40_2plus = manualANOVA(eth_samples_40[3:5])

  anova_35_2plus = reshape([lact_anova_35_2plus..., acet_anova_35_2plus..., prop_anova_35_2plus..., eth_anova_35_2plus...], 2, 4)
  anova_40_2plus = reshape([lact_anova_40_2plus..., acet_anova_40_2plus..., prop_anova_40_2plus..., eth_anova_40_2plus...], 2, 4)

  anova_data_2plus = hcat(anova_35_2plus, anova_40_2plus)

  anova_table_2plus = Tables.table(hcat(names, anova_data_2plus'), header = [:Test, :FStatistic, :pValue])
  CSV.write(datadir("exp_pro", "anova_35_40_2plus.csv"), anova_table_2plus)
  DataFrame(anova_table_2plus)

#+END_SRC

#+RESULTS: ANOVA_2_plus
#+begin_example
8×3 DataFrame
 Row │ Test           FStatistic  pValue      
     │ Any            Any         Any         
─────┼────────────────────────────────────────
   1 │ Lactate_35     252.209     4.87277e-29
   2 │ Acetate_35     47.1273     8.33169e-13
   3 │ Propionate_35  62.9024     3.76521e-15
   4 │ Ethanol_35     255.16      3.61682e-29
   5 │ Lactate_40     390.101     5.51787e-34
   6 │ Acetate_40     5.21984     0.00828594
   7 │ Propionate_40  4.37956     0.0170094
   8 │ Ethanol_40     145.021     4.38079e-23
#+end_example

#+RESULTS:
: 2×4 Matrix{Float64}:
:  390.101        5.21984     4.37956    145.021
:    5.51787e-34  0.00828594  0.0170094    4.38079e-23

Προκύπτει πως στους 35 όλες οι μεταβολές είναι στατιστικά σημαντικές και είναι όλες μειώσεις. Οπότε σίγουρα δεν θέλουμε πάνω από 2 ml. Στους 40, η αιθανόλη μειώνεται με στατιστικά σημαντικό τρόπο ενώ το γαλακτικό αυξάνεται. Το οξικό και το προπιονικό και αυτά αυξάνονται με στατιστικά σημαντικό τρόπο, αλλά έχουν πολύ μεγαλύτερα p-values. Συγκεκριμένα το οξικό μπορούμε να απορρίψουμε την H_0 με confidence interval 99% αλλά οριακά και στο προπιονικό μπορούμε με interval 95%. Οπότε στους 40 υπάρχει επαρκής evidence για να πάμε σε πάνω από 2 ml.

** T-test για 4-8 ml στους 40
Εφόσον στους 40 υπάρχει evidence για να πάμε πάνω από 2 ml, αξίζει να δούμε και αν υπάρχει evidence για να πάμε στα 8 ml ή αν δεν είναι στατιστικά σημαντικό σε σχέση με το 4.

#+NAME: ttest_40
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test.jl

  lact_ttest_40 = EqualVarianceTTest(lact_samples_40[4], lact_samples_40[5])
  acet_ttest_40 = EqualVarianceTTest(acet_samples_40[4], acet_samples_40[5])
  prop_ttest_40 = EqualVarianceTTest(prop_samples_40[4], prop_samples_40[5])
  eth_ttest_40 = EqualVarianceTTest(eth_samples_40[4], eth_samples_40[5])

  ttest_40_res = [pvalue(lact_ttest_40), pvalue(acet_ttest_40), pvalue(prop_ttest_40), pvalue(eth_ttest_40)]
#+END_SRC

#+RESULTS: ttest_40
: 4-element Vector{Float64}:
:  2.22371806920641e-22
:  0.8601425484051867
:  0.05330746828235466
:  3.349408697247747e-9

Τα αποτελέσματα του test αυτού δείχνουν πως η αλλαγή του οξικού και του προπιονικού δεν είναι στατιστικά σημαντική (το οξικό με μεγάλη βεβαιότητα, το προπιονικό οριακά δεν μπορεί να απορριφθεί στο 95%) ενώ η αιθανόλη μειώνεται με στατιστικά σημαντικό τρόπο. Οπότε, αν σκεφτούμε το αυξημένο κόστος της προσθήκης μεγαλύτερης ποσότητας, αφού επηρεάζεται μόνο το γαλακτικό, δεν είναι στατιστικά σημαντική η προσθήκη 8 ml σε αντίθεση με τα 4.

** ANOVA σε 2 ml και κάτω στους 35
Εφόσον στους 35 δεν έχει νόημα να πάμε πάνω από 2, αξίζει να εξεταστεί αν έχει νόημα και το 2 ή μήπως ούτε αυτό χρειάζεται και θα λειτουργούσε το ίδιο και χωρίς ένζυμα.

#+NAME: ANOVA_2_minus
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test.jl

  lact_anova_35_2minus = manualANOVA(lact_samples_35[1:3])
  acet_anova_35_2minus = manualANOVA(acet_samples_35[1:3])
  prop_anova_35_2minus = manualANOVA(prop_samples_35[1:3])
  eth_anova_35_2minus = manualANOVA(eth_samples_35[1:3])

  anova_35_2minus = reshape([lact_anova_35_2minus..., acet_anova_35_2minus..., prop_anova_35_2minus..., eth_anova_35_2minus...], 2, 4)

  new_names = ["Lactate", "Acetate", "Propionate", "Ethanol"]
  anova_table_2minus = Tables.table(hcat(new_names, anova_35_2minus'), header = [:Test, :FStatistic, :pValue])
  CSV.write(datadir("exp_pro", "anova_35_2minus.csv"), anova_table_2minus)
  DataFrame(anova_table_2minus)
#+END_SRC

#+RESULTS: ANOVA_2_minus
: 4×3 DataFrame
:  Row │ Test        FStatistic  pValue      
:      │ Any         Any         Any         
: ─────┼─────────────────────────────────────
:    1 │ Lactate     484.413     1.68593e-36
:    2 │ Acetate     212.78      3.64088e-27
:    3 │ Propionate  34.4211     1.57541e-10
:    4 │ Ethanol     301.943     4.66462e-31

Προκύπτει με πολύ μεγάλη βεβαιότητα ότι οι μεταβολές που υπάρχουν μεταξύ αυτών των 3 είναι στατιστικά σημαντικές. Βέβαια, το οξικό και το προπιονικό μειώνονται με στατιστικά σημαντικό τρόπο, δεν αυξάνονται.

** Επίδραση της θερμοκρασίας
Εκτός από τα παραπάνω που έδειξαν ότι οι διαφορετικές παίζουν ρόλο και ανάλογα με το τι θέλουμε επιλέγουμε ποια θα πάρουμε, έχει νόημα να εξετάσουμε και αν είναι στατιστικά σημαντική η επίδραση της θερμοκρασίας. Για αυτό, πρέπει να κάνουμε t-test μεταξύ ίδιων ποσοτήτων στις 2 θερμοκρασίες. Ο κώδικας για αυτό είναι παρακάτω.

#+NAME: temperature_ttest
#+BEGIN_SRC julia :tangle ../scripts/hypothesis_test.jl

  # Run the hypothesis tests
  lact_temp_ttest = [UnequalVarianceTTest(lact_samples_35[i], lact_samples_40[i]) for i in 1:length(lact_samples_35)]
  acet_temp_ttest = [UnequalVarianceTTest(acet_samples_35[i], acet_samples_40[i]) for i in 1:length(acet_samples_35)]
  prop_temp_ttest = [UnequalVarianceTTest(prop_samples_35[i], prop_samples_40[i]) for i in 1:length(prop_samples_35)]
  eth_temp_ttest = [UnequalVarianceTTest(eth_samples_35[i], eth_samples_40[i]) for i in 1:length(eth_samples_35)]

  # Get the pvalues of each test
  lact_temp_pvalues = pvalue.(lact_temp_ttest)
  acet_temp_pvalues = pvalue.(acet_temp_ttest)
  prop_temp_pvalues = pvalue.(prop_temp_ttest)
  eth_temp_pvalues = pvalue.(eth_temp_ttest)

  # Format them in a nice table and write it to CSV
  temp_ttest_table = Tables.table(hcat(mix_amount, lact_temp_pvalues, acet_temp_pvalues, prop_temp_pvalues, eth_temp_pvalues), header = [:Mix_Amount, :Lactate, :Acetate, :Propionate, :Ethanol])
  CSV.write(datadir("exp_pro", "temp_ttest.csv"), temp_ttest_table)
  DataFrame(temp_ttest_table)
#+END_SRC

#+RESULTS: temperature_ttest
: 5×5 DataFrame
:  Row │ Mix_Amount  Lactate      Acetate      Propionate   Ethanol     
:      │ Any         Any          Any          Any          Any         
: ─────┼────────────────────────────────────────────────────────────────
:    1 │ 0           2.64221e-9   0.00963913   3.67514e-6   3.93492e-20
:    2 │ 1           3.34504e-11  0.0420889    9.52229e-9   7.68513e-30
:    3 │ 2           8.67235e-13  8.92097e-15  0.0366243    1.30894e-29
:    4 │ 4           8.65549e-19  3.93894e-21  2.05434e-17  5.7464e-29
:    5 │ 8           1.46139e-22  4.55379e-20  2.78744e-13  2.11086e-25

Από τα αποτελέσματα, είναι εμφανές πως η θερμοκρασία παίζει ρόλο παντού. Αξίζει να σημειωθεί πως σε 2 τιμές του οξικού και μία του προπιονικού, ο ρόλος της θερμοκρασίας δεν είναι σίγουρος, αλλά με 95% βεβαιότητα μπορούμε να απορρίψουμε την υπόθεση ότι δεν παίζει ρόλο παντού.

* Τελικά Συμπεράσματα
Στο αρχείο αυτό έγιναν διάφορα hypothesis tests με σκοπό να δούμε αν οι παραμέτροι που ελέγχουμε έχουν στατιστικά σημαντική επίδραση στην τελική συγκέντρωση των προιόντων. Σε γενικές γραμμές, οι περισσότερες παραμέτροι έχουν σημαντική επίδραση. Σε κάποιες περιπτώσεις όμως, αυτό το συμπέρασμα δεν μπορεί να βγεί με τόση βεβαιότητα ή δεν μπορεί να βγεί καθόλου.

Τα τεστ που έγιναν είναι τα εξής: ANOVA μεταξύ των 5 διαφορετικών ποσοτήτων mix στις 2 δύο θερμοκρασίες και στα 4 προιόντα. ANOVA μεταξύ των ποσοτήτων 2, 4 και 8 ml και στις 2 θερμοκρασίες για να δούμε αν πραγματικά επιφέρει κάτι η προσθήκη πάνω από 2 ml. t-test μεταξύ 4 και 8 ml στους 40 (όπου είχε νόημα να αυξήσουμε πάνω από 2 ml με βάση το προηγούμενο). ANOVA μεταξύ 0, 1 και 2 ml στους 35 για να δούμε αν έχουν νόημα τα 2 ml επειδή τα παραπάνω σίγουρα δεν έχουν. t-test συγκρίνοντας τις 2 θερμοκρασίες για κάθε mix_amount και ένωση.

Καθώς οι περισσότερες υποθέσεις απορρίφθηκαν με μεγάλη βεβαιότητα (μεγαλύτερη από 99.99%), παρακάτω θα σημειωθούν όσες απορρίφθηκαν με λιγότερη ή δεν μπόρεσαν να απορριφθούν.

** Απόρριψη με 99% βεβαιότητα
Το οξικό στους 40 για ποσότητες 2-8 ml.
Το t-test για την θερμοκρασία στα 0 ml οξικού.

** Απόρριψη με 95% βεβαιότητα
Το προπιονικό στους 40 για ποσότητες 2-8 ml.
Το t-test για την θερμοκρασία στο 1 ml οξικό και στα 2 ml προπιονικό.

** Δεν μπόρεσαν να απορριφθούν
Το t-test για το οξικό και το προπιονικό στους 40 μεταξύ 4 και 8 ml.
