#+TITLE: Notebooks for Data Processing

This directory contains practically all the data processing and analysis, result discussion and conclusions that have been drawn from the main experiments of my thesis and for this reason, I consider it the heart of my thesis.

It is a collection of org mode based notebooksm, built on the premise of literate programming, a paradigm which I consider essential for well documented data analytics. These contain info on what experiments were done in each case, why we are analyzing them in a specific way, the actual processing using the Julia language and org-babel, discussion on the results of this as well as the conclusions that can be drawn from these.

Each notebook is self contained and all the info necessary for it is inside it, but it also exports to different formats. Specifically, it is ~weaved~ into a pdf file for easier sharing via LaTeX and it is ~tangled~ into jl files for sharing the code to someone to reproduce it. The weaved pdfs are in this directory, while the tangled source files are in the directories ~src~ and ~scripts~.

* Description of each notebook
To ease any potential reader of this repository, a small description of each notebook is mentioned here.

- ~anaerobic_digestion_feed_analysis~ is the notebook which analyzes all the data specific to the hydrolysates which were produced for use as AD feedstock. It is a fairly small notebook.
- ~anaerobic_digestion_notebook~ is one of the largest and most in-depth notebooks of this repository. It contains everything that is relevant to the anaerobic digestion experiments, namely the reading of their data, the initial preprocessing, curve fitting of a Gompertz model and various plots for each experiment. After the end of each cycle it also has some comparative plots and tables. Note that this makes very heavy use of org-mode's noweb syntax to reduce repetition in a way that makes each code block independent, but with much better interpretability than using Julia functions, which for this purpose would need multiple input and output arguments (which would make it a headache in my opinion).
- ~cod_balance_notebook~ is another small notebook. Its purpose is to process COD absorbance data to concentrations and besides that try and calculate the COD-eq of the HPLC measurements, in an attempt to see if all the COD is relevant to the compounds measured in HPLC. It also contains the acidification plots which are very important to the process.
- ~hplc_analysis_notebook~ is another decently large notebook, which analyzes all concentration data in the hydrolysis experiments taken with HPLC. HPLC exports area data, so their conversion to concentration is necessary. After, it creates different styled plots, some yield plots and comparisons based on these. It also makes use of the noweb syntax in many places.
- ~hydrolysis_hypothesis_testing_sensitivity~ is a notebook concerning the hypothesis testing and sensitivity results for the hydrolysis experiments. It arguably contains the most important results for the hydrolysis experiments, as they are more comparative and in-depth, compared to the HPLC results which are the initial preprocessed results of the concentrations of each compound. It starts with ANOVA and t-tests to determine which changes significantly affect the process and then quantifies these changes with the sensitivity analysis, with various visualizations for it.
- Lastly, the ~metabolic_pathways_notebook~ contains all the analysis for a project to attempt to computationally predict the metabolic pathways of the reactor using only information from literature as well as the input and output concentrations. This is a very interesting idea, which has theoretical basis, but its findings are hard to prove experimentally. However, a lot of work has been put into it and I consider it a very interesting project.
