#+TITLE: Οξικογένεση και Μεθανογένεση

* COMMENT Επεξήγηση
Στο αρχείο αυτό θα αναλυθούν η οξικογένεση και η μεθανογένεση. Αρχικά θα μιλήσω για την θερμοδυναμική της παραγωγής μεθανίου, πως ενεργοποιούνται οι οξεογενετικές αντιδράσεις και τα πλεονεκτήματα και μειονεκτήματα κάθε οξεογενετικού προιόντος. Μόλις φτάσουμε στην αιθανόλη, θα αναλύσουμε πως λειτουργεί το IHT και τις διαφορές με DIET και γιατί αυτό θεωρείται συχνά το προτινόμενο μοντέλο μεταφοράς ηλεκτρονίων και πως μπορεί να προωθηθεί. Θα αναφέρει και Gompertz για κινητική παραγωγής μεθανίου. Ίσως βάλω και για microbial community interactions και για τα αρχαία, αλλά επειδή δεν έχουμε τέτοια ανάλυση, ίσως δεν χρειάζεται καν.

* Οξικογένεση και Μεθανογένεση
\label{sec:methanogenesis}

Στα προηγούμενα κεφάλαια αναλύθηκαν εις βάθος η υδρόλυση και η οξεογένεση, τα 2 πρώτα στάδια της \acrshort{ad}, τα οποία είναι και αυτά που συνήθως διαχωρίζονται όταν η διεργασία διεξάγεται σε 2 στάδια. Συγκεκριμένα, στο \autoref{sec:acidogenesis} αναλύθηκαν όλα τα πιθανά μονοπάτια οξεογένεσης και τα προϊόντα του καθενός και αναφέρθηκε πως είναι επιθυμητό να ελεγχθεί το μεταβολικό μονοπάτι που θα ακολουθηθεί επειδή δεν είναι όλα τα προϊόντα το ίδιο χρήσιμα για την μεθανογένεση. Για να επεξηγηθεί αυτό, θα πρέπει να εξεταστεί σε βάθος ο μηχανισμός με τον οποίο διεξάγεται η μεθανογένεση, το οποίο είναι ο σκοπός του κεφαλαίου αυτού.
** Μηχανισμός Μεθανογένεσης
Η μεθανογένεση είναι το σημαντικότερο αλλά και πιο ευαίσθητο στάδιο της αναερόβιας χώνευσης. Γίνεται από μικροοργανισμούς του κλάδου των αρχαίων, οι οποίοι είναι υποχρεωτικά αναερόβιοι μικροοργανισμοί με στενό λειτουργικό εύρος pH (περίπου 6.4-8.0). Τα αρχαία τα οποία παράγουν μεθάνιο διαχωρίζονται σε δύο βασικές κατηγορίες, τους ακετοκλαστικούς μεθανογόνους (\acrshort{am}), οι οποίοι χρησιμοποιούν το οξικό οξύ ως υπόστρωμα και τους υδρογονοτρόφους μεθανογόνους (\acrshort{hm}), οι οποίοι ανάγουν διοξείδιο του άνθρακα σε μεθάνιο παρουσία υδρογόνου. Σε κανονικές συνθήκες, περίπου 2/3 του μεθανίου παράγονται από τους \acrshort{am} ενώ τα υπόλοιπα από τους \acrshort{hm} [cite:@liDynamicsMicrobialCommunity2015; @muEmergingStrategiesEnhancing2023] .

Για να έχουν υπόστρωμα οι μικροοργανισμοί αυτοί, πρέπει όλα τα προϊόντα της οξεογένεσης να μετατραπούν σε οξικό οξύ και υδρογόνο. Για αυτό υπάρχει το στάδιο της οξικογένεσης. Στο στάδιο αυτό, τα διάφορα προϊόντα που παράχθηκαν κατά την οξεογένεση μετατρέπονται σε οξικό οξύ, ενώ ταυτόχρονα παράγεται και υδρογόνο, καθώς όλες οι αντιδράσεις αυτές είναι οξειδωτικές. Σε αντίθεση όμως με τα 2 προηγούμενα και το επόμενο στάδιο, τα οποία γίνονται αυθόρμητα αν υπάρχει το κατάλληλο μικροβιακό δυναμικό, υπόστρωμα και λειτουργικές συνθήκες, οι περισσότερες οξικογενετικές αντιδράσεις δεν είναι αυθόρμητες σε καμία περιοχή του λειτουργικού εύρους που εξετάζεται [cite:@pipynLactateEthanolIntermediates1981] . Ο μηχανισμός με τον οποίο διεξάγονται οι αντιδράσεις αυτές είναι γνωστός ως συντροφικός μεταβολισμός. Για κάθε ένα από τα συχνά προϊόντα της οξεογένεσης, το άθροισμα των αντιδράσεων οξικογένεσης και παραγωγής μεθανίου από οξικό οξύ και υδρογόνο έχει αρνητική \acrshort{dg}, δηλαδή είναι αυθόρμητο. Οπότε, μπορεί να γίνει η αντίδραση οξικογένεσης, η οποία δεν είναι επιθυμητή για το σύστημα, επειδή τα προϊόντα της θα μεταβολιστούν από τους μεθανογόνους και ο συνδυασμός θα είναι ενεργειακά ωφέλιμος [cite:@supapholMicrobialCommunityDynamics2011; @liDynamicsMicrobialCommunity2015; @pipynLactateEthanolIntermediates1981] .

Με βάση αυτό, ένα από τα βασικά κριτήρια για την ποιότητα ενός προϊόντος για αναερόβια χώνευση είναι η θερμοδυναμική των αντιδράσεων αυτών, η οποία θα αναλυθεί παρακάτω.

** Θερμοδυναμική Παραγωγής Μεθανίου
Τα προϊόντα τα οποία θα συζητηθούν εδώ θα είναι τα εξής: Οξικό οξύ, προπιονικό οξύ, γαλακτικό οξύ, βουτηρικό οξύ, αιθανόλη. Τα υπόλοιπα προϊόντα που μπορούν να παραχθούν από οξεογένεση ή δεν παράγονται σε μεγάλη ποσότητα (πχ βαλερικό οξύ) ή όταν παράγονται, ο σκοπός της διεργασίας δεν είναι η παραγωγή μεθανίου (πχ ακετόνη ή βουτανόλη) [cite:@pipynLactateEthanolIntermediates1981; @zhangAnaerobicFermentationPretreated2021; @kohnRoleThermodynamicsControlling2000] . Ως αρχικό υπόστρωμα θα εξεταστεί η γλυκόζη, καθώς τα σάκχαρα είναι και το συχνότερο υπόστρωμα της \acrshort{ad}.

Η μετατροπή της γλυκόζης σε μεθάνιο (\( C_6H_{12}O_6 \rightarrow 3CH_4 + 3CO_2 \)) είναι μία αυθόρμητη αντίδραση με \acrshort{dg} = - 404 kJ/mol σε πρότυπες συνθήκες [cite:@pipynLactateEthanolIntermediates1981] . Από τον νόμο του Hess, είναι γνωστό πως η ενθαλπία (και κατ'επέκτασην η ελεύθερη ενέργεια Gibbs) μίας αντίδρασης είναι ίδια ανεξαρτήτως του μονοπατιού με το οποίο έγινε η αντίδραση. Οπότε, ανεξαρτήτως του ενδιαμέσου, το σύστημα της \acrshort{ad} θα παράγει αυτή την ενέργεια για αυτήν την μετατροπή. Όμως, όσο πιο κοντά στο 0 είναι το άθροισμα των \acrshort{dg} της οξικογένεσης και μεθανογένεσης, τόσο πιο δύσκολο είναι να ολοκληρωθεί η αντίδραση με βάση το μονοπάτι αυτό. Ακόμη, οι \acrshort{dg} που θα αναφερθούν παρακάτω είναι σε πρότυπες συνθήκες. Σε διαφορετικά pH (δηλαδή συγκέντρωση υδρογονοκατιόντων) ή σε διαφορετική συγκέντρωση του κάθε προϊόντος, μπορεί η \acrshort{dg} της αντίδρασης να είναι διαφορετική. Οπότε, αν είναι κοντά στο 0 σε πρότυπες συνθήκες, είναι πιθανόν να υπάρχει συνθήκη όπου η αντίδραση δεν μπορεί πλέον να συνεχίσει.

*** Οξικό Οξύ:
Το οξικό οξύ είναι το ιδανικό υπόστρωμα για μεθανογένεση καθώς είναι το μόνο που μεταβολίζεται απευθείας σε μεθάνιο. Οι αντιδράσεις μεθανογένεσης που διεξάγονται είναι οι

\begin{subequations}
\label{eqn:methanogenesis}
\begin{align}
2CH_3COO^- + 2H_2O &\rightarrow 2CH_4 + 2HCO_3^- & \text{ΔG = - 62.0 kJ} \label{eqn:acet-methane} \\
4H_2 + HCO_3^- + H^+ &\rightarrow CH_4 + 3H_2O & \text{ΔG = -135.6 kJ} \label{eqn:hydro-methane} \\
\hline
2CH_3COO^- + 4H_2 + H^+ &\rightarrow 3 CH_4 + HCO_3^- + H_2O & \text{ΔG = -197.6 kJ} \label{eqn:complete-methane}
\end{align}
\end{subequations}

με αποτέλεσμα το στάδιο αυτό να είναι αυθόρμητο με \acrshort{dg} = -197.6 kJ (αξίζει να αναφερθεί πως οι συντελεστές είναι με βάση τις ποσότητες που παράγει 1 mol γλυκόζη) [cite:@pipynLactateEthanolIntermediates1981] .

*** Προπιονικό Οξύ:
Το προπιονικό οξύ είναι συχνό αναγωγικό προϊόν του μεταβολισμού του πυροσταφυλικού οξέος και παρατηρείται συχνά στην \acrshort{ad} [cite:@daiValuableBiochemicalProduction2017; @zhouEnhancedVolatileFatty2018a] . Εκτός από τις αντιδράσεις \ref{eqn:acet-methane}, \ref{eqn:hydro-methane}, γίνεται και η αντίδραση

\begin{align}
2CH_3CH_2COO^- + 6H_2O &\rightarrow 2CH_3COO^- + 2HCO_3^- + 2H^+ + 6H_2 & \text{ΔG = + 152.2 kJ}
\label{eqn:prop-acet}
\end{align}

με αποτέλεσμα, το άθροισμα οξεογένεσης και μεθανογένεσης να είναι -45.4 kJ. Η αντίδραση αυτή παραμένει αυθόρμητη, όμως αποτελεί μία πολύ πιο δύσκολη αντίδραση, διότι οι μεθανογόνοι σπαταλούν πολύ περισσότερη ενέργεια για να διεξαχθεί [cite:@pipynLactateEthanolIntermediates1981; @muEmergingStrategiesEnhancing2023]. Επιπλέον, σε συνθήκες μακριά από τις πρότυπες (πχ μεγάλη μερική πίεση υδρογόνου ή πολύ όξινο περιβάλλον), η \acrshort{dg} την αντίδρασης \ref{eqn:prop-acet} θα είναι ακόμη μεγαλύτερη, με αποτέλεσμα το άθροισμα να είναι ακόμη πιο κοντά στο 0. Σε ακραίες περιπτώσεις, έχει παρατηρηθεί και κατάρρευση του συστήματος της \acrshort{ad} επειδή έχει παραχθεί πολύ προπιονικό οξύ και στις συνθήκες που υπάρχουν, δεν μπορεί να μετατραπεί σε μεθάνιο. Οπότε, το προπιονικό οξύ είναι γενικά ένα αρκετά ανεπιθύμητο προϊόν [cite:@patonComprehensiveBioenergeticEvaluation2020; @pipynLactateEthanolIntermediates1981; @wangEffectsVolatileFatty2009] . Όμως, καθώς αποτελεί το βασικότερο αναγωγικό προϊόν της οξεογένεσης, συχνά δεν μπορεί να αποφευχθεί πλήρως [cite:@zhouEnhancedVolatileFatty2018a]. Στην βιβλιογραφία, έχουν προταθεί τρόποι για να γίνει πιο εύκολη η αντίδραση αυτή και να μην αναστέλλει το σύστημα, όπως η προσθήκη σιδήρου μηδενικού σθένους (\acrshort{zvi}), ο οποίος μειώνει αρκετά το \acrshort{redox} του αντιδραστήρα, το οποίο κάνει πολύ πιο αρνητικό το \acrshort{dg} της αντίδρασης [cite:@chengNanoscaleZerovalentIron2020] αλλά και άλλες τεχνολογίες όπως η προσθήκη κάποιου buffer, ή απαραίτητων ιχνοστοιχείων για να γίνει πιο αποτελεσματική η αντίδραση [cite:@muEmergingStrategiesEnhancing2023] .

*** Γαλακτικό Οξύ:
Το άλλο συχνό αναγωγικό προϊόν είναι το γαλακτικό οξύ, το οποίο όπως αναφέρθηκε, παράγεται σε μεγάλες ποσότητες κατά την ζύμωση \acrshort{fw} [cite:@fengEffectPrefermentationTypes2020; @wuLacticAcidProduction2015] . Το γαλακτικό οξύ είναι ένα ενδιαφέρον ενδιάμεσο για την \acrshort{ad} καθώς η αναγωγή του σε προπιονικό οξύ και η οξείδωση του σε οξικό είναι και οι δύο κοντά στην ισορροπία. Σε πρότυπες συνθήκες είναι οι εξής: [cite:@pipynLactateEthanolIntermediates1981; @saadyHomoacetogenesisHydrogenProduction2013]

\begin{subequations}
\label{eqn:lact-redox}
\begin{align}
2CH_3CHOHCOO^- &\rightarrow 2CH_3COO^- + 2HCO_3^- + 2H^+ + 4H_2 & \text{ΔG = - 8.4 kJ} \label{eqn:lact-ox} \\
2CH_3CHOHCOO^- &\xrightarrow{2NADH \rightarrow 2NAD^+} 2CH_3CH_2COO^- & \text{ΔG = 27.6 kJ} \label{eqn:lact-red}
\end{align}
\end{subequations}

Επίσης υπενθυμίζεται πως το ζεύγος \acrshort{nadh} με \acrshort{nad} είναι ένα οξειδωαναγωγικό ζεύγος με την ισορροπία

\begin{align}
NADH + H^+ &\rightleftharpoons NAD^+ + H_2 & ΔG = - 21.8 \frac{kJ}{mol}
\label{eqn:nadh}
\end{align}

Άρα, σε πρότυπες συνθήκες, θερμοδυναμικά επιθυμητή είναι η αντίδραση \ref{eqn:lact-ox}, οπότε θεωρητικά θα έπρεπε το γαλακτικό οξύ να είναι ένα ιδιαίτερα επιθυμητό προϊόν της \acrshort{ad}. Όμως, η \acrshort{ad} λειτουργεί σε ένα αρκετά αναγωγικό περιβάλλον, όπου το \acrshort{nadh} είναι συχνότερα στην ανηγμένη μορφή του και άρα η \ref{eqn:lact-red} ευνοείται πολύ περισσότερο, ενώ η \ref{eqn:lact-ox} έχει γίνει θερμοδυναμικά ανέφικτη. Βέβαια, η συντροφική δράση των μικροοργανισμών αυτών με τους μεθανογόνους κάνει την αντίδραση αυτή εφικτή, όπως και για τα άλλα προϊόντα. Στην πράξη, o πιο συχνός μεταβολισμός του γαλακτικού οξέος είναι ένας μικτός μεταβολισμός με βάση την αντίδραση

\begin{align}
3CH_3CHOHCOOH &\rightarrow 2CH_3CH_2COOH + CH_3COOH + HCO_3^- + H^+ & \text{ΔG = -165 kJ}
\label{eqn:mixed-lact}
\end{align}

Η αντίδραση αυτή είναι μία οξειδωαναγωγική αντίδραση όπου τα υδρογόνα της \ref{eqn:lact-ox} χρησιμοποιούνται για την \ref{eqn:lact-red} με αποτέλεσμα μία ιδιαίτερα θερμοδυναμική επιθυμητή αντίδραση. Αυτή είναι η αντίδραση που ακολουθείται όταν και οι δύο αντιδράσεις είναι πολύ κοντά σε ισορροπία [cite:@saadyHomoacetogenesisHydrogenProduction2013] . 

Οπότε, το γαλακτικό οξύ δεν είναι ένα ιδιαίτερα επιθυμητό ενδιάμεσο, λόγω της πιθανότητας να μεταβολιστεί σε προπιονικό [cite:@pipynLactateEthanolIntermediates1981], αλλά υπό τις κατάλληλες συνθήκες αποτελεί ένα πολύ καλό ενδιάμεσο της διεργασίας και κάποιες μελέτες έχουν δείξει πολύ καλή απόδοση στην \acrshort{ad} από υπόστρωμα πλούσιο σε γαλακτικό [cite:@chengNanoscaleZerovalentIron2020; @fengEffectPrefermentationTypes2020] .

*** Βουτηρικό Οξύ:
Το βουτηρικό οξύ είναι ένα ακόμη σύνηθες προϊόν της οξεογένεσης [cite:@chenImprovingBiomethaneYield2015; @zhouEnhancedVolatileFatty2018a] . Η οξικογένεση του βουτηρικού είναι η αντίδραση

\begin{align}
CH_3CH_2CH_2COO^- + 2H_2O &\rightarrow 2CH_3COO^- + H^+ + 2H_2 & \text{ΔG = + 48.1 kJ}
\label{eqn:but-ox}
\end{align}

Η αντίδραση αυτή δεν είναι αυθόρμητη σε πρότυπες συνθήκες, αλλά σε συντροφικό μεταβολισμό με τις αντιδράσεις \ref{eqn:methanogenesis} έχει ένα τελικό \acrshort{dg} = -149.5 kJ [cite:@saadyHomoacetogenesisHydrogenProduction2013; @pipynLactateEthanolIntermediates1981]. Γενικά το βουτηρικό οξύ είναι ένα προϊόν το οποίο μετατρέπεται εύκολα σε μεθάνιο λόγω αυτού και υπάρχουν μελέτες που έχουν δείξει πως είναι ένα από τα πιο επιθυμητά προϊόντα της οξεογένεσης [cite:@zhouEnhancedVolatileFatty2018a; @wangEffectsVolatileFatty2009; @chenImprovingBiomethaneYield2015] .

*** Αιθανόλη:
Η αιθανόλη είναι το τελευταίο προϊόν το οποίο θα εξεταστεί. Αποτελεί ένα αναγωγικό προϊόν του \acrshort{acet-coa} που παράγεται ως συμπροϊόν του οξικού οξέος σε χαμηλά pH [cite:@qiaoOrientedFermentationFood2020; @zhouEnhancedVolatileFatty2018a] . Η αιθανόλη μπορεί να μετατραπεί σε οξικό αρκετά εύκολα για τον λόγο αυτό. Η αντίστοιχη αντίδραση είναι η

\begin{align}
2C_2H_5OH + 2H_2O &\rightarrow 2CH_3COO^- + 2H^+ + 4H_2 & \text{ΔG = + 19.2 kJ}
\label{eqn:eth-acet}
\end{align}

η οποία έχει θετική αλλά χαμηλή \acrshort{dg} με αποτέλεσμα σε συνδυασμό με τις αντιδράσεις \ref{eqn:methanogenesis} να έχει \acrshort{dg} = -178.4 kJ, το οποίο καθιστά την μετατροπή της αιθανόλης σε μεθάνιο αρκετά εύκολη. Ακόμη, σε ορισμένες συνθήκες (χαμηλή μερική πίεση υδρογόνου, υψηλή συγκέντρωση αιθανόλης) μπορεί η αντίδραση αυτή να γίνει αυθόρμητη και από μόνη της και να παρατηρηθεί οξικογένεση χωρίς συντροφική μεθανογένεση [cite:@pipynLactateEthanolIntermediates1981; @saadyHomoacetogenesisHydrogenProduction2013] . 

Εκτός από το γεγονός ότι είναι ένα ενδιάμεσο που μετατρέπεται εύκολα σε μεθάνιο και άρα είναι καλό για μεθανογένεση [cite:@fengEffectPrefermentationTypes2020; @zhuUsingStrawBioethanol2019], η αιθανόλη έχει δείξει να βελτιώνει την ρυθμιστική ικανότητα του αντιδραστήρα [cite:@yuEthanolPrefermentationFood2018] και να προάγει το μεταβολικό μονοπάτι \acrfull{diet} για την μεθανογένεση, το οποίο είναι πολύ ενεργειακά αποτελεσματικό [cite:@zhuAlleviatingAcidInhibition2022; @zhaoApplicationEthanoltypeFermentation2019; @rotaruNewModelElectron2013] . Τα πλεονεκτήματα του μονοπατιού αυτού έναντι του συμβατικού (\acrfull{iht}) θα αναλυθούν περισσότερο παρακάτω.

** Πλεονεκτήματα του Direct Interspecies Electron Tranfer (DIET) στην Mεθανογένεση
Το συμβατικό μοντέλο συντροφικού μεταβολισμού μεταξύ των οξικογόνων μικροοργανισμών και των μεθανογόνων, βασίζεται στην παραγωγή οξικού οξέος αλλά και υδρογόνου, η μεθανογένεση των οποίων προσφέρει στο σύστημα την απαιτούμενη ενέργεια για να λειτουργήσει [cite:@saadyHomoacetogenesisHydrogenProduction2013; @pipynLactateEthanolIntermediates1981] . Ο ρόλος του υδρογόνου είναι η αναγωγή του CO_2 σε CH_4. Ένα αναγωγικό μέσο είναι μία ένωση που προσφέρει ηλεκτρόνια σε άλλες ενώσεις. Οπότε, ουσιαστικά το υδρογόνο δρα ως ένας φορέας ηλεκτρονίων τον οποίο δημιουργούν οι οξικογόνοι για να προσφέρουν στους μεθανογόνους. Ο μηχανισμός αυτός λέγεται \acrfull{iht} [cite:@saadyHomoacetogenesisHydrogenProduction2013; @rotaruNewModelElectron2013] .

Όμως, το υδρογόνο δεν αποτελεί το κύριο προϊόν της οξείδωσης. Το κύριο προϊόν μίας οξειδωτικής αντίδρασης είναι τα ηλεκτρόνια, τα οποία παράγουν το υδρογόνο για να μεταφέρουν την αναγωγική τους ιδιότητα σε κάποια ένωση. Στην πράξη, όλες οι οξικογενετικές αντιδράσεις είναι οξειδωαναγωγικές αντιδράσεις, των οποίων η αναγωγική ημί-αντίδραση είναι η

\begin{align}
2H^+ + 2e^- &\rightleftharpoons H_2 & \text{ΔG = 856.9 kJ/mol}
\label{eqn:hydrogen}
\end{align}

Για παράδειγμα, η οξικογένεση από προπιονικό οξύ είναι στην ουσία το άθροισμα των αντιδράσεων

\begin{subequations}
\label{eqn:prop-redox}
\begin{align}
2CH_3CH_2COO^- + 6H_2O \rightarrow 2CH_3COO^- + 2HCO_3^- + 14H^+ + 12e^-  \label{eqn:prop-ox} \\
12H^+ + 12e^- \rightarrow 6H_2 \label{eqn:hydro-red} \\
\hline
2CH_3CH_2COO^- + 6H_2O \rightarrow 2CH_3COO^- + 2HCO_3^- + 2H^+ + 6H_2 \label{eqn:prop-acet-comp}
\end{align}
\end{subequations}

Το πρόβλημα, έγκειται στο γεγονός ότι η θερμοδυναμική ευνοεί τον ιοντισμό του υδρογόνου σε υδρογονοκατιόντα και ηλεκτρόνια, αλλά δεν ευνοεί την αντιστροφή της αντίδρασης αυτής. Σε μία παρόμοια λογική με παραπάνω, η αντίδραση αυτή γίνεται επειδή το σύστημα θα κερδίσει ενέργεια αν παραχθεί υδρογόνο, μεταφερθεί στους \acrfull{hm} και αυτοί το μεταβολίσουν. Όμως, αν μπορούσαν να μεταφερθούν απευθείας τα ηλεκτρόνια και να ανάγουν αυτά το CO_2 κατά την μεθανογένεση, το σύστημα θα ήταν πολύ πιο αποδοτικό ενεργειακά [cite:@rotaruNewModelElectron2013] .

Αυτό είναι το μεταβολικό μονοπάτι \acrfull{diet}, στο οποίο παρακάμπτεται η παραγωγή υδρογόνου και τα ηλεκτρόνια μεταφέρονται απευθείας. Το μονοπάτι αυτό παρατηρήθηκε πρώτη φορά μεταξύ του ζεύγους μικροοργανισμών των γενών Geobacter (οξικογόνοι) και Methanosaeta (ακετοκλαστικοί μεθανογόνοι) από τους [cite:@rotaruNewModelElectron2013] κατά την επεξεργασία υγρών αποβλήτων ζυθοποιίας. Με μία μικροβιακή ανάλυση, παρατηρήθηκε πως οι \acrshort{hm} ήταν λιγότερο από \( 1 \% \) των αρχαίων, όμως, ενώσεις όπως η αιθανόλη μεταβολιζόντουσαν κανονικά. Ακόμη, η παραγωγή μεθανίου ήταν περισσότερη από ότι θα μπορούσε να είναι αν μόνο το οξικό μετατρεπόταν σε μεθάνιο. Μετά από διερεύνηση, βρέθηκαν γονίδια αναγωγής του CO_2, παρότι η αναγωγή δεν γινόταν από υδρογόνο. Οπότε, υποτέθηκε πως τα ηλεκτρόνια μεταφέρονται απευθείας από την μία ομάδα μικροοργανισμών στην άλλη.

Μετά την δημοσίευση αυτή, έγινε πολύ περισσότερη έρευνα πάνω στον μηχανισμό αυτόν. Βρέθηκε πως και άλλοι μικροοργανισμοί μπορούν να συμμετέχουν σε αυτόν τον μεταβολισμό [cite:@rotaruDirectInterspeciesElectron2014] και διαπιστώθηκε πειραματικά πως ο λόγος που βρέθηκε πρώτα σε απόβλητα ζυθοποιίας είναι επειδή η αιθανόλη ενεργοποιεί το μονοπάτι αυτό, όχι μόνο αν υπάρχει εξαρχής εκεί, αλλά και στην περίπτωση που γίνει ένα ethanol-type fermentation κατά την οξεογένεση [cite:@zhaoCommunitiesStimulatedEthanol2016; @zhaoNewApplicationEthanolType2017; @zhaoApplicationEthanoltypeFermentation2019] . Αυτό είναι ιδιαίτερα ενδιαφέρον για όξινα απόβλητα όπως τα \acrshort{fw} επειδή σε μία αναερόβια χώνευση σε 2 στάδια, είναι συχνό ένα από τα κύρια προϊόντα της οξεογένεσης να είναι η αιθανόλη και άρα να ενεργοποιηθεί το \acrshort{diet} [cite:@yeImprovingStabilityEfficiency2018; @zhuAlleviatingAcidInhibition2022] . Ακόμη, βρέθηκε πως εκτός από την αιθανόλη, η προσθήκη αγώγιμων ενώσεων ή πρόσθετων μπορεί να ενεργοποιήσει και να ενισχύσει το μονοπάτι αυτό για ακόμη καλύτερη αποδοτικότητα. Υλικά όπως ο ενεργός άνθρακας, το biochar ή ο \acrshort{zvi} μελετήθηκαν στην διεργασία αυτή και φάνηκε πως την βελτιώνουν [cite:@yeImprovingStabilityEfficiency2018; @zhuAlleviatingAcidInhibition2022; @jiangEngineeringApplicationIntegrating2022] .

Εκτός όμως από τα πλεονεκτήματα του \acrshort{diet} ενεργειακά, έχει παρατηρηθεί πως μπορεί να βοηθήσει και στην ρυθμιστική ικανότητα του αντιδραστήρα [cite:@yuEthanolPrefermentationFood2018; @zhuAlleviatingAcidInhibition2022] αλλά και στην αντοχή του σε μεγάλες συγκεντρώσεις \acrshort{vfa}, υψηλά \acrshort{olr} και υψηλή μερική πίεση υδρογόνου. Ως αποτέλεσμα, η μεθανογένεση μέσω του \acrshort{diet} είναι πολύ πιο σταθερή, εκτός από αποτελεσματική [cite:@jiangEngineeringApplicationIntegrating2022; @zhaoCommunitiesStimulatedEthanol2016; @zhaoPotentialEnhancementDirect2016] .

** Απόκριση της μεθανογένεσης
Παραπάνω αναφέρθηκε η ποιότητα του κάθε προϊόντος για την μεθανογένεση σε θεωρητικό επίπεδο. Στην πράξη, για να μετρηθεί η ποιότητα ενός υποστρώματος για μεθανογένεση, χρησιμοποιείται το \acrfull{bmp} ή κάποια άλλη παρόμοια δοκιμή. Σκοπός αυτών είναι μία batch δοκιμή στην οποία μπορεί να υπάρξει εύκολη 24ωρή παρατήρηση της αναερόβιας χώνευσης και μπορούν να εξεταστούν πολλά υποστρώματα ταυτόχρονα. Έτσι, μπορεί να γίνει μία ανάλυση της μέγιστης ποσότητας μεθανίου που μπορεί να παράξει κάθε υπόστρωμα (είτε ανά gCOD που καταναλώνεται ή ανά gVS λάσπης του αντιδραστήρα) καθώς και του ρυθμού παραγωγής τους. Έτσι, μπορεί να προκύψει το βέλτιστο υπόστρωμα από όσα θα εξεταστούν [cite:@chenImprovingBiomethaneYield2015; @fengEffectPrefermentationTypes2020; @dharTechnoeconomicEvaluationUltrasound2012; @hobbsEnhancingAnaerobicDigestion2018] .

Στην περίπτωση του ρυθμού παραγωγής, ο προσδιορισμός του ρυθμού απαιτεί την επιλογή του κινητικού μοντέλου. Για αυτό έχουν προταθεί πολλά μοντέλα, όπως το λογιστικό μοντέλο, το μοντέλο κόνου, το μοντέλο Richards και το μοντέλο Gompertz [cite:@fengEffectPrefermentationTypes2020; @zwieteringModelingBacterialGrowth1990; @yuEthanolPrefermentationFood2018; @sunyotoEffectBiocharAddition2016] . Οι [cite:@zwieteringModelingBacterialGrowth1990] έδειξαν πως το μοντέλο Gompertz, το οποίο περιγράφεται από την εξίσωση \ref{eqn:gompertz}

\begin{equation}
y = a\exp [-\exp(b-cx)]
\label{eqn:gompertz}
\end{equation}

είναι ένα μοντέλο το οποίο έχει αρκετή πολυπλοκότητα για να περιγράψει πολύ αναλυτικά την βακτηριδιακή ανάπτυξη (σε αντίθεση με απλούστερα μοντέλα όπως το λογιστικό), ενώ μοντέλα με μεγαλύτερη πολυπλοκότητα (πχ περισσότερες παραμέτρους όπως το μοντέλο Richards) δεν βελτιώνουν ιδιαίτερα την απόδοση της προσαρμογής. Συγκεκριμένα, προτείνουν μία τροποποίηση του μοντέλου ώστε οι 3 σταθερές του να αποκτήσουν φυσικό νόημα. Η εξίσωση που προκύπτει είναι η

\begin{equation}
y = A \exp \left[ -\exp \left( \frac{μ_{\max }e}{Α} (λ-t) + 1 \right) \right]
\label{eqn:mod-gompertz}
\end{equation}

στην οποία η σταθερά Α είναι το πλατό της καμπύλης της μικροβιακής ανάπτυξης (στάσιμη φάση), η σταθερά μ_max είναι ο μέγιστος ειδικός ρυθμός ανάπτυξης της μικροβιακής διεργασίας και λ ο χρόνος καθυστέρησης της.

Το μοντέλο αυτό έχει χρησιμοποιηθεί ευρέως για την μοντελοποίηση της μεθανογένεσης με πολύ καλά αποτελέσματα [cite:@khadkaEffectSubstrateInoculum2022; @hobbsEnhancingAnaerobicDigestion2018; @fangSynergisticCodigestionWaste2020; @fengEffectPrefermentationTypes2020; @uckunkiranEnhancingHydrolysisMethane2015] .
