#+TITLE: Συμπεράσματα

* COMMENT Outline
Στα συμπεράσματα κάνουμε ένα briefing των όσων είπαμε

** Intro
FW = problem

AD = potential solution due to high TRL, but many advantages over conventional treatment

2-phase AD = better stability and performance as well as more process control

PROGEN L 100 = cheap enzymatic mixture for the first phase of the system, achieves very good hydrolysis but also fermentation at a low cost

** Exp
Δοκιμάστηκαν οι τάδε συνθήκες σε εργαστηριακή και πιλοτική κλίμακα για να γίνει optimized και scaled up η διεργασία και έπειτα μετρήθηκε το μεθάνιο

** Αποτελέσματα
Προέκυψε πως το 1 ml είναι καλύτερο για υδρόλυση, το 2 για ζύμωση, στη χώνευση βλέπουμε trade off μεταξύ τους και ανάλογα τι είναι σημαντικότερο επιλέγεται σε κάθε περίπτωση. Το παραγώμενο υπόστρωμα είναι πολύ καλύτερο για ad από fw και αυτό έγινε validated και στη πιλοτική κλίμακα, δείχνοντας ένα feasible scale up της διεργασίας. + μπλα μπλα

** Προτάσεις
Δοκιμή πειραμάτων σε διαφορετικές τιμές pH, καθώς με βάση την βιβλιογραφία είναι πολύ σημαντικό

Πιο άμεσος έλεγχος του αερισμού ή πειράματα σε πλήρως αναερόβιο περιβάλλον για να βρεθούν οι διαφορές

Δοκιμή άλλων θερμοκρασιών (όχι τόσο relevant, μάλλον προς το τέλος)

Χρήση των VFAs ως platform για παραγωγή προϊόντων και όχι ενέργειας επειδή η ενέργεια είναι πιο "solved"

* Συμπεράσματα και Προτάσεις
\label{sec:conclusion}

Τα \acrfull{fw} αποτελούν ένα πολύ σοβαρό πρόβλημα της σημερινής κοινωνίας και η διαχείριση τους είναι πολύ σημαντική, λόγω του υψηλού οργανικού φορτίου που έχουν. Η διαχείριση τους με συμβατικές μεθόδους όπως η διάθεση τους σε \acrshort{xyta} δεν θεωρείται βιώσιμη καθώς δεν εκμεταλλεύεται το φορτίο αυτό, και μάλιστα οδηγεί και σε ανεξέλεγκτες εκπομπές μεθανίου. Για τον λόγο αυτόν, είναι επιτακτική η ανάγκη ανάπτυξης τεχνολογιών διαχείρισης \acrshort{fw}, η οποίες να είναι εύκολες στην εφαρμογή και την κλιμάκωση. Στην εργασία αυτή επιλέχθηκε η \acrfull{ad}, λόγω του υψηλού \acrshort{trl} της και της παραγωγής ενός πολύ χρησιμού ενεργειακού φορέα, του μεθανίου, το οποίο παράγεται ελεγχόμενα και μπορεί να αποθηκευτεί. Μέσω μίας βιβλιογραφικής ανασκόπησης, βρέθηκαν τα προβλήματα της διεργασίας αυτής, όπως η μειωμένη απόδοση υδρόλυσης κατά την χώνευση και η αστάθεια της όταν λειτουργεί σε μεγάλο ρυθμό φόρτισης. Η διεξαγωγή της \acrshort{ad} σε 2 στάδια λύνει τα προβλήματα αυτά.

Επιλέχθηκε η χρήση ενός εμπορικού σκευάσματος ενζύμων και μικροοργανισμών (μιξ) χαμηλής τιμής (PROGEN L 100) για το πρώτο στάδιο, καθώς επιτρέπει την αποτελεσματική ενζυμική υδρόλυση του υποστρώματος, σε ένα χαμηλό σχετικά κόστος, ενώ ταυτόχρονα μπορεί να γίνει και η οξεογενή ζύμωση. Η διεργασία αυτή βελτιστοποιήθηκε σε εργαστηριακή κλίμακα με αντιδραστήρες 1 L, ενώ οι καλύτερες συνθήκες εξετάστηκαν και σε πιλοτικό αντιδραστήρα όγκου 300 L για να εξεταστεί η εφικτότητα της κλιμάκωσης της διεργασίας αυτής. Διαπιστώθηκε πως η βέλτιστη διάρκεια των πειράματων ήταν 72 ώρες, ενώ η διεργασία ήταν πιο αποτελεσματική στους 40 \( ^oC \), καθώς στους 35 \( ^oC \) παραγόταν πολύ αιθανόλη εις βάρος του οξικού οξέος, το οποίο είναι το θεωρητικά ιδανικό υπόστρωμα για την διεργασία. Ως προς την ποσότητα του μιξ που προστέθηκε σε κάθε πείραμα, βρέθηκε πως η προσθήκη 10 mL μιξ/kg \acrshort{fw} είχε την καλύτερη απόδοση παραγωγής οξεογενών προϊόντων όπως το οξικό και το γαλακτικό οξύ μετά από μία ανάλυση ευαισθησίας. Όμως, αν προστεθούν μόνο 5 mL μιξ/kg \acrshort{fw}, η υδρόλυση/βιοαποδόμηση είναι πιο αποτελεσματική. Συγκεκριμένα, βρέθηκε πως ο λόγος sCOD/tCOD ήταν \( 46.08 \pm 12.17 \), ενώ στην περίπτωση των 10 mL μιξ/kg \acrshort{fw} ήταν \( 32.72 \pm 10.30 \) τιμή η οποία είναι χαμηλότερη με στατιστική βεβαιότητα (p-Value = 0.0002). Αυτό συμβαίνει επειδή στην περίπτωση των 10 mL/kg \acrshort{fw}, υπάρχουν περισσότεροι μικροοργανισμοί και καταναλώνεται κάποιο από το παραγόμενο \acrshort{cod}, ενώ η ποσότητα ενζύμων που απαιτείται για την αποτελεσματική υδρόλυση/βιοαποδόμηση μπορεί να επιτευχθεί ακόμη και στα 5 mL μιξ/kg \acrshort{fw}.

Το δεύτερο στάδιο της \acrshort{ad}, το οποίο περιέχει την μεθανογένεση έγινε μόνο σε εργαστηριακή κλίμακα σε αντιδραστήρες 0.5 L. Τα συμπεράσματα της υδρόλυσης/βιοαποδόμησης επαληθεύτηκαν κατά το στάδιο αυτό, καθώς τα υδρολύματα με 5 mL μιξ/kg \acrshort{fw} είχαν την μεγαλύτερη παραγωγή μεθανίου, όμως αυτά με 10 mL μιξ/kg \acrshort{fw} είχαν υψηλότερους ρυθμούς και μικρότερο χρόνο καθυστέρησης, επειδή είχαν πιο αποτελεσματική ζύμωση, και το υπόστρωμα ήταν πιο εύκολο στην μεθανογένεση. Τα αποτελέσματα αυτά επαληθεύτηκαν με λάσπη από 3 διαφορετικές πηγές και χρησιμοποιώντας υδρολύματα από πειράματα εργαστηριακής αλλά και πιλοτικής κλίμακας. Ακόμη, η παραγωγή αυτή συγκρίθηκε με αυτήν των ανεπεξέργαστων \acrshort{fw}, όπου παρατηρήθηκε αστάθεια της διεργασίας και οξίνιση σε κάποιες περιπτώσεις, αλλά και ακόμη όταν δεν έγινε αυτό, η παραγωγή ήταν περίπου 4-5 φορές μικρότερη από την μέγιστη παραγωγή μεθανίου μετά το στάδιο υδρόλυσης που χρησιμοποιήθηκε.

Έτσι, διαπιστώθηκε πως η διεργασία υδρόλυσης/βιοαποδόμησης με το εμπορικό σκεύασμα PROGEN L 100 είναι μία πολύ αποτελεσματική διεργασία για την βελτίωση της απόδοσης και της σταθερότητας της \acrshort{ad} σε εργαστηριακή αλλά και σε πιλοτική κλίμακα, ενώ είναι μία προεπεξεργασία χαμηλού κόστους. Η βέλτιστη δοσολογία του σκευάσματος για γρήγορη \acrshort{ad} είναι 10 mL μιξ/kg \acrshort{fw}, ενώ για μεγιστοποίηση της παραγωγής μεθανίου - αλλά λίγο πιο αργό ρυθμό - προτείνεται η δοσολογία 5 mL μιξ/kg \acrshort{fw}.

Παρόλη την πρόοδο που υπήρξε στα πλαίσια της εργασίας αυτής, η προτεινόμενη διεργασία έχει ακόμη κάποια ερευνητικά κενά τα οποία προτείνεται να καλυφθούν σε επόμενες ερευνητικές εργασίες. Ένα από τα σημαντικότερα αντικείμενα προς μελέτη είναι η επίδραση του pH στην διεργασία υδρόλυσης/βιοαποδόμησης. Με βάση την βιβλιογραφία, το pH είναι από τους σημαντικότερους παράγοντες που επηρεάζουν την διεργασία και η εύρεση μίας βέλτιστης τιμής αυτού μπορεί να συνεισφέρει σημαντικά στην απόδοση της. Στην παρούσα μελέτη επιλέχθηκε η διεξαγωγή των πειραμάτων χωρίς μεταβολή του pH, για να μην αυξηθεί περαιτέρω η πολυπλοκότητα της, αλλά αυτό είναι σίγουρα ένα αντικείμενο προς συζήτηση. Ως προς άλλες λειτουργικές συνθήκες, θα ήταν ενδιαφέρουσα η εξέταση ψυχρόφιλων ή θερμόφιλων θερμοκρασιών πέρα από την μεσοφιλή περιοχή που εξετάστηκε στην εργασία αυτή, καθώς η θερμοκρασία παίζει βασικό ρόλο στις μικροβιακές δράσεις (παρόλο που αναμένεται πως η μεσόφιλη περιοχή είναι ιδανική) αλλά και η μελέτη της διεργασίας σε πιο ελεγχόμενες συνθήκες αερισμού ή σε πλήρως αναερόβιες συνθήκες για να παρατηρηθεί αν όντως ο μικροαερισμός που επιβλήθηκε βοήθησε την διεργασία και αν υπάρχει περιθώριο για περαιτέρω βελτίωση από αυτό. Ως προς το δεύτερο στάδιο της διεργασίας, υπάρχει αρκετό ενδιαφέρον στο να γίνει μία αναλυτική μελέτη της αναερόβιας χώνευσης των υδρολυμάτων αυτών σε πιλοτική μονάδα συνεχούς λειτουργίας καθώς εξετάστηκε η κλιμάκωση της υδρόλυσης/βιοαποδόμησης, αλλά όχι της αναερόβιας χώνευσης. Θεωρείται πως τα συμπεράσματα θα είναι αντίστοιχα, αλλά θα είχε ενδιαφέρον να γίνει για την ολοκλήρωση της διεργασίας σε πιλοτική κλίμακα. 

Τέλος, ένα αντικείμενο αρκετού ερευνητικού ενδιαφέροντος γύρω από την διεργασία αυτή είναι η χρήση του παραγόμενου υδρολύματος, το οποίο είναι πλούσιο σε \acrfull{vfa} ως πλατφόρμα για παραγωγή βιο-προϊόντων στη λογική ενός βιοδιυλιστηρίου. Η ενέργεια είναι ένα πολύ σημαντικό ζήτημα και η μετάβαση σε πιο πράσινες πηγές ενέργειας όπως το βιοαέριο είναι αρκετά σημαντική. Όμως, ακόμη μεγαλύτερο πρόβλημα στην πράσινη μετάβαση αποτελούν τα προϊόντα τα οποία παράγονται από το πετρέλαιο. Το υδρόλυμα αυτό αποτελεί ένα φθηνό υπόστρωμα, το οποίο έχει παραχθεί με πράσινο τρόπο από ένα απόβλητο. Περιέχει χρήσιμες ενώσεις (οξικό οξύ, προπιονικό οξύ, γαλακτικό οξύ και αιθανόλη, ενώ με αλλαγή των λειτουργικών συνθηκών θεωρείται πως θα μπορέσουν να παραχθούν και άλλες) οι οποίες μπορούν να ανακτηθούν ως έχουν, καθώς όλα τα προϊόντα αυτά παράγονται συμβατικά από το πετρέλαιο και έχουν μία σημαντική αγορά είτε για άμεση χρήση ή ως χημικά ενδιάμεσα για την παραγωγή άλλων ενώσεων. Εναλλακτικά, μπορούν να χρησιμοποιηθούν χωρίς διαχωρισμό για παραγωγή προϊόντων όπως τα \acrfull{mcfa} ή ακόμη και για την παραγωγή βιοπλαστικών όπως οι \acrfull{pha}, κάτι που θα είχε ιδιαίτερο ενδιαφέρον για την αντικατάσταση των πετρελαϊκών πρώτων υλών.
