#+TITLE: Πειραματική Διαδικασία - Αρχικό Manuscript

* Μεθοδολογία
** Συλλογή και προεπεξεργασία υποστρώματος
Τα υπολείμματα τροφών (FW) που χρησιμοποιήθηκαν για τα πειράματα εργαστηριακής κλίμακας συλλέχθηκαν από το εστιατόριο του Εθνικού Μετσόβιου Πολυτεχνείου. Αρχικά, αντικείμενα όπως κόκκαλα, χαρτί και άλλα αφαιρέθηκαν από τα υπολείμματα. Έπειτα, τα τρόφιμα τεμαχίστηκαν σε μπλέντερ (Cecotec Powder Black Titanium 2000) για να δημιουργηθεί μία ομοιόμορφη ημιστερεή φάση η οποία μπορεί να χρησιμοποιηθεί ως υπόστρωμα για την υδρόλυση. Το υλικό αυτό αποθηκεύτηκε σε κατάψυξη στους - 20 \( ^oC \) για περαίτερω χρήση.

Για τα πειράματα πιλοτικής κλίμακας, γινόταν καθημερινή συλλογή υπολειμμάτων από το εστιατόριο για να τροφοδοτηθεί ο αντιδραστήρας, αλλά δεν χρειαζόταν κάποιος τεμαχισμός επειδή ο ίδιος ο αντιδραστήρας είχε την δυνατότητα αυτή.

** Εμβόλιο
Για την βιοαποδόμηση της οργανικής ύλης χρησιμοποιήθηκε εμπορικό σκεύασμα ενζύμων και μικροοργανισμών (Ένζυμα PROGEN https://www.progen-enzymes.com/) το οποίο έχει ως σκοπό την αποτελεσματική υδρόλυση του υποστρώματος αλλά και την οξεογενή ζύμωση της οργανικής ύλης.

Για την αναερόβια χώνευση χρησιμοποιήθηκε λάσπη από 2 διαφορετικές πηγές (++ αλλά εγώ δεν ξέρω άλλες πληροφορίες).

** Βιοαποδόμηση υπολειμμάτων τροφών - Εργαστηριακή Κλίμακα
Τα πειράματα βιοαποδόμησης σε εργαστηριακή κλίμακα ήταν διαλείποντος έργου και έγιναν σε όργανο το οποίο έχει 7 διαθέσιμα δοχεία συνολικού όγκου 1000 ml εξοπλισμένα με αναδευτήρες και με δυνατότητα ρύθμισης της θερμοκρασίας. Το σύστημα αυτό προσφέρει την δυνατότητα να δοκιμαστούν αρκετές συνθήκες σε κάθε πείραμα, με βασικό περιορισμό ότι η ρύθμιση της θερμοκρασίας είναι κεντρική και όλα τα δοχεία λειτουργούν στην ίδια θερμοκρασία.

(λογικά μία φωτογραφία)

Ο βασικός πειραματικός σχεδιασμός που έγινε για την βελτιστοποίηση της διεργασίας χρησιμοποιήσε 2 θερμοκρασίες της μεσόφιλης περιοχής, τους 35 \( ^oC \) και τους 40 \( ^oC \). Σε κάθε δοχείο τροφοδοτήθηκαν 200 g τεμαχισμένων υπολειμμάτων τροφών και αυτά αραιώθηκαν με 600 ml νερό. Η αραίωση αυτή επιλέχθηκε μετά από κάποια προπαρασκευαστικά πειράματα ως μία τιμή στην οποία πετυχαίνεται καλή ομοιογένια του υποστρώματος και τα στερεά δεν δημιουργούν κάποιο πρόβλημα. Κάθε δοχείο είχε προσθήκη διαφορετικής ποσότητας του σκευάσματος ενζύμων και μικροοργανισμών (μιξ) με τις τιμές που εξετάστηκαν να είναι 0 ml (επίδραση μόνο της θερμοκρασίας), 1 ml, 2 ml, 4 ml και 8 ml. Οπότε δημιουργήθηκαν αναλογίες υποστρώματος:εμβολίου 200, 100, 50 και 25 g υγρού FW ανά ml μιξ. Η ανάδευση ρυθμίστηκε στα 120 rpm για κάθε πείραμα.

** Βιοαποδόμηση υπολειμμάτων τροφών - Πιλοτική Κλιμάκα
Για τα πειράματα σε πιλοτική κλίμακα χρησιμοποιήθηκε ο αερόβιος χωνευτήρας ORCA (https://www.feedtheorca.com/). Η λειτουργία του αντιδραστήρα ήταν ημι-συνεχής καθώς η τροφοδοσία γινόταν 2 φορές την ημέρα (μία το πρωί και μία το απόγευμα) με ποσότητα περίπου στα 30-40 kg υγρού FW/ημέρα. Η εκροή του αντιδραστήρα συλλεγόταν σε δεξαμενή συνολικής χωρητικότητας 250 L μετά από λιποσυλλογή.

Ο αντιδραστήρας έχει πληρωτικό υλικό, το οποίο επιτρέπει την πιο αποτελεσματική διεξαγωγή της αντίδρασης. Επίσης, έχει εσωτερική ζυγαριά για την μέτρηση της μάζας της τροφοδοσίας του και ροόμετρο για την μέτρηση της παροχής στην εκροή. Τέλος, έχει ένα PLC το οποίο επιτρέπει την ρύθμιση του ρυθμού τροφοδοσίας του ενζυμικού σκευάσματος καθώς και τη ρύθμιση του νερού που προστίθεται είτε στο εσωτερικό του αντιδραστήρα ή στην εκροή (για να γίνει καλύτερη αραίωση του συστήματος).

Στα πειράματα που έγιναν εξετάστηκε η επίδραση όλων αυτών των παραμέτρων.

** Αναερόβια Χώνευση
Η αναερόβια χώνευση έγινε σε εργαστηριακή κλίμακα χρησιμοποιώντας μία batch διάταξη μέτρησης του μεθανίου που μπορεί να παράξει το υδρόλυμα. Χρησιμοποιήθηκαν δοχεία συνολικού όγκου 500 ml τα οποία τοποθετήθηκαν σε θερμόλουτρο ρυθμισμένο στους 37 \( ^oC \) με ανάδευση 170 rpm. Τα δοχεία σφραγίστηκαν με σιλικόνη για να μην υπάρξουν διαρροές. Το παραγώμενο αέριο αρχικά διοχετεύεται σε διάλυμα καυστικού νατρίου για δέσμευση του διοξειδίου του άνθρακα ενώ το μεθάνιο περνάει σε μία προχοίδα όπου με μέτρηση της μετατόπισης του υγρού υπολογίζεται η παραγωγή αερίου. Η μετατόπιση αυτή καταγράφεται με χρήση κάμερας που υπάρχει στην διάταξη.

Αρχικά, η αναερόβια λάσπη ενεργοποιήθηκε με τροφοδοσία με οξικό οξύ και έπειτα έγινε τροφοδοσία με τα παραγώμενα υδρολύματα. Εκτός από τα υδρολύματα, έγινε και μία τροφοδοσία με ανεπεξέργαστο FW για να παρατηρηθεί αν η διεργασία βιοαποδόμησης βοήθησε στην πιο αποτελεσματική χώνευση. Σε όλα τα πειράματα που έγιναν, η τροφοδοσία υποστρώματος ήταν 100 mg COD. Στον κύκλο με την πρώτη λάσπη, τροφοδοτήθηκαν 1.55 g VS λάσπης, οδηγώντας σε μία αναλογία υποστρώματος:εμβολίου 0.06 ενώ στον δεύτερο τροφοδοτήθηκαν 4.2 g VS λάσπης και άρα μία αναλογία 0.02. Η αναλογίες αυτές είναι γενικά χαμηλές, με σκοπό να υπάρχει μία γρήγορη απόκριση στην τροφοδοσία και να μην παραχθεί πολύ μεγάλη ποσότητα αερίου, καθώς οι προχοίδες που χρησιμοποιούνται έχουν χωρητικότητα 50 ml.

Καθώς η καταγραφή του όγκου ήταν 24ωρη, έγινε και κινητική ανάλυση της παραγωγής μεθανίου, με χρήση του τροποποιημένου μοντέλου Gompertz [cite:@zwieteringModelingBacterialGrowth1990] το οποίο έχει χρησιμοποιηθεί εκτενώς στη βιβλιογραφία για την ανάλυση αυτή [cite:@uckunkiranEnhancingHydrolysisMethane2015; @fengEffectPrefermentationTypes2020; @hobbsEnhancingAnaerobicDigestion2018].

\begin{equation}
\tag{1}
P(t) = P_{\max } \exp \left( - \exp \left[ \frac{R_{\max }e (λ-t)}{P_{\max }} + 1 \right] \right)
\label{eqn:1}
\end{equation}

Το μοντέλο αυτό έχει τρείς παραμέτρους. Τη μέγιστη δυνατή παραγωγή μεθανίου \( P_{\max } \), τον μέγιστο ειδικό ρυθμό παραγωγής μεθανίου \( R_{\max } \) και τον χρόνο καθυστέρησης \( λ \). 

** Αναλύσεις
Για τα πειράματα βιοαποδόμησης σε εργαστηριακή κλίμακα έγιναν μετρήσεις pH, sCOD και HPLC. Για τα πειράματα πιλοτικής κλίμακας, έγιναν μετρήσεις TS, VS, sCOD και tCOD. Για την αναερόβια χώνευση έγιναν μετρήσεις TS, VS, pH και αλκαλικότητας της λάσπης, sCOD, TS και VS του κάθε υποστρώματος και pH του τελικού υγρού μετά την χώνευση.

Η μέτρηση pH έγινε με pH probe (μοντέλο αν το ξέρουμε). Τα TS μετρήθηκαν μετά από μία ημέρα σε φούρνο στους 70 \( ^oC \) ενώ τα VS μετρήθηκαν μετά από 2 ώρες σε φούρνο στους 550 \( ^oC \). Για το COD, έγινε φασματοσκοπική ανάλυση. 2 ml του κάθε δείγματος αναμείχθηκαν με 2.8 ml θειικό οξύ και 1.2 ml διχρωμικό και αφέθηκαν για 2 ώρες στους 150 \( ^oC \). Έπειτα, με βάση την απορρόφηση του δείγματος στα 600 nm, υπολογιζόταν το COD. Για το διαλυτό COD, έγινε διήθηση με φίλτρο Whatman. Για την αλκαλικότητα έγινε ογκομέτρηση 20 ml δείγματος με θειικό οξύ κανονικότητας 0.2 N και η αλκαλικότητα υπολογίστηκε από τον όγκο του καταναλισκόμενου θειικού οξέος ως

\begin{equation}
\tag{2}
\frac{50 \cdot V_{H_2SO_4} \cdot 1000 \cdot 0.2}{20}
\label{eqn:2}
\end{equation}

Τέλος, η HPLC που έγινε είχε ως σκοπό την μέτρηση των διαλυτών σακχάρων, οξέων και αιθανόλης που υπήρχαν στα δείγματα. Ο χρόνος παραμονής στην στήλη ήταν 45 λεπτά. Ως κινητή φάση, χρησιμοποιήθηκε υπερκάθαρο νερό (νομίζω). Οι συγκεντρώσεις προσδιορίστηκαν με βάση πρότυπες καμπύλες για κάθε συστατικό από την επιφάνεια κάθε κορυφής στο χρωματογράφημα.
