#+TITLE: Πειραματική Διαδικασία

* COMMENT Επεξήγηση
Το αρχείο αυτό περιγράφει την πειραματική διαδικασία που χρησιμοποιήθηκε για όλα τα πειράματα (κεφάλαιο materials and methods). Παρακάτω υπάρχει το αρχικό και τελικό manuscript του πειραματικού από το paper για το πσχμ από το οποίο σίγουρα θα πάρω κάποια πράγματα, αλλά σε ένα βαθμό θα γίνει rewritten και σίγουρα θα έχει περισσότερες πληροφορίες.

* Υλικά και Μεθόδοι
\label{sec:materials_methods}

** Υπόστρωμα και Εμβόλιο
Τα \acrshort{fw} που χρησιμοποιήθηκαν συλλέχθηκαν από την φοιτητική λέσχη του Εθνικού Μετσόβιου Πολυτεχνείου και αποθηκεύτηκαν στους - 20 \( ^oC \) για περαιτέρω χρήση. Για τα εργαστηριακά πειράματα, όπου χρειάστηκε μικρή ποσότητα υποστρώματος ανά πείραμα, συλλέχθηκαν τρόφιμα μία φορά και τεμαχίστηκαν σε μπλέντερ (Cecotec Powder Black Titanium 2000) για να επιτευχθεί μία ομοιόμορφη ημιστερεή φάση η οποία μπορεί να χρησιμοποιηθεί ως υπόστρωμα για την υδρόλυση. Το υλικό αυτό αναλύθηκε ως προς το pH, την ηλεκτρική αγωγιμότητα, τα στερεά, την πυκνότητα και το \acrfull{cod}. Η σύσταση του φαίνεται στον πίνακα [[tbl:fw_characterism]]. Στην διάταξη της πιλοτικής κλίμακας, ο τεμαχισμός δεν ήταν απαραίτητος καθώς ο αντιδραστήρας είχε την δυνατότητα αυτή. Λόγω των ποσοτήτων που χρειαζόντουσαν, υπήρχε καθημερινή συλλογή \acrshort{fw}, τα χαρακτηριστικά των οποίων δεν αναλύθηκαν.

#+CAPTION: Χαρακτηριστικά Υπολειμμάτων Τροφών
#+NAME: tbl:fw_characterism
| Παράμετροι     | Τιμή              |
|----------------+-------------------|
| pH             | 4.62 \pm 0.02     |
| EC (μS/cm)     | 1817.7 \pm 38.0   |
| TS (%)         | 11.54 \pm 2.18    |
| VS (%)         | 10.93 \pm 2.07    |
| VS/TS (%)      | 94.70 \pm 4.46    |
| Density (g/mL) | 1.0316 \pm 0.0078 |
| sCOD (mg/L)    | 20009 \pm 1980    |
| TCOD (mg/L)    | 96031 \pm 2204    |
| sCOD/tCOD(%)   | 20.82 \pm 1.58    |

Το \acrfull{mix} που χρησιμοποιήθηκε είναι το εμπορικό σκεύασμα PROGEN της εταιρείας HiTech. Αυτό το σκεύασμα είναι ιδανικό για την αποτελεσματική υδρόλυση των \acrshort{fw} αλλά και την ταυτόχρονη ζύμωση της παραγώμενης οργανικής ύλης σε \acrshort{vfa}.

Για την \acrshort{ad} χρησιμοποιήθηκε αναερόβια λάσπη προερχόμενη από τρείς διαφορετικές πηγές. Η πρώτη (Λάσπη 1) από τo \acrfull{kel} των βορείων προαστίων της Αττικής, η δεύτερη (Λάσπη 2) από μονάδα ανακύκλωσης απορριμάτων στην Βοιωτία και η τρίτη (Λάσπη 3) από αναερόβιο χωνευτήρα εγκατεστημένο σε βιομηχανία τροφίμων στην Αττική. Οι λάσπες αυτές αναλύθηκαν ως προς τα στερεά, το pH και την αλκαλικότητα. Τα αποτελέσματα των αναλύσεων αυτών φαίνονται στον πίνακα [[tbl:sludge_characterism]]. 

#+CAPTION: Χαρακτηριστικά Λάσπης
#+NAME: tbl:sludge_characterism
| Παράμετροι          | Λάσπη 1          | Λάσπη 2          | Λάσπη 3         |
|---------------------+------------------+------------------+-----------------|
| TS (g/kg)           | 46.277 \pm 0.033 | 25.546 \pm 0.238 | 4.315 \pm 0.151 |
| VS (g/kg)           | 12.364 \pm 0.322 | 16.148 \pm 0.704 | 2.001 \pm 0.072 |
| VS/TS (%)           | 26.72 \pm 0.72   | 63.23 \pm 3.34   | 46.38 \pm 0.05  |
| pH                  | 8.33 \pm 0.01    | 8.90 \pm 0.07    | 7.50 \pm 0.03   |
| Αλκαλικότητα (mg/L) | 12250            | 14200            | 1100            |

** Δοκιμαστικά πειράματα υδρόλυσης

** Πειραματικός κύκλος υδρόλυσης

** Υδρόλυση σε πιλοτική κλίμακα

** Πειραματικός κύκλος αναερόβιας χώνευσης

** Αναλυτικές Μέθοδοι
Η μέτρηση pH έγινε με χρήση pH μέτρου (inoLab pH Level 1 pH Meter) σε ακολουθία με τις πρότυπες τεχνικές, ενότητα 4500-H^+ [cite:@aphaStandardMethodsExamination2005]. Η μέτρηση ηλεκτρικής αγωγιμότητας έγινε με τον ηλεκτροχημικό αναλυτή CONSORT C933.

Η μέτρηση των στερεών, έγινε σε ακολουθία με τις πρότυπες τεχνικές, ενότητα 2540 [cite:@aphaStandardMethodsExamination2005] . Συγκεκριμένα για τα \acrfull{ts}, έγινε ζύγιση σε προζυγισμένη κάψα μετά από ξήρανση σε φούρνο στους 75 \( ^oC \) για 1 μέρα, ενώ για να μετρηθούν τα \acrfull{vs}, έγινε ζύγιση μετά από ξήρανση σε φούρνο στους 550 \( ^oC \) για 2 ώρες. Για τα \acrfull{ss}, έγινε αρχικά διήθηση του δείγματος με χρήση προζυγισμένου φίλτρου Whatman GF/A το οποίο κατακρατάει στερεά διαμέτρου 1.6 μm και πάνω. Έπειτα, ακολουθήθηκε η ίδια διαδικασία με παραπάνω για την μέτρηση ολικών και πτητικών αιρούμενων στερεών.

Η μέτρηση του \acrshort{cod} έγινε σε ακολουθία με τις πρότυπες τεχνικές, ενότητα 5220 [cite:@aphaStandardMethodsExamination2005]. Για την μέτρηση αυτή, αρχικά γίνεται αραίωση του δείγματος ανάλογα με το αναμενόμενο \acrshort{cod}, καθώς η μέθοδος είναι αξιοπιστή σε COD από 50 εώς 1000 mg/L. Έπειτα, 2 ml του αραιωμένου δείγματος αναμιγνύονται με 2.8 ml πυκνού θειϊκού οξέος και 1.2 ml διχρωμικού καλίου και τοποθετούνται σε ειδικό φούρνο στους 150 \( ^oC \) για 2 ώρες (HACH COD Reactor 45600). Το διχρωμικό κάλιο είναι ισχυρό οξειδωτικό, ενώ το θειϊκό οξύ και η θερμοκρασία δρουν ως καταλύτες της αντίδρασης. Ανάλογα με το \acrshort{cod}, μεταβάλλεται η οξειδωτική κατάσταση του χρωμίου από +6 σε +3. Ταυτόχρονα, μεταβάλλεται το χρώμα του από πορτοκαλί σε γαλάζιο. Μετρώντας την απορρόφηση στα 600 nm μετά τις 2 ώρες, μπορεί να ποσοτικοποιηθεί η οξείδωση που διεξάχθηκε. Για να μετρηθεί το \acrshort{cod} ενός δείγματος, απαιτείται μία πρότυπη καμπύλη η οποία αντιστοιχεί την απορρόφηση αυτήν σε συγκέντρωση \acrshort{cod}.

* COMMENT Initial Manuscripts
** Τελικό version paper
Τα FW που χρησιμοποιήθηκαν συλλέχθηκαν από την φοιτητική λέσχη του Εθνικού Μετσόβιου Πολυτεχνείου και αποθηκεύτηκαν στους -20oC για περαιτέρω χρήση. Για τα εργαστηριακά πειράματα, τα τρόφιμα τεμαχίστηκαν σε μπλέντερ (Cecotec Powder Black Titanium 2000) για να επιτευχθεί μία ομοιόμορφη ημιστερεή φάση η οποία μπορεί να χρησιμοποιηθεί ως υπόστρωμα για την υδρόλυση. Στην διάταξη της πιλοτικής κλίμακας αυτό δεν ήταν απαραίτητο καθώς υπάρχει η δυνατότητα τεμαχισμού. Για την βιοαποδόμηση της οργανικής ύλης χρησιμοποιήθηκε το εμπορικό σκεύασμα ενζύμων και μικροοργανισμών PROGEN το οποίο έχει ως σκοπό την αποτελεσματική υδρόλυση του υποστρώματος αλλά και την ζύμωση της οργανικής ύλης σε VFAs. Για την ΑΧ χρησιμοποιήθηκε αναερόβια λάσπη προερχόμενη από δύο διαφορετικές πηγές: α μονάδα ανακύκλωσης απορριμμάτων Βοιωτίας και β αναερόβιο χωνευτήρα βιομηχανίας τροφίμων Αττικής. 
Τα πειράματα βιοαποδόμησης σε εργαστηριακή κλίμακα ήταν διαλείποντος έργου και έγιναν σε διάταξη με 7 διαθέσιμα δοχεία συνολικού όγκου 1L το καθένα εξοπλισμένα με αναδευτήρες και με δυνατότητα ρύθμισης της θερμοκρασίας. Οι θερμοκρασίες που εξετάστηκαν κατά τη βιοαποδόμηση ήταν 35 και 40oC. Σε κάθε δοχείο τροφοδοτήθηκαν 200 g τεμαχισμένων FW και αυτά αραιώθηκαν με 600 mL νερό για την καλύτερη ομογενοποίησή τους. Οι ποσότητες του σκευάσματος ενζύμων-μικροοργανισμών (mix) που εξετάστηκαν είναι 0 (επίδραση μόνο της θερμοκρασίας), 1, 2, 4 και 8 mL με αντίστοιχες αναλογίες υποστρώματος/εμβολίου 200, 100, 50 και 25 g υγρού FW/mL mix. Η ανάδευση ρυθμίστηκε στα 120 rpm για κάθε πείραμα και η διάρκεια του κάθε πειράματος ήταν 72 ώρες. Η απόδοση της βιοαποδόμησης εκτιμάται από την παραγωγή VFAs στο τέλος της διεργασίας.
Για τα πειράματα σε πιλοτική κλίμακα χρησιμοποιήθηκε ο πρωτότυπος αερόβιος χωνευτήρας (MyECO) χωρητικότητας 300 L. Στο εσωτερικό του αντιδραστήρα έχει τοποθετηθεί αδρανές πλαστικό πληρωτικό υλικό, για την καλύτερη διεπαφή FW και ενζύμων-μικροοργανισμών. Επίσης, διαθέτει εσωτερική ζυγαριά για την μέτρηση της μάζας της τροφοδοσίας του και ροόμετρο για την μέτρηση της παροχής νερού. Τέλος, έχει ενσωματωμένο PLC που επιτρέπει την ρύθμιση του ρυθμού τροφοδοσίας του σκευάσματος καθώς και του νερού που προστίθεται στο εσωτερικό του αντιδραστήρα αλλά και στην εκροή του για την αραίωση του τελικού προϊόντος. ΑΝΑΔΕΥΣΗ. Στα πειράματα που έγιναν εξετάστηκε η επίδραση του ρυθμού τροφοδοσίας του σκευάσματος (mL σκευάσματος/kg ξηρού FW/day) καθώς και της παροχής νερού στην υδρόλυση του FW. Η λειτουργία του αντιδραστήρα ήταν ημι-συνεχής και η τροφοδοσία γινόταν 2 φορές την ημέρα με ποσότητες 25-36 kg υγρού FW/ημέρα, ενώ το κάθε πείραμα είχε διάρκεια 5 ημέρες. Η εκροή του αντιδραστήρα συλλεγόταν σε δεξαμενή συνολικής χωρητικότητας 250 L μετά από λιποσυλλογή. Για τα πειράματα πιλοτικής κλίμακας, η βασική απόκριση του πειράματος ήταν ο λόγος διαλυτού προς ολικό COD ο οποίος δείχνει την βιοαποδομησιμότητα του υποστρώματος και κατά συνέπεια την απόδοση της υδρόλυσής του. 
Η ΑΧ πραγματοποιήθηκε σε εργαστηριακούς αντιδραστήρες διαλείποντος έργου, συνολικού όγκου 500 Ml ο καθένας. Οι αντιδραστήρες εμβολιάστηκαν αρχικά με 120 g αναερόβιας λάσπης, και στη συνέχεια πληρώθηκαν με 350 mL νερού και τοποθετήθηκαν σε υδατόλουτρο θερμοκρασίας 37oC και ανάδευσης 170 rpm. Αρχικά, η αναερόβια λάσπη ενεργοποιήθηκε με τροφοδοσία οξικού οξέος 100 mg, και στη συνέχεια, ακολούθησε η τροφοδοσία με τα υδρολύματα που προέκυψαν από τη υδρόλυση/βιοαποδόμηση των FW με 0, 1, 2 και 4 mL mix/200 g FW στους 40oC, αλλά και με ανεπεξέργαστο FW. Το παραγόμενο βιοαέριο αρχικά διοχετεύεται σε διάλυμα NaOH 1Μ όπου δεσμεύεται το διοξείδιο του άνθρακα ενώ το μεθάνιο συλλέγεται και μετριέται με την τεχνική της μετατόπισης του υγρού. Η παραγωγή μεθανίου στο χρόνο καταγράφεται με σύστημα παρακολούθησης με χρήση κάμερας. Πραγματοποιήθηκαν 2 κύκλοι πειραμάτων ΑΧ με λάσπη δυο διαφορετικών προελεύσεων. Κατά τον πρώτο κύκλο πειραμάτων (λάσπη Βοιωτίας) χρησιμοποιήθηκαν 1,55 g VS λάσπης/αντιδραστήρα, ενώ στον δεύτερο (λάσπη Αττικής) τροφοδοτήθηκαν 4,20 g VS λάσπης/αντιδραστήρα. Τέλος ακολούθησε η αναερόβια επεξεργασία του υδρολύματος που προέκυψε από τον πιλοτικό αντιδραστήρα με χρήση σκευάσματος ενζύμων-μικροοργανισμών που αντιστοιχούσε σε 1 και 2 mL mix/200 g FW, με χρήση λάσπης Αττικής. Σε όλα τα πειράματα η τροφοδοσία υποστρώματος ήταν 100 mg sCOD, ενώ το κάθε πείραμα σταματούσε με την ελαχιστοποίηση του ρυθμού παραγωγής μεθανίου.
Καθώς η καταγραφή του όγκου ήταν 24ωρη, υπήρξε δυνατότητα κινητικής ανάλυσης της παραγωγής μεθανίου με χρήση του τροποποιημένου μοντέλου Gompertz[6] το οποίο χρησιμοποιείται εκτενώς για τον προσδιορισμό του ρυθμού παραγωγής CH4 [4,7].
                                                                                         (1)
Όπου P(t) η παραγωγή μεθανίου σε χρόνο t,  η μέγιστη δυνατή παραγωγή μεθανίου,  ο μέγιστος ρυθμός παραγωγής μεθανίου και λ ο χρόνος υστέρησης.
Οι χημικές αναλύσεις πραγματοποιήθηκαν σε ακολουθία με τις Standard Methods: ολικά στερεά ενότητα 2540 Β., πτητικά στερεά, ενότητα 2540 E., pH, ενότητα 4500-H+, χημικά απαιτούμενο οξυγόνο, ενότητα 5220 C. Τα VFAs αναλύθηκαν με HPLC (Agilent Technologies 1260 Infinity II).

** Αρχικό version paper
*** Συλλογή και προεπεξεργασία υποστρώματος
Τα υπολείμματα τροφών (FW) που χρησιμοποιήθηκαν για τα πειράματα εργαστηριακής κλίμακας συλλέχθηκαν από το εστιατόριο του Εθνικού Μετσόβιου Πολυτεχνείου. Αρχικά, αντικείμενα όπως κόκκαλα, χαρτί και άλλα αφαιρέθηκαν από τα υπολείμματα. Έπειτα, τα τρόφιμα τεμαχίστηκαν σε μπλέντερ (Cecotec Powder Black Titanium 2000) για να δημιουργηθεί μία ομοιόμορφη ημιστερεή φάση η οποία μπορεί να χρησιμοποιηθεί ως υπόστρωμα για την υδρόλυση. Το υλικό αυτό αποθηκεύτηκε σε κατάψυξη στους - 20 \( ^oC \) για περαίτερω χρήση.

Για τα πειράματα πιλοτικής κλίμακας, γινόταν καθημερινή συλλογή υπολειμμάτων από το εστιατόριο για να τροφοδοτηθεί ο αντιδραστήρας, αλλά δεν χρειαζόταν κάποιος τεμαχισμός επειδή ο ίδιος ο αντιδραστήρας είχε την δυνατότητα αυτή.

*** Εμβόλιο
Για την βιοαποδόμηση της οργανικής ύλης χρησιμοποιήθηκε εμπορικό σκεύασμα ενζύμων και μικροοργανισμών (Ένζυμα PROGEN https://www.progen-enzymes.com/) το οποίο έχει ως σκοπό την αποτελεσματική υδρόλυση του υποστρώματος αλλά και την οξεογενή ζύμωση της οργανικής ύλης.

Για την αναερόβια χώνευση χρησιμοποιήθηκε λάσπη από 2 διαφορετικές πηγές (++ αλλά εγώ δεν ξέρω άλλες πληροφορίες).

*** Βιοαποδόμηση υπολειμμάτων τροφών - Εργαστηριακή Κλίμακα
Τα πειράματα βιοαποδόμησης σε εργαστηριακή κλίμακα ήταν διαλείποντος έργου και έγιναν σε όργανο το οποίο έχει 7 διαθέσιμα δοχεία συνολικού όγκου 1000 ml εξοπλισμένα με αναδευτήρες και με δυνατότητα ρύθμισης της θερμοκρασίας. Το σύστημα αυτό προσφέρει την δυνατότητα να δοκιμαστούν αρκετές συνθήκες σε κάθε πείραμα, με βασικό περιορισμό ότι η ρύθμιση της θερμοκρασίας είναι κεντρική και όλα τα δοχεία λειτουργούν στην ίδια θερμοκρασία.

(λογικά μία φωτογραφία)

Ο βασικός πειραματικός σχεδιασμός που έγινε για την βελτιστοποίηση της διεργασίας χρησιμοποιήσε 2 θερμοκρασίες της μεσόφιλης περιοχής, τους 35 \( ^oC \) και τους 40 \( ^oC \). Σε κάθε δοχείο τροφοδοτήθηκαν 200 g τεμαχισμένων υπολειμμάτων τροφών και αυτά αραιώθηκαν με 600 ml νερό. Η αραίωση αυτή επιλέχθηκε μετά από κάποια προπαρασκευαστικά πειράματα ως μία τιμή στην οποία πετυχαίνεται καλή ομοιογένια του υποστρώματος και τα στερεά δεν δημιουργούν κάποιο πρόβλημα. Κάθε δοχείο είχε προσθήκη διαφορετικής ποσότητας του σκευάσματος ενζύμων και μικροοργανισμών (μιξ) με τις τιμές που εξετάστηκαν να είναι 0 ml (επίδραση μόνο της θερμοκρασίας), 1 ml, 2 ml, 4 ml και 8 ml. Οπότε δημιουργήθηκαν αναλογίες υποστρώματος:εμβολίου 200, 100, 50 και 25 g υγρού FW ανά ml μιξ. Η ανάδευση ρυθμίστηκε στα 120 rpm για κάθε πείραμα.

*** Βιοαποδόμηση υπολειμμάτων τροφών - Πιλοτική Κλιμάκα
Για τα πειράματα σε πιλοτική κλίμακα χρησιμοποιήθηκε ο αερόβιος χωνευτήρας ORCA (https://www.feedtheorca.com/). Η λειτουργία του αντιδραστήρα ήταν ημι-συνεχής καθώς η τροφοδοσία γινόταν 2 φορές την ημέρα (μία το πρωί και μία το απόγευμα) με ποσότητα περίπου στα 30-40 kg υγρού FW/ημέρα. Η εκροή του αντιδραστήρα συλλεγόταν σε δεξαμενή συνολικής χωρητικότητας 250 L μετά από λιποσυλλογή.

Ο αντιδραστήρας έχει πληρωτικό υλικό, το οποίο επιτρέπει την πιο αποτελεσματική διεξαγωγή της αντίδρασης. Επίσης, έχει εσωτερική ζυγαριά για την μέτρηση της μάζας της τροφοδοσίας του και ροόμετρο για την μέτρηση της παροχής στην εκροή. Τέλος, έχει ένα PLC το οποίο επιτρέπει την ρύθμιση του ρυθμού τροφοδοσίας του ενζυμικού σκευάσματος καθώς και τη ρύθμιση του νερού που προστίθεται είτε στο εσωτερικό του αντιδραστήρα ή στην εκροή (για να γίνει καλύτερη αραίωση του συστήματος).

Στα πειράματα που έγιναν εξετάστηκε η επίδραση όλων αυτών των παραμέτρων.

** Αναερόβια Χώνευση
Η αναερόβια χώνευση έγινε σε εργαστηριακή κλίμακα χρησιμοποιώντας μία batch διάταξη μέτρησης του μεθανίου που μπορεί να παράξει το υδρόλυμα. Χρησιμοποιήθηκαν δοχεία συνολικού όγκου 500 ml τα οποία τοποθετήθηκαν σε θερμόλουτρο ρυθμισμένο στους 37 \( ^oC \) με ανάδευση 170 rpm. Τα δοχεία σφραγίστηκαν με σιλικόνη για να μην υπάρξουν διαρροές. Το παραγώμενο αέριο αρχικά διοχετεύεται σε διάλυμα καυστικού νατρίου για δέσμευση του διοξειδίου του άνθρακα ενώ το μεθάνιο περνάει σε μία προχοίδα όπου με μέτρηση της μετατόπισης του υγρού υπολογίζεται η παραγωγή αερίου. Η μετατόπιση αυτή καταγράφεται με χρήση κάμερας που υπάρχει στην διάταξη.

Αρχικά, η αναερόβια λάσπη ενεργοποιήθηκε με τροφοδοσία με οξικό οξύ και έπειτα έγινε τροφοδοσία με τα παραγώμενα υδρολύματα. Εκτός από τα υδρολύματα, έγινε και μία τροφοδοσία με ανεπεξέργαστο FW για να παρατηρηθεί αν η διεργασία βιοαποδόμησης βοήθησε στην πιο αποτελεσματική χώνευση. Σε όλα τα πειράματα που έγιναν, η τροφοδοσία υποστρώματος ήταν 100 mg COD. Στον κύκλο με την πρώτη λάσπη, τροφοδοτήθηκαν 1.55 g VS λάσπης, οδηγώντας σε μία αναλογία υποστρώματος:εμβολίου 0.06 ενώ στον δεύτερο τροφοδοτήθηκαν 4.2 g VS λάσπης και άρα μία αναλογία 0.02. Η αναλογίες αυτές είναι γενικά χαμηλές, με σκοπό να υπάρχει μία γρήγορη απόκριση στην τροφοδοσία και να μην παραχθεί πολύ μεγάλη ποσότητα αερίου, καθώς οι προχοίδες που χρησιμοποιούνται έχουν χωρητικότητα 50 ml.

Καθώς η καταγραφή του όγκου ήταν 24ωρη, έγινε και κινητική ανάλυση της παραγωγής μεθανίου, με χρήση του τροποποιημένου μοντέλου Gompertz [cite:@zwieteringModelingBacterialGrowth1990] το οποίο έχει χρησιμοποιηθεί εκτενώς στη βιβλιογραφία για την ανάλυση αυτή [cite:@uckunkiranEnhancingHydrolysisMethane2015; @fengEffectPrefermentationTypes2020; @hobbsEnhancingAnaerobicDigestion2018].

\begin{equation}
\tag{1}
P(t) = P_{\max } \exp \left( - \exp \left[ \frac{R_{\max }e (λ-t)}{P_{\max }} + 1 \right] \right)
\label{eqn:1}
\end{equation}

Το μοντέλο αυτό έχει τρείς παραμέτρους. Τη μέγιστη δυνατή παραγωγή μεθανίου \( P_{\max } \), τον μέγιστο ειδικό ρυθμό παραγωγής μεθανίου \( R_{\max } \) και τον χρόνο καθυστέρησης \( λ \). 

*** Αναλύσεις
Για τα πειράματα βιοαποδόμησης σε εργαστηριακή κλίμακα έγιναν μετρήσεις pH, sCOD και HPLC. Για τα πειράματα πιλοτικής κλίμακας, έγιναν μετρήσεις TS, VS, sCOD και tCOD. Για την αναερόβια χώνευση έγιναν μετρήσεις TS, VS, pH και αλκαλικότητας της λάσπης, sCOD, TS και VS του κάθε υποστρώματος και pH του τελικού υγρού μετά την χώνευση.

Η μέτρηση pH έγινε με pH probe (μοντέλο αν το ξέρουμε). Τα TS μετρήθηκαν μετά από μία ημέρα σε φούρνο στους 70 \( ^oC \) ενώ τα VS μετρήθηκαν μετά από 2 ώρες σε φούρνο στους 550 \( ^oC \). Για το COD, έγινε φασματοσκοπική ανάλυση. 2 ml του κάθε δείγματος αναμείχθηκαν με 2.8 ml θειικό οξύ και 1.2 ml διχρωμικό και αφέθηκαν για 2 ώρες στους 150 \( ^oC \). Έπειτα, με βάση την απορρόφηση του δείγματος στα 600 nm, υπολογιζόταν το COD. Για το διαλυτό COD, έγινε διήθηση με φίλτρο Whatman. Για την αλκαλικότητα έγινε ογκομέτρηση 20 ml δείγματος με θειικό οξύ κανονικότητας 0.2 N και η αλκαλικότητα υπολογίστηκε από τον όγκο του καταναλισκόμενου θειικού οξέος ως

\begin{equation}
\tag{2}
\frac{50 \cdot V_{H_2SO_4} \cdot 1000 \cdot 0.2}{20}
\label{eqn:2}
\end{equation}

Τέλος, η HPLC που έγινε είχε ως σκοπό την μέτρηση των διαλυτών σακχάρων, οξέων και αιθανόλης που υπήρχαν στα δείγματα. Ο χρόνος παραμονής στην στήλη ήταν 45 λεπτά. Ως κινητή φάση, χρησιμοποιήθηκε υπερκάθαρο νερό (νομίζω). Οι συγκεντρώσεις προσδιορίστηκαν με βάση πρότυπες καμπύλες για κάθε συστατικό από την επιφάνεια κάθε κορυφής στο χρωματογράφημα.
