#+TITLE: Draft της Εισαγωγής

* COMMENT Επεξήγηση
Το αρχείο αυτό είναι ένα πρώτο draft της εισαγωγής της διπλωματικής μου. Το γενικό train of thought φαίνεται στο αντίστοιχο xournal++ file, το οποίο δείχνει ψιλο σχηματικά το structure.

* Υδρόλυση
Η υδρόλυση γίνεται γενικά με 3 βασικές τεχνολογίες. Η πρώτη, είναι η θερμική υδρόλυση. Βασίζεται στην αύξηση της θερμοκρασίας, ώστε να αποικοδομηθούν τα πολυμερή και να είναι πιο εύκολη η αξιοποιήση του υπολείμματος. Ενδείκνειται για δύσκολα αποδομήσιμη βιομάζα, όπου είναι δύσκολο να χρησιμοποιηθεί κάποια άλλη τέχνικη. Βέβαια, λόγω των πολύ υψηλών ενεργειακών απαιτήσεων τους, δεν είναι ιδιαίτερα ελκυστικές για τα υπολείμματα τροφών, τα οποία είναι σχετικά εύκολα αποδομήσιμα [cite:@maUtmostBioenergyConversion2018].

Μία άλλη τεχνολογία είναι η χημική υδρόλυση. Βασίζεται στην χρήση κάποιων χημικών με ακραίες τιμές pH (είτε ισχυρά όξινα ή αλκαλικά), τα οποία μπορούν να προκαλέσουν κατάρρευση της πολυμερικής δομής και να απελευθερώσουν μικρότερα μόρια. Είναι μία πολύ φθηνή μέθοδος η οποία είναι όμως αποτελεσματική και για αυτό έχει ευρεία εφαρμογή. Όμως, στο περιβάλλον αυτό μπορούν να γίνουν ανεπιθύμητες αντιδράσεις, των οποίων τα προιόντα δρουν παρεμποδιστικά στις περισσότερες βιολογικές διεργασίες. Οπότε, παρόλο που η υδρόλυση θα έχει καλή απόδοση, το επόμενο στάδιο, που είναι και το στάδιο της αξιοποιήσης του υπολείμματος, δεν θα είναι πολύ αποδοτικό [cite:@maUtmostBioenergyConversion2018; @hanBiohydrogenProductionEnzymatic2016] .

Η τρίτη τεχνολογία είναι η ενζυμική υδρόλυση. Σε αυτήν, ειδικά ένζυμα, όπως οι υδατανθρακάσες, οι πρωτεάσες και οι κυτταρινάσες διασπούν τα πολυμερή σε μικρότερα μόρια. Δεν έχουν παραπροιόντα, χρησιμοποιούν ήπιες συνθήκες και έχουν την καλύτερη απόδοση από τις 3 τεχνολογίες [cite:@hanBiohydrogenProductionEnzymatic2016; @maUtmostBioenergyConversion2018] . Παρότι έχουν αυτά τα πλεονεκτήματα, έχουν ένα πολύ σημαντικό μειωνέκτημα. Το κόστος ενός ενζυμικού σκευάσματος για να γίνει σε μεγάλη κλίμακα η υδρόλυση είναι πολύ υψηλό, το οποίο εμποδίζει την εφαρμογή της τεχνολογίας αυτής. Βέβαια, μία αναλυτική οικονομική ανάλυση, η οποία σύγκρινε την ενζυμική με την χημική υδρόλυση, έδειξε πως ακόμη και με το αυξημένο κόστος της ενζυμικής υδρόλυσης, έχει μεγαλύτερο κέρδος λόγω της πολύ αυξημένης απόδοσης της συγκριτικά με την χημική υδρόλυση [cite:@zhangValorizationFoodWaste2020] .

* Ενζυμική Υδρόλυση
Καθώς η ενζυμική υδρόλυση θεωρείται η καλύτερη τεχνική για την βιοαποδόμηση των υπολειμμάτων τροφών, αλλά έχει το πρόβλημα του αρκετά αυξημένου κόστους, υπάρχει αρκετή μελέτη προσανατολισμένη στην μείωση του κόστους της ενζυμικής υδρόλυσης. Μία ιδέα που έχει προταθεί είναι η χρήση υπερήχων ως επικουρική προεπεξεργασία. Οι υπέρηχοι δημιουργούν ελεύθερες ρίζες υδροξυλίου οι οποίες είναι αντιδραστικές και μπορούν να συνεισφέρουν στην διάσπαση των πολυμερών [cite:@usmaniMinimizingHazardousImpact2021; @sureshProcessIntensificationComparison2020; @maUtmostBioenergyConversion2018] . Μία πιο αναλυτική μελέτη έδειξε πως σε batch πειράματα, η προεπεξεργασία με υπερήχους οδήγησε σε \( 10 \% \) καλύτερη αποδοτικότητα και σε μείωση του απαραίτητου χρόνου επεξεργασίας στο μισό. Σε ένα συνεχές σύστημα, αυτό θα σήμαινε μείωση της απαραίτητης ποσότητας ένζυμων στο μισό, το οποίο είναι μία πολύ σημαντική βελτίωση [cite:@liUltrasonicPretreatmentFood2019] . Όμως, η χρήση των υπερήχων έχει και αυτή ένα κόστος, το οποίο ειδικά σε μεγάλη κλίμακα είναι υψηλό. Οπότε, παρόλο που η τεχνολογία αυτή αυξάνει την απόδοση και μειώνει το κόστος, αυτό παραμένει αρκετά υψηλό, οπότε δεν μπορεί να θεωρηθεί μία τεχνική που θα επιτρέψει στην φθηνή μαζική επεξεργασία των υπολειμμάτων.

*πιθανόν να προσθέσω και κάποια άλλη παρόμοια προσπάθεια αν βρω*

Μία υποσχόμενη και οικονομικά εφαρμόσιμη λύση για το πρόβλημα αυτό είναι η χρήση σκευασμάτων τα οποία περιέχουν ένζυμα και μικροοργανισμούς. Το κόστος ενός τέτοιου σκευάσματος είναι σημαντικά χαμηλότερο από κάποιο το οποίο έχει μόνο ένζυμα, όμως, μπορεί να κάνει και αυτό αποτελεσματική βιοαποδόμηση. Ταυτόχρονα με την υδρόλυση, γίνεται και μία ζύμωση των υπολειμμάτων, η οποία παράγει προιόντα όπως η αιθανόλη και πτητικά λιπαρά οξέα (VFAs) όπως το οξικό, το προπιονικό και το γαλακτικό. Η ζύμωση αυτή κατατάσσεται στην κατηγορία οξεογενετικής ζύμωσης μικτής καλλιέργειας, η οποία είναι αρκετά μελετημένη στην βιβλιογραφία (σίγουρα χρειάζεται κάποια citations αλλά θα πρέπει να τα οργανώσω λίγο).

* Σκευάσματα με ένζυμα και μικροοργανισμούς
Τα προιόντα αυτής της μικτής διεργασίας είναι προιόντα τα οποία έχουν σημαντική αξία, οπότε μία τεχνολογία αξιοποίησης θα μπορούσε να είναι και η απευθείας ανάκτηση τους. Εναλλακτικά, μπορούν αυτά να χρησιμοποιηθούν ως ένα πιο κατάλληλο υπόστρωμα - σε σχέση με τα υπολείμματα τροφών - για κάποια άλλη διεργασία, όπως η αναερόβια χώνευση. Τα αρχικά στάδια της αναερόβιας χώνευσης είναι άλλωστε η υδρόλυση και η οξεογένεση, οπότε η διεξαγωγή τους σε ξεχωριστό αντιδραστήρα δεν δημιουργεί πρόβλημα. Μάλιστα, σε κάποιες περιπτώσεις είναι και πιο επιθυμητή η διεξαγωγή της αναερόβιας χώνευσης σε πολλά στάδια καθώς επιτρέπει καλύτερο έλεγχο της διεργασίας και συχνά αποφέρει καλύτερη απόδοση από ότι να γίνουν όλα σε ένα στάδιο (και για αυτό έχω κάποια citations).

Βέβαια, είτε στην περίπτωση ανάκτησης των προιόντων αυτών ή της χρήσης τους σε κάποια άλλη διεργασία, είναι πολύ σημαντικό, να κατανοηθεί ο μηχανισμός της ζύμωσης αυτής και ποιές αντιδράσουν συμβαίνουν, ώστε να μπορέσει μετά να ελεγχθεί η ζύμωση προς τα πιο επιθυμητά προιόντα ανά την εφαρμογή.

* Αναερόβια Χώνευση

