#+TITLE: ΒΙΟΑΠΟΔΟΜΗΣΗ ΥΠΟΛΕΙΜΜΑΤΩΝ ΤΡΟΦΙΜΩΝ ΚΑΙ ΠΑΡΑΓΩΓΗ ΒΙΟΑΕΡΙΟΥ ΜΕΣΩ ΑΝΑΕΡΟΒΙΑΣ ΧΩΝΕΥΣΗΣ ΣΕ ΕΡΓΑΣΤΗΡΙΑΚΗ ΚΑΙ ΠΙΛΟΤΙΚΗ ΚΛΙΜΑΚΑ
#+AUTHOR: Βιδιάνος Γιαννίτσης
\renewcommand{\abstractname}{Περίληψη}
\renewcommand{\tablename}{Πίνακας}
\renewcommand{\figurename}{Σχήμα }
\renewcommand{\chaptername}{Κεφάλαιο}
\renewcommand{\chapterautorefname}{Κεφάλαιο}
\renewcommand{\sectionautorefname}{Ενότητα}
\renewcommand{\partname}{Μέρος}
\renewcommand{\appendixname}{Παράρτημα}
\renewcommand{\listfigurename}{Περιεχόμενα Σχημάτων: }
\renewcommand{\listtablename}{Περιεχόμενα Πινάκων: }
\renewcommand\listingscaption{Κώδικας}
#+LATEX_CLASS: report
#+LATEX_HEADER: \usepackage[automake]{glossaries-extra}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \geometry{a4paper,width=150mm,top=25mm,bottom=25mm}
#+LATEX_HEADER: \makeglossaries
#+LATEX_HEADER: \definecolor{Julia_Blue}{RGB}{0, 154, 250}
#+LATEX_HEADER: \definecolor{Julia_Orange}{RGB}{227, 111, 71}
#+LATEX_HEADER: \definecolor{Julia_Green}{RGB}{62, 164, 76}
#+LATEX_HEADER: \hypersetup{linktoc = all, colorlinks = true, citecolor = Julia_Blue, linkcolor = Julia_Orange, urlcolor = Julia_Green}
#+cite_export: csl american-chemical-society.csl
\pagestyle{fancy}
\fancyhead{}
\fancyhead[L]{ΕΜΠ, Σχολή ΧΜ, Εργαστήριο ΟΧΤ}
\fancyhead[R]{Βιδιάνος Γιαννίτσης}
\fancyfoot{}
\fancyfoot[L]{\chaptername~\thechapter}
\fancyfoot[C]{\thepage}
\newacronym{fw}{ΥΤ}{υπολείμματα τροφών}
\newacronym{fao}{FAO}{Οργανισμός Τροφίμων και Αγρονομίας των Ηνωμένων Πολιτειών}
\newacronym{co2eq}{$CO_2$-eq}{ισοδύναμο διοξειδίου του άνθρακα}
\newacronym{xyta}{ΧΥΤΑ}{Χώρους Υγειονομικής Ταφής Απορριμάτων}
\newacronym{syngas}{syngas}{αέριο σύνθεσης}
\newacronym{pla}{PLA}{πολυγαλακτικό οξύ}
\newacronym{trl}{TRL}{technology readiness level}
\newacronym{vfa}{VFAs}{πτητικά λιπαρά οξέα}
\newacronym{hrt}{HRT}{υδραυλικός χρόνος παραμονής}
\newacronym{olr}{OLR}{ρυθμός οργανικής φόρτισης}
\newacronym{uasb}{UASB}{αντιδραστήρας ανοδικής ροής διαμέσου στρώσης ιλύος}
\newacronym{mix}{μιξ}{σκεύασμα ενζύμων και μικροοργανισμών}
\newacronym{ad}{ΑΧ}{αναερόβια χώνευση}
\newacronym{ts}{TS}{ολικά στερεά}
\newacronym{vs}{VS}{πτητικά στερεά}
\newacronym{cod}{COD}{χημικά απαιτούμενο οξυγόνο}
\newacronym{scod}{sCOD}{διαλυτό COD}
\newacronym{tcod}{tCOD}{ολικό COD}
\newacronym{pi}{PI}{Process Intensification}
\newacronym{ssf}{SSF}{Solid State Fermentation}
\newacronym{orp}{ORP}{οξειδοαναγωγικό δυναμικό}
\newacronym{emp}{EMP}{μονοπάτι Embden-Meyerhof}
\newacronym{lcfa}{LCFA}{long chain fatty acids}
\newacronym{acet-coa}{Acetyl-CoA}{ακέτυλο συνένζυμο Α}
\newacronym{nad}{NAD$^+$}{nicotinamide adenine dinucleotide}
\newacronym{nadh}{NADH}{nicotinamide adenine dinucleotide hydrogen}
\newacronym{fd}{Fd}{ferredoxins}
\newacronym{dg}{ΔG}{μεταβολή ελεύθερης ενέργειας Gibbs}
\newacronym{abe}{ABE}{ζύμωση ακετόνης-βουτανόλης-αιθανόλης}
\newacronym{ed}{ED}{μονοπάτι Entner-Doudoroff}
\newacronym{pp}{PP}{μονοπάτι Pentose Phosphate}
\newacronym{pk}{PK}{μονοπάτι Phosphoketolase}
\newacronym{am}{AM}{ακετοκλαστικοί μεθανογόνοι}
\newacronym{hm}{YM}{υδρογονοτρόφοι μεθανογόνοι}
\newacronym{zvi}{ZVI}{σίδηρος μηδενικού σθένους}
\newacronym{redox}{redox}{οξειδωαναγογικό δυναμικό}
\newacronym{iht}{IHT}{interspecies hydrogen transfer}
\newacronym{diet}{DIET}{direct interspecies electron transfer}
\newacronym{tvfa}{tVFAs}{συνολικά πτητικά λιπαρά οξέα}
\newacronym{bmp}{BMP}{βιοχημικό δυναμικό μεθανίου}
\newacronym{sma}{SMA}{ειδική μεθανογόνος δραστικότητα της λάσπης}
\newacronym{kel}{ΚΕΛ}{κέντρο επεξεργασίας λυμάτων}
\newacronym{ss}{SS}{αιωρούμενα στερεά}
\newacronym{tss}{TSS}{ολικά αιωρούμενα στερεά}
\newacronym{vss}{VSS}{πτητικά αιωρούμενα στερεά}
\newacronym{hplc}{HPLC}{υγρή χρωματογραφία υψηλής απόδοσης}
\newacronym{si}{S/I}{υποστρώματος προς εμβόλιο}
\newacronym{anova}{ANOVA}{ανάλυση διακύμανσης}
\newacronym{mcfa}{MCFA}{λιπαρά οξέα μέτριας ανθρακικής αλυσίδας}
\newacronym{pha}{PHAs}{πολυ-υδρόξυαλκανοϊκοί εστέρες}

#+options: toc:nil title:nil author:nil date:nil
#+LATEX_HEADER: \newcommand{\HRule}{\rule{\linewidth}{0.5mm}}
#+BEGIN_SRC latex
  \renewcommand{\contentsname}{Κεφάλαια: }
  \begin{titlepage}

  \begin{center}
    \begin{minipage}{0.2\textwidth}
      \begin{flushleft}
	\includegraphics[width=1\textwidth]{~/Pictures/ntua_logo.png}\\[0.4cm]    
      \end{flushleft}
    \end{minipage}
    \begin{minipage}{0.75\textwidth}
      \textsc{\bfseries \Large ΕΘΝΙΚΟ ΜΕΤΣΟΒΙΟ ΠΟΛΥΤΕΧΝΕΙΟ}\\[0.2cm]
      \textsc{\bfseries \Large ΣΧΟΛΗ ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ}\\[0.2cm]
      \textsc{\large \bfseries ΤΟΜΕΑΣ IV: ΣΥΝΘΕΣΗ ΚΑΙ ΑΝΑΠΤΥΞΗ ΒΙΟΜΗΧΑΝΙΚΩΝ ΔΙΑΔΙΚΑΣΙΩΝ}\\[0.2cm]
      \textsc{\bfseries \large ΕΡΓΑΣΤΗΡΙΟ ΟΡΓΑΝΙΚΗΣ ΧΗΜΙΚΗΣ \\ ΤΕΧΝΟΛΟΓΙΑΣ}\\[0.2cm]
    \end{minipage}
    \\[2.5cm]

    \HRule \\[0.3cm]
    \Huge Βιοαποδόμηση Υπολειμμάτων Τροφίμων και Παραγωγή Βιοαερίου μέσω Αναερόβιας Χώνευσης σε Εργαστηριακή και Πιλοτική Κλίμακα\\[2.5cm]

    \huge Διπλωματική Εργασία \\[0.3cm]
     \begin{minipage}{0.4\textwidth}
      \begin{flushleft}
	\emph{\LARGE Συγγραφέας:}\\
	  \emph{\LARGE Αριθμός Μητρώου:} \\
	  \emph{\LARGE e-mail:} \\

	  \emph{\LARGE Υπεύθυνος Καθηγητής:}
	\end{flushleft}
      \end{minipage}
      \begin{minipage}{0.4\textwidth}
	\begin{flushright} \large
	  \LARGE Βιδιάνος Γιαννίτσης\\
	  \LARGE ch19113\\
	  \LARGE vidianosgiannitsis@gmail.com \\
  
	  \LARGE Ανέστης Βλυσίδης
	\end{flushright}
      \end{minipage}
      \HRule \\[0.3cm]
    \vfill
  {\LARGE Αθήνα, 2024}

  \end{center}

  \end{titlepage}
#+END_SRC

\begin{abstract}

\large Τα υπολείμματα τροφών (ΥΤ) αποτελούν μία από τις σημαντικότερες κατηγορίες οργανικών αποβλήτων. Η μη ορθή διαχείριση των ΥΤ επιβαρύνει σημαντικά κάθε έναν από τους τρείς πυλώνες της βιωσιμότητας. Το βασικότερο πρόβλημα στην ορθή διαχείριση τους είναι η περιεκτικότητα τους σε βιοπολυμερή. Οπότε, για να αξιοποιηθούν κατάλληλα, απαιτείται ένα στάδιο υδρόλυσης/βιοαποδόμησης. Ιδανικά, αυτό θα γίνει ενζυμικά για να έχει την καλύτερη απόδοση. Όμως, το υψηλό κόστος ενός ενζυμικού σκευάσματος εμποδίζει την εμπορική εφαρμογή μίας τέτοιας διεργασίας. Μία υποσχόμενη και οικονομικά εφαρμόσιμη λύση είναι η χρήση εμπορικών σκευασμάτων ενζύμων και μικροοργανισμών. Ένα τέτοιο σκεύασμα έχει υψηλή ενζυμική ενεργότητα, οπότε μπορεί να υδρολύσει αποτελεσματικά τα υπολείμματα, αλλά έχει πολύ χαμηλή τιμή σε σχέση με καθαρά ένζυμα. Ακόμη, λόγω της παρουσίας μικροοργανισμών, γίνεται μία ταυτόχρονη ζύμωση των ΥΤ. Σκοπός της παρούσας μελέτης είναι η αναλυτική διερεύνηση της δράσης ενος τέτοιου σκευάσματος για παραγωγή μίας υγρής εκροής πλούσιας σε πτητικά λιπαρά οξέα σε εργαστηριακή και πιλοτική κλίμακα. Η εκροή αυτή μπορεί να χρησιμοποιηθεί για διεργασίες όπως η αναερόβια χώνευση. Στα πειράματα εργαστηριακής κλίμακας, τα οποία διεξάχθηκαν σε αντιδραστήρες διαλείποντος έργου, συνολικού όγκου 1 L, έγινε βελτιστοποίηση της διεργασίας ως προς την θερμοκρασία και την ποσότητα του σκευάσματος που προστίθεται. Μέσω αυτών, βρέθηκε πως η υδρόλυση παράγει την μέγιστη ποσότητα οξεογενών προϊόντων σε θερμοκρασία 40 $^o$C και σε ποσότητα 10 mL σκευάσματος/kg ΥΤ. Στα πειράματα πιλοτικής κλίμακας, τα οποία διεξάχθηκαν σε αντιδραστήρα 300 L ημισυνεχούς λειτουργίας, έγιναν δοκιμές για να εξεταστεί η κλιμάκωση της διεργασίας και εξετάστηκε η ποιότητα της υδρόλυσης ανάλογα με την ποσότητα σκευάσματος και την παροχή νερού. Βρέθηκε πως η παροχή μεγαλύτερης ποσότητας νερού δεν επηρεάζει την υδρόλυση, πέραν της αραίωσης, ενώ η ποσότητα σκευάσματος επηρεάζει αρνητικά την παραγωγή διαλυτού οργανικού φορτίου αν αυξηθεί από 5 $\frac{mL}{kg~ ΥΤ}$ σε 10 $\frac{mL}{kg~ ΥΤ}$ καθώς ο λόγος $\frac{sCOD}{tCOD}$ μεταβάλλεται από $46.1 \pm 12.2 \%$ σε $32.7 \pm 10.3 \%$ κατά την αλλαγή αυτή. Έχοντας βελτιστοποιήσει την διεργασία αυτή, έγιναν και δοκιμές αναερόβιας χώνευσης σε αντιδραστήρες διαλείποντος έργου 500 mL, για να μετρηθεί η παραγωγή βιομεθανίου από τα υδρολύματα αυτά, χρησιμοποιώντας αναερόβια λάσπη από 3 διαφορετικές πηγές, για να διαπιστωθεί η επαναληψιμότητα των πειραμάτων. Παρατηρήθηκε πως τα υδρολύματα με 5 και 10 mL σκευάσματος/kg ΥΤ είχαν την καλύτερη απόδοση. Συγκεκριμένα, το 10 $\frac{mL}{kg ~ΥΤ}$ είχε το χαμηλότερο χρόνο καθυστέρησης και τον υψηλότερο ρυθμό παραγωγής μεθανίου, λόγω της καλύτερης οξεογένεσης. Όμως, είχε χαμηλότερη παραγωγή μεθανίου από το υδρόλυμα με 5 mL σκευάσματος/kg ΥΤ, καθώς είχε χειρότερη υδρόλυση. Σε σύγκριση με ανεπεξέργαστα ΥΤ, τα υδρολύματα αυτά είχαν 4-5 φορές περισσότερη παραγωγή μεθανίου. Τα συμπεράσματα αυτά επαληθεύτηκαν για λάσπες διαφορετικών προελεύσεων και χρησιμοποιώντας υδρόλυμα από εργαστηριακή αλλά και πιλοτική κλίμακα. Συμπερασματικά, η υδρόλυση/βιοαποδόμηση ΥΤ μπορεί να γίνει αποτελεσματικά με ένα εμπορικό σκεύασμα ενζύμων και μικροοργανισμών και το παραγώμενο υδρόλυμα είναι ιδιαίτερα κατάλληλο ως υπόστρωμα για αναερόβια χώνευση. \\


Λέξεις Κλειδιά: Υπολείμματα τροφίμων, Υδρόλυση, Βιοαποδόμηση, Αναερόβια χώνευση, Παραγωγή μεθανίου
\end{abstract}

\renewcommand{\abstractname}{Abstract}
\begin{abstract}

\large Food Waste (FW) is one of the most important categories of organic waste. The improper treatment of FW has a very negative impact in all three of the sustainability pillars. The largest problem in properly trating FW is their biopolymer content. For their proper valorization, a hydrolysis/biodegradation step is necessary. Ideally, this is done using enzymes, as this gives the best yield. However, the high cost of enzymic mixtures makes the commercial application of this process very hard. A promising and economic solution for this is the use of commercial mixtures of enzymes and microorganism. Such a mix has high enzymatic activity, thus can effectively hydrolyze the FW, but has a very low price compared to pure enzymes. Furthermore, due to the microorganisms, the FW is fermented as well as hydrolyzed. The goal of this study is an in-depth analysis of the function of such a mix for the production of a liquid effluent, rich in volatile fatty acids, in lab and pilot scale. This effluent can be used in processes such as anaerobic digestion. In the lab scale experiments, which were conducted in batch reactors of total volume 1 L, the process was optimized for temperature and mix amount. From these experiments, it was found that the maximum amount of acidogenic products were produced at a temperature of 40 $^o$ C and with a mix amount of 10 mL/kg FW. In the pilot scale experiments, which were conducted in a semi-continuous reactor with volume 300 L, scale-up tests were done, as well as tests for the hydrolysis quality when varying the mix amount and water flow. It was found that increasing the water flow did not affect the hydrolysis, while the addition of mix beyond 5 mL/kg FW negatively affected the process, since $\frac{sCOD}{tCOD}$ changed from $46.1 \pm 12.2 \%$ to $32.7 \pm 10.3 \%$ when the mix amount was increased to 10 mL/kg FW. Having optimized this process, anaerobic tests were conducted in batch reactors with volume 500 mL, to assess the biomethane production of these hydrolysates, using sludge from 3 different sources, for reproducibility. It was found that the hydrolysates with 5 and 10 mL mix/kg FW had the best production. Specifically, the hydrolysate with 10 mL mix/kg FW had the lowest lag time and fastest production rate, indicating the best acidogenesis, but had less methane production compared to the hydrolysate with 5 mL mix/kg FW. Compared to untreated FW, the hydrolysates had 4-5 times more methane production. These conclusions were validated for different sludge samples and using both and lab and pilot scale hydrolysates. To conclude, the hydrolysis/biodegradation of FW can be effectively done using a commercial mixture of enzymes and microorganisms and the produced hydrolysate is a very good substrate for anaerobic digestion. \\ 


Keywords: Food waste, Hydrolysis, Biodegradation, Anaerobic digestion, Methane production
\end{abstract}

** Ευχαριστίες
:PROPERTIES:
:UNNUMBERED: 1
:END:

Η διπλωματική εργασία αυτή δεν θα ήταν δυνατή χωρίς την βοήθεια και καθοδήγηση που δέχτηκα από τον υπεύθυνο καθηγητή μου κ. Ανέστη Βλυσίδη, με τον οποίο είχα εξαιρετική συννενόηση και συνεργασία. Χάρις αυτόν η εργασία παρουσιάστηκε πρόσφατα στο 14ο Πανελλήνιο Συνέδριο Χημικής Μηχανικής, όπου βραβεύτηκε ως η καλύτερη αναρτημένη εργασία της ημέρας και είμαι ιδιαίτερα ευγνώμων που μου δώθηκε αυτή η ευκαιρία. Ιδιαίτερα πολύτιμη ήταν και η βοήθεια που είχα στην διεξαγωγή των πειραμάτων, αλλά και στη συγγραφή της εργασίας από τους μεταδιδακτορικούς ερευνητές του εργαστηρίου Οργανικής Χημικής Τεχνολογίας Δημοσθένη Τσιβά και Δήμητρα Θεοδόση Παλιμέρη. Και οι δύο ήταν εκεί για ότι χρειάστηκα και η στήριξη τους ήταν πολύ σημαντική για την ολοκλήρωση της εργασίας αυτής.

Ακόμη, νιώθω υπόχρεος στην ομάδα του Statista, οι οποίοι μας πρόσφεραν δωρεάν πρόσβαση σε όλη την ιστοσελίδα τους για μερικούς μήνες. Χάρις αυτό, κατάφερα να βρω πολύ αναλυτικά και ανανεωμένα στατιστικά στοιχεία για το αντικείμενο της μελέτης μου, τα οποία έκαναν την εισαγωγή της εργασίας πολύ πιο ευπαρουσίαστη και ενδιαφέρουσα.

Επίσης όμως θα ήθελα να ευχαριστήσω όλο το εργαστήριο Οργανικής Χημικής Τεχνολογίας, από τα μέλη ΕΔΙΠ κ. Δημήτρη Κουλλά και κ. Λάζαρο Καραογλάνογλου, τον μεταδιδακτορικό ερευνητή Κωνσταντίνο Τζάθα, τους υποψήφιους διδάκτορες Παντελή Μάνακα και Ιωάννα Γουδέλη αλλά και τις φοιτήτριες Ιωάννα Κοροπούλη, Αθανασία Δημητρέλου, Στυλιανή Σταύρου και Νεφέλη Καραγιαννοπούλου που έκαναν τις διπλωματικές τους στο εργαστήριο για την ιδιαίτερα ευχάριστη ατμόσφαιρα που είχε το εργαστήριο, κάτι που έκανε την διεξαγωγή των πειραμάτων της εργασίας μου πολύ πιο ευχάριστη. Τέλος, δεν θα μπορούσα να ολοκληρώσω τις ευχαριστίες χωρίς να πω ευχαριστώ στην οικογένεια και στους φίλους μου, οι οποίοι παρότι δεν έπαιξαν άμεσο ρόλο στην εκπόνηση της εργασίας αυτής, με στηρίζουν καθημερινά με άλλους τρόπους.

* Περιεχόμενα
:PROPERTIES:
:UNNUMBERED: 1
:END:
\tableofcontents
\pagebreak

[[list-of-figures:]]
\pagebreak

[[list-of-tables:]]
\pagebreak

\printglossary
\printglossary[type = \acronymtype, title = Συντομογραφίες]

* Θεωρητικό Μέρος
#+INCLUDE: "./intro_of_intro.org::*Εισαγωγή" :minlevel 2

#+INCLUDE: "./anaerobic_digestion_problems.org" :minlevel 2

#+INCLUDE: "./pretreatments.org" :minlevel 2

#+INCLUDE: "./acidogenesis.org" :minlevel 2

#+INCLUDE: "./acetogenesis_methanogenesis.org" :minlevel 2

* Πειραματικό Μέρος
#+INCLUDE: "./experimental.org" :minlevel 2

#+INCLUDE: "./result_discussion.org" :minlevel 2

#+INCLUDE: "./conclusion.org" :minlevel 2

* Βιβλιογραφία
:PROPERTIES:
:UNNUMBERED: 1
:END:
#+print_bibliography:

#+LATEX: \appendix
* Παραρτήματα
#+INCLUDE: "./metabolic_pathways.org" :minlevel 2
