#+TITLE: Μεθόδοι Επεξεργασίας

* COMMENT Επεξήγηση
Στο αρχείο αυτό θα αναπτυχθεί το 3ο κεφάλαιο της διπλωματικής μου, το οποίο θα είναι σχετικό με μεθόδους προεπεξεργασίας των FW για την υδρόλυση του υποστρώματος.

* Προεπεξεργασία Υπολειμμάτων Τροφών
\label{sec:fw_pretreatment}

Τα \acrshort{fw} έχουν υψηλή περιεκτικότητα σε βιοπολυμερή. Για να μπορέσουν να χρησιμοποιηθούν αποδοτικά ως ένα υπόστρωμα για διεργασίες όπως η \acrshort{ad}, απαιτείται κάποια διεργασία η οποία θα υδρολύσει το υπόστρωμα αυτό. Υπάρχουν πολλές τεχνολογίες για να βοηθήσουν την υδρόλυση του υποστρώματος αυτού όπως η μηχανική, θερμική, χημική ή ενζυμική προεπεξεργασία και η προεπεξεργασίες με υπερήχους και μικροκύματα.

** Μηχανική Επεξεργασία
Η πιο απλή είναι η μηχανική επεξεργασία. Μία μηχανική επεξεργασία όπως ο τεμαχισμός είναι αρκετά αποτελεσματική. Ο σκοπός της είναι η ομογενοποίηση της στερεής μάζας και μείωση του μεγέθους κόκκων της ώστε να επιταχυνθούν τα επόμενα στάδια της προεπεξεργασίας. Είναι το πιο σύνηθες στάδιο προεπεξεργασίας και γίνεται ανεξαρτήτως των επόμενων σταδίων συνήθως [cite:@chenProcessDesignTechnoeconomic2022; @moonEnzymaticHydrolysisFoodWaste2011; @usmaniMinimizingHazardousImpact2021] . 

** Θερμική Επεξεργασία
Η θερμική υδρόλυση βασίζεται στην αύξηση της θερμοκρασίας, με σκοπό την διάσπαση των πολυμερικών δεσμών. Είναι πολύ αποτελεσματική ως μία προεπεξεργασία για δύσκολα αποδομήσιμη βιομάζα. Στην περίπτωση των \acrshort{fw}, οι υψηλές θερμοκρασίες δεν είναι αναγκαίες για την αποικοδόμηση και μάλιστα συνήθως υποβαθμίζουν την ποιότητα του υποστρώματος καθώς καταστρέφουν οργανική ύλη και μπορεί να παράξουν προιόντα θερμικής αποδόμησης τα οποία είναι τοξικά για επόμενα βιολογικά στάδια. Ακόμη, είναι μία τεχνική με σχετικά υψηλές ενεργειακές απαιτήσεις [cite:@srisowmeyaCriticalConsiderationsTwostage2020; @cesaroPretreatmentMethodsImprove2014; @maUtmostBioenergyConversion2018] .

** Επεξεργασία με Μικροκύματα
Αντίστοιχη λογική έχει και η χρήση μικροκυμάτων, η οποία αυξάνει την θερμοκρασία μέσω ενός ηλεκτρομαγνητικού πεδίου. Θεωρείται πιο αποτελεσματική από την θερμική τεχνολογία λόγω της μικρότερης κατανάλωσης ενέργειας. Επίσης, συνδυάζει θερμικά με μη θερμικά φαινόμενα. Όμως, όπως και στη περίπτωση της θερμικής υδρόλυσης, δεν επιφέρει ιδιαίτερα θετικά αποτελέσματα για την επεξεργασία \acrshort{fw} [cite:@cesaroPretreatmentMethodsImprove2014; @maUtmostBioenergyConversion2018; @srisowmeyaCriticalConsiderationsTwostage2020] . 

** Επεξεργασία με Υπερήχους
Η χρήση υπερήχων βασίζεται στην δημιουργία ελεύθερων ριζών υδροξυλίου \( OH^{\cdot} \), οι οποίες διασπούν ταχύτατα τα στερεά, απελευθερώνοντας μεγάλα ποσά οργανικής ύλης. Πειράματα που έχουν χρησιμοποιήσει υπερήχους ως μία προεπεξεργασία για αναερόβια χώνευση έχουν δείξει πως βελτιώνει αρκετά την παραγωγή μεθανίου. Βέβαια, υδρολύουν μόνο σε περιορισμένο βαθμό το υπόστρωμα, με αποτέλεσμα να πρέπει να γίνει και κάποια υδρόλυση κατά την διάρκεια της χώνευσης [cite:@cesaroPretreatmentMethodsImprove2014; @maUtmostBioenergyConversion2018] .

** Χημική Επεξεργασία
Σε ένα παρόμοιο μηχανισμό βασίζεται και η χημική τεχνολογία της οζόνωσης, καθώς η τροφοδοσία με όζον δημιουργεί και αυτή ελεύθερες ρίζες οι οποίες διασπούν την στερεή οργανική ύλη. Είναι όμως μία πιο έντονη επεξεργασία η οποία χρησιμοποιείται σε υποστρώματα τα οποία είναι πιο δύσκολα στην αποδόμηση. Στην περίπτωση των \acrshort{fw} μπορεί να οδηγήσουν σε μείωση του COD λόγω οξείδωσης ακόμη και των ζυμώσιμων σακχάρων και παραγωγής προιόντων πιο δύσκολα αποδομήσιμα από τα αρχικά, για αυτό αποφεύγεται [cite:@srisowmeyaCriticalConsiderationsTwostage2020; @cesaroPretreatmentMethodsImprove2014] .

Βέβαια, η πιο συχνή κατηγορία χημικής επεξεργασίας είναι αυτή που βασίζεται στην προσθήκη οξέος ή βάσης. Η προσθήκη των ενώσεων αυτών βασίζεται στην επίτευξη ακραίων τιμών pH, στις οποίες καταρρέει η πολυμερική δομή. Στην τεχνολογία αυτή χρησιμοποιούνται ισχυρά οξέα ή βάσεις (πχ θειικό οξύ, υδροχλωρικό οξύ, καυστικό νάτριο ή ασβέστης). Η τεχνολογία αυτή είναι η πιο απλή και φθηνή τεχνολογία προεπεξεργασίας, αλλά είναι και αρκετά αποτελεσματική. Για αυτό χρησιμοποιείται αρκετά [cite:@cesaroPretreatmentMethodsImprove2014; @maUtmostBioenergyConversion2018; @zhangValorizationFoodWaste2020]. Ακόμη, για την αλκαλική υδρόλυση, ισχύει πως αν τα \acrshort{fw} χρησιμοποιηθούν μετά για αναερόβια χώνευση, το σύστημα θα έχει αποκτήσει μεγαλύτερη αλκαλικότητα, με αποτέλεσμα να έχει καλύτερη σταθερότητα η διεργασία [cite:@srisowmeyaCriticalConsiderationsTwostage2020] . Όμως, μπορεί να παραχθούν μη επιθυμητά προϊόντα κατά την όξινη ή αλκαλική αποδόμηση των \acrshort{fw}, όπως η φουρφουράλη, τα οποία είναι τοξικά προς μικροοργανισμούς και άρα να μειωθεί σημαντικά η απόδοση της διεργασίας [cite:@hanBiohydrogenProductionEnzymatic2016; @zhangValorizationFoodWaste2020; @maUtmostBioenergyConversion2018] .

** Ενζυμική Επεξεργασία
Τέλος, υπάρχει η ενζυμική επεξεργασία. Αυτή βασίζεται στην χρήση υδρολυτικών ενζύμων όπως οι υδατανθρακάσες, οι πρωτεάσες και οι λιπάσες για την διάσπαση των βιοπολυμερών. Η διεργασία αυτή δεν έχει κανένα τοξικό παραπροιόν, ήπιες συνθήκες (οι οποίες συνδέονται με το κόστος) και εξαιρετική απόδοση υδρόλυσης/βιοαποδόμησης [cite:@maUtmostBioenergyConversion2018; @hanBiohydrogenProductionEnzymatic2016; @jingStatisticalOptimizationSimultaneous2020]. Επίσης, είναι η μόνη προεπεξεργασία, της οποίας οι συνθήκες μπορούν να ρυθμιστούν έτσι ώστε να γίνει ταυτόχρονα με την οξεογένεση, το οποίο επιτρέπει την αναερόβια χώνευση σε 2 στάδια. Σε κάθε άλλη περίπτωση, η διεργασία πρέπει να γίνει σε τρία στάδια, το οποίο παρότι προσφέρει σταθερότητα και πιθανόν καλύτερες αποδόσεις, δημιουργεί και πολυπλοκότητα στην διεργασία [cite:@usmaniMinimizingHazardousImpact2021; @maUtmostBioenergyConversion2018] . Παρόλα αυτά, το κόστος ενός εμπορικού ενζυμικού σκευάσματος είναι πολύ υψηλό, κάτι που καθιστά την συμβατική ενζυμική υδρόλυση μία τεχνολογία απαγορευτική σε μεγάλη κλίμακα. Για τον λόγο αυτόν, στην βιβλιογραφία υπάρχουν αρκετές μελέτες χρησιμοποιώντας πρωτοποριακές τεχνολογίες ενζυμικής υδρόλυσης χαμηλού κόστους για να λύσουν το πρόβλημα αυτό [cite:@chenReviewMicroaerationbasedAnaerobic2020; @zhangThreestageAnaerobicDigester2017; @dossantosferreiraEnzymaticPretreatmentAnaerobic2020; @pleissnerDirectProductionLactic2017; @sureshProcessIntensificationComparison2020] . Οι τεχνολογίες αυτές θα αναλυθούν σε περισσότερο βάθος στο \autoref{sec:enzymes}.

** Απόκριση της Υδρόλυσης
Αλλά μία σημαντική ερώτηση που έγκειται για την υδρόλυση, είναι πως προσδιορίζεται πειραματικά η απόδοση μίας τέτοιας διεργασίας. Στην πράξη, το σημαντικότερο μέτρο για αυτό είναι ο λόγος \acrfull{scod} προς \acrfull{tcod}. Αυτό δείχνει πόση από την οργανική ύλη έχει διαλυτοποιηθεί και στα \acrshort{fw} ξεκινάει από \( 20-30 \% \) συνήθως και μπορεί να φτάσει από \( 60 - 80 \% \) σε μία αρκετά αποδοτική υδρόλυση [cite:@kavithaLiquefactionFoodWaste2017; @graunkeExaminingMechanismsShortterm2014; @fangSynergisticCodigestionWaste2020] .

* Βελτιστοποίηση της Διεργασίας της Ενζυμικής Υδρόλυσης
\label{sec:enzymes}

Στο \autoref{sec:fw_pretreatment} αναφέρθηκαν όλες οι τεχνολογίες προεπεξεργασίας των \acrshort{fw}. Σκοπός αυτών είναι η επίτευξη υψηλών αποδόσεων σε επόμενα βιολογικά στάδια όπως η \acrshort{ad}. Προέκυψε, πως η ενζυμική υδρόλυση/βιοαποδόμηση είναι η πιο αποτελεσματική καθώς δεν έχει παραπροιόντα, χρησιμοποιεί ήπιες συνθήκες, μειώνει αποτελεσματικά τα \acrfull{ts} και αυξάνει το διαλυτό \acrfull{cod}, ενώ μπορεί να γίνει παράλληλα με την οξεογένεση. Όμως, αναφέρθηκε πως το κύριο εμπόδιο της είναι το κόστος των ενζυμικών σκευασμάτων. Για αυτό, στο κεφάλαιο αυτό θα αναφερθούν όλες οι τεχνολογίες που έχουν προταθεί στην βιβλιογραφία για την μείωση του κόστους της διεργασίας αυτής. Γενικά, κατατάσσονται σε δύο κατηγορίες:

- Εντατικοποίηση της διεργασίας υδρόλυσης (\acrfull{pi}) και μείωση του απαιτούμενου χρόνου υδρόλυσης, ο οποίος σε συνεχή συστήματα αντιστοιχεί στην ποσότητα ενζύμων που απαιτούνται.
- Χρήση μικροοργανισμών, οι οποίοι στις κατάλληλες συνθήκες θα εκκρίνουν υδρολυτικά ένζυμα in-situ για την υδρόλυση

** Εντατικοποίηση της Διεργασίας Υδρόλυσης
Οι μελέτες οι οποίες υπάγονται σε αυτήν την κατηγορία αποτελούν τις μελέτες οι οποίες έχουν προσπαθήσει να βελτιστοποιήσουν διάφορες συνθήκες της υδρόλυσης, με σκοπό την πιο αποτελεσματική και γρήγορη ενζυμική υδρόλυση, η οποία θα έχει χαμηλότερο κόστος.

Για παράδειγμα, οι [cite:@graunkeExaminingMechanismsShortterm2014] προσπάθησαν να μειώσουν πολύ τον χρόνο παραμονής στην υδρόλυση και έδειξαν ότι με βέλτιστες συνθήκες, σε περίπου 4 ώρες έχει γίνει ικανοποιητική υδρόλυση. Καθώς ο χρόνος αυτός συχνά είναι στις 24 ώρες, μία τέτοια μείωση θα μπορούσε να μειώσει σημαντικά την απαίτηση σε ένζυμα και άρα να βελτιώσει το οικονομικό προφίλ της διεργασίας [cite:@moonEnzymaticHydrolysisFood2009; @maUtmostBioenergyConversion2018; @zhangAnaerobicFermentationPretreated2021] .

Οι [cite:@sureshProcessIntensificationComparison2020] έκαναν μία μελέτη στην οποία προσπάθησαν να βελτιστοποίησουν μία διεργασία παραγωγής βιοαιθανόλης από απόβλητα της βιομηχανίας επεξεργασίας πατάτας λαμβάνοντας υπόψην συνθήκες όπως η ποσότητα ενζύμων που θα χρησιμοποιηθεί και η πιθανότητα χρήσης άλλων διεργασιών υδρόλυσης επικουρικά, όπως η προσθήκη HCl ή χρήση υπερήχων κατά την διεργασία.

Οι [cite:@liUltrasonicPretreatmentFood2019] χρησιμοποιήσαν έναν συνδυασμό υπερήχων και ενζυμικής υδρόλυσης με σκοπό οι υπέρηχοι να κάνουν την βιομάζα πιο προσβάσιμη στα ένζυμα, με σκοπό να μειωθεί σημαντικά η ποσότητα ενζύμων που πρέπει να προστεθεί. Η μελέτη τους έδειξε πως αυτός ο συνδυασμός είναι αρκετά αποτελεσματικός.

Παρόλες τις επιτυχίες που υπάρχουν στον τομέα αυτόν, ακόμη και με σημαντική μείωση της ποσότητας ενζύμων που χρειάζονται, όσο μεγαλώνει η κλίμακα, γίνεται όλο και πιο δύσκολο η τεχνική αυτή να είναι αποτελεσματική. Οπότε, θεωρείται πως οι πιο αποτελεσματικές τεχνικές υδρόλυσης είναι στην δεύτερη κατηγορία, όπου το σύστημα τροφοδοτείται με μικροοργανισμούς και οι συνθήκες ελέγχονται ώστε να παραχθούν in-situ μεγάλες ποσότητες υδρολυτικών ενζύμων.

** Ζύμωση Στερεής Κατάστασης
  Η ζύμωση στερεής κατάστασης (\acrfull{ssf}) είναι μία αρκετά ενδιαφέρουσα κατηγορία ζύμωσης. Η βασική της αρχή είναι πως δεν χρησιμοποιείται νερό στον αντιδραστήρα όπου θα αναπτυχθεί ο μικροοργανισμός (ή οι μικροοργανισμοί στη περίπτωση μικτής καλλιέργειας) αλλά κάποια στερεή φάση, η οποία μπορεί να χρησιμοποιηθεί ως η τροφή του μικροοργανισμού [cite:@pleissnerDirectProductionLactic2017; @dossantosferreiraEnzymaticPretreatmentAnaerobic2020].

  Μία από τις βασικές εφαρμογές της \acrshort{ssf} είναι η ανάπτυξη μυκήτων οι οποίοι μπορούν να εκκρίνουν μεγάλη ποσότητα ενζύμων. Η τεχνολογία αυτή για την παραγωγή υδρολυτικών ενζύμων έχει αρκετό ενδιαφέρον, καθώς είναι μία διεργασία η οποία χρησιμοποιεί συχνά απόβλητα ως πρώτη ύλη. Για παράδειγμα, μπορούν τα ίδια \acrshort{fw} που θα χρησιμοποιηθούν για την \acrshort{ad} να χρησιμοποιηθούν και στην \acrshort{ssf} [cite:@uckunkiranEnzymeProductionFood2014]. Έπειτα, η βιομάζα που έχει παραχθεί στην \acrshort{ssf} μπορεί να αναμειχθεί με τα υπόλοιπα \acrshort{fw} και το μίγμα αυτό να χρησιμοποιηθεί για διεργασίες όπως η αναερόβια χώνευση [cite:@dossantosferreiraEnzymaticPretreatmentAnaerobic2020; @soaresReductionScumAccumulation2019]. Ακόμη όμως και στην περίπτωση που δεν χρησιμοποιούνται απόβλητα, χρησιμοποιείται κάποιο φθηνό υπόστρωμα, το οποίο προσωμοιώνει το φυσικό περιβάλλον ανάπτυξης του μικροοργανισμού, και όχι κάποια καθαρή ένωση όπως η γλυκόζη. Έτσι, μπορούν να παραχθούν μεγάλες ποσότητες υδρολυτικών ενζύμων σε πολύ χαμηλό κόστος [cite:@uckunkiranEnhancingHydrolysisMethane2015; @zouValorizationFoodWaste2020; @pleissnerDirectProductionLactic2017] . 

  Επιπλέον, στην διεργασία \acrshort{ssf} δεν απαιτούνται στάδια καθαρισμού, καθώς όλη η βιομάζα του μύκητα, η οποία είνα πλούσια σε υδρολυτικά ένζυμα, προστίθεται στον αντιδραστήρα. Ο καθαρισμός των ενζύμων είναι το δυσκολότερο κομμάτι της παραγωγής τους και ο βασικός λόγος για τον οποίο είναι ακριβά. Μία τέτοια διεργασία μπορεί να παράγει ένζυμα χωρίς αυτόν τον περιορισμό, και σε ορισμένες περιπτώσεις να είναι και πιο αποτελεσματική από την χρήση ενός εμπορικού σκευάσματος. Επιπροσθέτως, μπορεί να παραχθεί ένα μίγμα ενζύμων το οποίο είναι δύσκολο να βρεθεί ως έχει εμπορικά [cite:@zouValorizationFoodWaste2020; @dossantosferreiraEnzymaticPretreatmentAnaerobic2020; @uckunkiranEnhancingHydrolysisMethane2015].

  Εκτός όμως από το κόστος, η τεχνολογία αυτή έχει πολλά πλεονεκτήματα. Αρχικά, καθώς μιλάμε για στερεή φάση και όχι υδατική, ο όγκος του αντιδραστήρα που απαιτείται είναι αρκετά μικρός, το οποίο μειώνει σημαντικά το κόστος της διεργασίας. Επίσης, σε μία στερεή φάση, υπάρχει μικρότερος κίνδυνος για μόλυνση σε σχέση με την υγρή. Ακόμη, το προιόν της ζύμωσης (στην περίπτωση που εξετάζεται τα ένζυμα) προκύπτει πυκνό και χωρίς ανάγκη ακριβού διαχωρισμού στον οποίο θα απομακρυνθεί το νερό, μειώνοντας σημαντικά το κόστος. Επιπλέον, εφόσον δεν απομακρύνεται νερό, δεν υπάρχουν υγρά απόβλητα τα οποία απαιτούν διαχείριση [cite:@aroraBioreactorsSolidState2018; @dossantosferreiraEnzymaticPretreatmentAnaerobic2020] . Όμως, είναι μία σχετικά καινούργια τεχνολογία, η οποία δεν έχει τόσο υψηλό \acrshort{trl} και δεν έχει αξιοποιηθεί εμπορικά σε μεγάλο βαθμό. Παρόλα αυτά, θεωρείται πως έχει πολύ μεγάλο περιθώριο εφαρμογής για διεργασίες που θέλουν ενζυμική υδρόλυση, αλλά το κόστος της την κάνει ανεπιθύμητη [cite:@aroraBioreactorsSolidState2018] . 

  Για την διεργασία αυτή, ένα από τα πιο βασικά γένη είναι τα Aspergillus, με τα A. awamori, A. oryzae, A. terreus και A. niger να είναι τα βασικότερα στελέχη που έχουν εφαρμοστεί στην διεργασία. Έχει βρεθεί πως ο A. awamori είναι ένας από τους αποτελεσματικούς μύκητες για την παραγωγή υδατανθρακασών, ο A. oryzae είναι ένας από τους πιο αποτελεσματικούς για πρωτεάσες ενώ ο Α. terreus είναι ένας από τους πιο αποτελεσματικούς για λιπάσες [cite:@soaresReductionScumAccumulation2019; @zouValorizationFoodWaste2020]. Ο λόγος που χρησιμοποιούνται μικροοργανισμοί του γένους αυτού είναι επειδή μπορούν να προσαρμωστούν εύκολα σε διάφορες περιβαλλοντικές συνθήκες και έχουν μεγάλο εύρος θερμοκρασιών και pH στα οποία μπορούν να αναπτυχθούν (από ψυχρόφιλους μέχρι 10 \( ^oC \) μέχρι θερμόφιλους στους 50 \( ^oC \) και από οξεόφιλους σε pH εώς και 2 μέχρι αλκαλόφιλους σε pH 11). Επίσης, μπορούν να λειτουργήσουν αποτελεσματικά ακόμη και σε συνθήκες ολιγοτροφισμού. Όλα αυτά, τους κάνουν πολύ ικανούς για την διεργασία αυτή, η οποία έχει πολύ μεγάλη σημασία στα πλαίσια της προεπεξεργασίας αποβλήτων, καθώς η ενζυμική υδρόλυση είναι η πιο αποτελεσματική τεχνολογία προεπεξεργασίας, αλλά η τιμή της είναι απαγορευτική [cite:@aroraBioreactorsSolidState2018; @soaresReductionScumAccumulation2019] .

** Παραγωγή Υδρολυτικών Ενζύμων από Βακτήρια
Βέβαια, εκτός από \acrshort{ssf} με χρήση μηκύτων, υδρολυτικά ένζυμα μπορούν να παραχθούν και από βακτήρια. Από το \figurename [[fig:anaerobic_digestion_steps]] φαίνεται πως κατά την αναερόβια χώνευση, μπορεί να γίνει υδρόλυση από τα υδρολυτικά βακτήρια, τα οποία εκκρίνουν ένζυμα με αυτήν την δράση [cite:@grippiChemicalBioenergeticCharacterization2020]. Όπως προαναφέρθηκε, οι συνθήκες της χώνευσης δεν είναι σύμφωνες με τις ιδανικές για τους μικροοργανισμούς αυτούς, οπότε η χώνευση, διεξάγεται πολύ αργά, στην περίπτωση αυτή. Όμως, ως ένα χωριστό στάδιο υδρόλυσης, οι συνθήκες αυτές μπορούν να ρυθμιστούν καλύτερα [cite:@zhangThreestageAnaerobicCodigestion2019; @zhangThreestageAnaerobicDigester2017] . Η υδρόλυση λείτουργεί βέλτιστα σε όξινα pH (πχ 4.5-5.0) και πολλά από τα υδρολυτικά βακτήρια είναι θερμόφιλα, οπότε οι υψηλές θερμοκρασίες (πχ 45-55 \( ^oC \)) μπορεί να συνεισφέρουν στην πιο αποτελεσματική υδρόλυση [cite:@xiaoTemperaturephasedAnaerobicDigestion2018; @zhangThreestageAnaerobicDigester2017; @tangEffectsMicroaerationPhylogenetic2004]. Οπότε, μπορεί η ίδια λάσπη που θα χρησιμοποιηθεί στην αναερόβια χώνευση να χρησιμοποιηθεί και ως εμβόλιο για το στάδιο της υδρόλυσης, μόνο που οι συνθήκες θα είναι ρυθμισμένες έτσι ώστε να είναι βέλτιστη η υδρόλυση.

Αυτή είναι και η αρχή λειτουργίας της αναερόβιας χώνευσης σε 2 φάσεις. Στις συνθήκες αυτές, εκτός από υδρόλυση θα διεξαχθεί και οξεογένεση (οι οξεογόνοι μικροοργανισμοί μπορούν να δράσουν στις συνθήκες αυτές) [cite:@wuPotentialityRecoveringBioresource2022; @pohlandDevelopmentsAnaerobicStabilization1971; @azbarEffectProcessConfiguration2001] . Συχνά, σε ένα τέτοιο σύστημα οι συνθήκες ρυθμίζονται για την βελτιστοποίηση της οξεογένεσης, αλλά μπορούν να επιλεχθούν και συνθήκες με βάση την βελτιστοποίηση της υδρόλυσης.

Άλλη μία αλλαγή που μπορεί να βοηθήσει την υδρόλυση είναι ο αερισμός. Τα βακτήρια που συμμετέχουν στα στάδια της υδρόλυσης και οξεογένεσης είναι προαιρετικά αναερόβια και μάλιστα λειτουργούν πιο αποτελεσματικά σε αερόβιες συνθήκες. Ακόμη, στις συνθήκες αυτές γίνεται πιο πλούσια η μικροβιακή ποικιλότητα στον αντιδραστήρα [cite:@ramosMicroaerobicDigestionSewage2014; @tangEffectsMicroaerationPhylogenetic2004]. Οπότε, αν ο αντιδραστήρας αυτός αερίζεται, μπορεί να βελτιωθεί η απόδοση της υδρόλυσης αλλά και της οξεογένεσης. Μία από τις πρώτες μελέτες που διαπίστωσε αυτό το συμπέρασμα το διαπίστωσε μετά από μικροβιακή ανάλυση, στην οποία υπήρχαν υποχρεωτικά αερόβια βακτήρια σε έναν χωνευτήρα σε δύο φάσεις [cite:@limStudyMicrobialCommunity2013] . Μετά από μελέτη του συστήματος αυτού, διαπιστώθηκε πως πράγματι η προσθήκη οξυγόνου βοηθάει το σύστημα, αρκεί να μην είναι πάρα πολύ μεγάλη ποσότητα, στην οποία περίπτωση αρχίζει να δημιουργεί προβλήματα στα επόμενα στάδια, τα οποία είναι υποχρεωτικά αναερόβια [cite:@xuOptimizationMicroaerationIntensity2014; @nguyenLittleBreathFresh2018; @chenReviewMicroaerationbasedAnaerobic2020] . Έτσι, η τεχνολογία του μικροαερισμού στην αναερόβια χώνευση έχει διερευνηθεί από πολλές ερευνητικές ομάδες [cite:@nguyenLittleBreathFresh2018; @chenReviewMicroaerationbasedAnaerobic2020; @canulbacabTwoPhaseAnaerobic2020; @limEnhancedHydrolysisMethane2013; @limMicrobialCommunityStructure2014] .

Εκτός από την υδρόλυση, ο αερισμός βοηθάει και στην απομάκρυνση του υδρόθειου που μπορεί να δημιουργηθεί σε έναν χωνευτήρα και αποτελεί πρόβλημα [cite:@chenReviewMicroaerationbasedAnaerobic2020; @ramosMicroaerobicDigestionSewage2014] . Αυτό δεν είναι πρόβλημα στην περίπτωση των \acrshort{fw} βέβαια.

Πέρα από τις τεχνικές αυτές για την έκκριση ενζύμων από βακτήρια τα οποία υπάρχουν στην αναερόβια λάσπη, υπάρχουν και εμπορικά σκευάσματα με αντίστοιχους μικροοργανισμούς τα οποία έχουν υψηλή ενεργότητα σε υδρολυτικά ένζυμα χωρίς να χρειάζεται να παραχθούν με βάση αυτές τις τεχνολογίες. Η χρήση των συνθηκών αυτών είναι και πάλι επιθυμητή για την βέλτιστη λειτουργία, αλλά η χρήση ενός τέτοιου σκευάσματος επιτρέπει μία πολύ εύκολη, αλλά αποτελεσματική ενζυμική υδρόλυση σε χαμηλό κόστος. Λόγω της απλότητας της διεργασίας με την χρήση ενός τέτοιου εμπορικού σκευάσματος σε σχέση με τις προηγούμενες τεχνολογίες, θεωρείται η ιδανική διεργασία υδρόλυσης/βιοαποδόμησης για μεγάλη κλίμακα.
