#+TITLE: Συζήτηση Αποτελεσμάτων Διπλωματικής

* Συζήτηση Αποτελεσμάτων
\label{sec:result_discussion}

Στο κεφάλαιο αυτό θα γίνει η συζήτηση των σημαντικότερων από τα πειραματικά αποτελέσματα καθώς και η παράθεση κάποιων συγκριτικών αποτελεσμάτων, με σκοπό να προκύψουν και τα βασικότερα συμπεράσματα της μελέτης αυτής.

** Μεταβολικά Μονοπάτια Οξεογένεσης
Ένα από τα πιο ενδιαφέροντα συμπεράσματα της μελέτης είναι η διαπίστωση του μεταβολικού μονοπατιού που ακολουθείται στην διεργασία. Η γνώση αυτού μπορεί να βοηθήσει και στην βελτιστοποίηση της διεργασίας.

Η αποδόμηση των διαλυτών σακχάρων έγινε αποτελεσματικά σε κάθε πείραμα. Η σακχαρόζη και η γλυκόζη καταναλώθηκαν σε κάθε περίπτωση μέσα στην πρώτη μέρα με το πείραμα στους 40 \( ^oC \) να έχει τον γρηγορότερο ρυθμό αποικοδόμησης. Για την φρουκτόζη, το δοκιμαστικό πείραμα το οποίο έγινε στους 45 \( ^oC \) είχε συσσώρευση φρουκτόζης ακόμη και μετά από 1 εβδομάδα πειράματος, σημαίνοντας μία δυσκολία στον μεταβολισμό της. Παρότι και στις άλλες θερμοκρασίες ο μεταβολισμός της είναι αργός, εκεί μεταβολίζεται πλήρως. Ως προς την παραγωγή τους, από το κινητικό πείραμα διαπιστώθηκε πως την πρώτη μέρα υπάρχει αύξηση σακχάρων, το οποίο επιβεβαιώνει ότι συμβαίνει μία υδρόλυση κατά την διάρκεια της διεργασίας αυτής.

Τα μεταβολικά προϊόντα που παρατηρούνται είναι το γαλακτικό οξύ, το οξικό οξύ, το προπιονικό οξύ και η αιθανόλη. Τα προϊόντα αυτά είναι σύνηθη προϊόντα της οξεογένεσης (\autoref{sec:acidogenesis}). Συγκεκριμένα, το γαλακτικό οξύ έχει παρατηρηθεί να παράγεται σε μεγάλες ποσότητες σε όξινα περιβάλλοντα και ιδιαίτερα με υπόστρωμα \acrshort{fw}, στα οποία έχει παρατηρηθεί συχνά η ύπαρξη ενδογενών μικροοργανισμών του γένους Lactobacillus [cite:@wuLacticAcidProduction2015]. Αυτό παράγεται είτε από ομογαλακτική ή ετερογαλακτική ζύμωση. Είναι πιθανό πως στο σύστημα που εξετάζεται υπάρχουν και τα δύο, καθώς η παραγωγή μεγάλης ποσότητας αιθανόλης μπορεί να σημαίνει ότι παράχθηκε μαζί με το γαλακτικό οξύ κατά την ετερογαλακτική ζύμωση και το προπιονικό οξύ παράγεται από την περαιτέρω αναγωγή του γαλακτικού οξέος κατά την ομογαλακτική ζύμωση. Το οξικό οξύ είναι επίσης λογικό να παραχθεί καθώς παράγεται σχεδόν σε κάθε οξεογένεση και ειδικά στην περίπτωση που τα υπόλοιπα προϊόντα είναι αναγωγικά, είναι ένα απαραίτητο προϊόν για να ρυθμίσει το \acrfull{redox} της αντίδρασης. Τέλος, εφόσον παράγεται το Acetyl-CoA για τον σκοπό αυτόν, είναι πιθανό πως αιθανόλη παράγεται και από το αναγωγικό μονοπάτι από το οξικό οξύ.
  
Από τα αποτελέσματα του δοκιμαστικού πειράματος, παρατηρήθηκε πως η αιθανόλη και το γαλακτικό οξύ παράγονται σε μεγάλο βαθμό τις πρώτες μέρες, ενώ μετά τις 3 μέρες, αρχίζουν να συσσωρεύονται οξικό και προπιονικό οξύ. Στο δοκιμαστικό πείραμα παρατηρήθηκε κατανάλωση της αιθανόλης και του γαλακτικού οξύ. Η κατανάλωση της αιθανόλης σημαίνει λογικά πως έχει ενεργοποιηθεί η οξικογενετική αντίδραση της κατανάλωσης της αιθανόλης (\autoref{sec:methane-thermodynamics}) ενώ για το γαλακτικό οξύ, λογικά υπάρχει μία μικτή κατανάλωση προς οξικό και προπιονικό οξύ ανάλογα με το \acrshort{redox} (\autoref{sec:methane-thermodynamics}). Η μείωση της αιθανόλης υπήρχε σε κάθε πείραμα, κάτι λογικό καθώς είναι εύκολο να υπάρξουν οι συνθήκες για αυθόρμητη μετατροπή αιθανόλης σε οξικό, ενώ η μείωση του γαλακτικού δεν ξανά παρατηρήθηκε. Η αναγωγή του σε προπιονικό σίγουρα έγινε - καθώς παράχθηκε προπιονικό - ενώ η οξείδωση του σε οξικό δεν είναι σίγουρο αν έγινε καθώς υπάρχουν αρκετές άλλες αντιδράσεις από τις οποίες μπορεί να παράχθηκε το οξικό οξύ. Ακόμη και αν έγινε όμως, ο ρυθμός της ήταν χαμηλός καθώς ο συνολικός ρυθμός παραγωγής γαλακτικού οξέος ήταν μεγαλύτερος από τον ρυθμό κατανάλωσης του.

Το προπιονικό οξύ φαίνεται να παράγεται σε παρόμοια ποσότητα ανεξαρτήτως ποσότητας μιξ και θερμοκρασίας, ενώ η αιθανόλη φαίνεται να παράγεται σε πολύ περισσότερη ποσότητα στους 35 \( ^oC \) σε σχέση με τα άλλα πειράματα. Οπότε, είναι πιθανό πως οι μικροοργανισμοί που καταλύουν την αντίδραση παραγωγής αιθανόλης αναστέλλονται σε υψηλότερη θερμοκρασία. Επίσης, έγινε και ένα διάγραμμα των προϊόντων που παράγονται σε κάθε συνθήκη (Σχήμα [[fig:comp-prod]]), από το οποίο είναι πιο εύκολο να φανούν τα συγκριτικά συμπεράσματα σε σχέση με τα προηγούμενα.

#+CAPTION: Προϊόντα της οξεογενούς ζύμωσης
#+NAME: fig:comp-prod
[[../plots/35_40_comp/final_products.svg]]

** Βαθμός Οξίνισης
Ένα ακόμη χρήσιμο συγκεντρωτικό κριτήριο που μπορεί να συμπεριληφθεί 

** Ανάλυση Ευαισθησίας
Από το Σχήμα [[fig:global-tornado]], υπάρχει η ένδειξη πως η θερμοκρασία παίζει ένα πάρα πολύ σημαντικό ρόλο στη ζύμωση καθώς από τις 8 επιδράσεις, στις 4 πρώτες, οι 3 είναι θερμοκρασιακές, με την επίδραση της αιθανόλης να είναι η σημαντικότερη. Εκτός όμως από την αρνητική αυτή επίδραση, τα άλλα 3 μεταβολικά προϊόντα επηρεάζονται θετικά από την θερμοκρασία. Από την άποψη της ποσότητας μιξ, φαίνεται πως το γαλακτικό έχει μία πολύ μεγάλη θετική επίδραση, το οξικό μία αρνητική επίδραση ενώ τα άλλα 2 δείχνουν να επηρεάζονται αμελητέα από την ποσότητα του μιξ.

Όπως διαπιστώθηκε από το Σχήμα [[fig:temperature-tornado]] η αρνητική επίδραση του οξικού από την ποσότητα μιξ οφείλεται μόνο στην χαμηλή θερμοκρασία. Οπότε, η λειτουργία στους 40 \( ^oC \) θεωρείται πιο επιθυμητή στην περίπτωση που η διεργασία αυτή είναι προεπεξεργασία για αναερόβια χώνευση, επειδή η αύξηση της συγκέντρωσης του οξικού οξέος είναι επιθυμητή. (Σίγουρα θέλω και κάποια σχόλια για το γιατί δεν κάναμε άλλο πείραμα στους 45 \( ^oC \), αλλά δεν έχω τα κατάλληλα αποτελέσματα ήδη γραμμένα νμζ).

Για την ποσότητα του μιξ θεωρήθηκε πως η βέλτιστη ποσότητα είναι 2 mL μιξ καθώς σε παραπάνω ποσότητες η βελτίωση είναι αρκετά μικρή. Αυτό φαίνεται ιδιαίτερα ξεκάθαρα στο Σχήμα [[fig:high-tornado]] όπου καμία ένωση δεν έχει θετική ευαισθησία στο εξεταζόμενο εύρος. Όμως, η διαφορά από το 1 mL στα 2 mL είναι στα περισσότερα πειράματα σημαντική.

** Υδρόλυση σε Πιλοτική Κλίμακα
Τα αποτελέσματα των πειραμάτων της πιλοτικής κλίμακας αναλύθηκαν κυρίως ως προς την απόδοση της υδρόλυσης, η οποία μετριέται από τον λόγο διαλυτού με ολικό \acrshort{cod}. Για τον πρώτο πειραματικό κύκλο, ο λόγος αυτός ήταν \( 46.1 \pm 12.2 \% \).

Έπειτα, εξετάστηκε η μεταβολή της ποσότητας νερού που προστίθεται στον αντιδραστήρα. Ο λόγος sCOD/tCOD στην περίπτωση αυτή ήταν \( 39.2 \pm 10.4 \% \) το οποίο φαινομενικά φαίνεται χειρότερο από το προηγούμενο, αλλά συγκρίνοντας τα με ένα t-test, φαίνεται πως δεν μπορεί να προκύψει ασφαλές συμπέρασμα για την επίδραση της αραίωσης στην υδρόλυση/βιοαποδόμηση (p-Value = 0.86). 

Τέλος, στο τρίτο πείραμα διπλασιάστηκε η ποσότητα του \acrshort{mix} που προστίθεται και βρέθηκε πως ο λόγος sCOD/tCOD ήταν \( 32.7 \pm 10.3 \% \), μείωση η οποία είναι στατιστικά σημαντική σε σχέση με τις προηγούμενες τιμές (p-Value = 0.0002 και 0.0011 σε t-test με το 1ο και 2ο πείραμα αντίστοιχα). Οπότε, είναι ασφαλές να προκύψει το συμπέρασμα ότι η προσθήκη παραπάνω από 5 mL \acrshort{mix}/kg \acrshort{fw} δεν βοηθάει την υδρόλυση.

Ένα πιθανό αίτιο για αυτό είναι πως προστίθενται περισσότεροι μικροοργανισμοί, οι οποίοι καταναλώνουν διαλυτό \acrshort{cod} για να τραφούν. Ένα μεγάλο ποσοστό της τροφής αυτής μετατρέπεται στα οξεογενή προϊόντα, αλλά αν οι μικροοργανισμοί αυξηθούν πολύ, αρχίζει να παρατηρείται και η μείωση στο \acrshort{cod}. Αντίθετα, η υδρόλυση μπορεί να γίνεται κορεσμένη σε ένζυμα (δηλαδή να μην περιορίζεται πλέον από την ποσότητα αυτών) σε ποσότητα κοντά στα 5 mL \acrshort{mix}/kg \acrshort{fw}. Αυτό δείχνει μία ένδειξη πως παρότι στα εργαστηριακά πειράματα φάνηκε πιο αποτελεσματική η ποσότητα 10 mL \acrshort{mix}/kg \acrshort{fw} λόγω της βέλτιστης οξεογένεσης, αυτό μπορεί να μην συνάδει με το βέλτιστο της υδρόλυσης. Οπότε, έχει αρκετό ενδιαφέρον να βρεθεί τι από τα δύο είναι πιο σημαντικό για την \acrshort{ad}.

Βέβαια, υπάρχει και πιθανότητα αυτό να είναι μία διαφορά μεταξύ της εργαστηριακής και της πιλοτικής κλίμακας και στην κλίμακα αυτή, η ποσότητα 5 mL \acrshort{mix}/kg \acrshort{fw} να έχει και καλύτερη οξεογένεση. Για τον σκοπό αυτόν, τα 2 αυτά δείγματα αναλύθηκαν με \acrshort{hplc} για να διαλευκανθεί αυτό το θέμα.

** Αναερόβια Χώνευση
