#+TITLE: Συζήτηση Αποτελεσμάτων Διπλωματικής

* Συζήτηση Αποτελεσμάτων
Στο κεφάλαιο αυτό θα γίνει η συζήτηση των σημαντικότερων από τα πειραματικά αποτελέσματα καθώς και η παράθεση κάποιων συγκριτικών αποτελεσμάτων, με σκοπό να προκύψουν και τα βασικότερα συμπεράσματα της μελέτης αυτής.

** Μεταβολικά Μονοπάτια Οξεογένεσης
Για την υδρόλυση σε εργαστηριακή κλίμακα, αξίζει να συζητηθεί το μεταβολικό μονοπάτι το οποίο ακολουθήθηκε σε κάθε περίπτωση.

Η αποδόμηση των διαλυτών σακχάρων έγινε αποτελεσματικά σε κάθε πείραμα. Η σακχαρόζη και η γλυκόζη καταναλώθηκαν σε κάθε περίπτωση μέσα στην πρώτη μέρα με το πείραμα στους 40 \( ^oC \) να έχει τον γρηγορότερο ρυθμό αποικοδόμησης. Για την φρουκτόζη, το δοκιμαστικό πείραμα το οποίο έγινε στους 45 \( ^oC \) είχε συσσώρευση φρουκτόζης ακόμη και μετά από 1 εβδομάδα πειράματος, σημαίνοντας μία δυσκολία στον μεταβολισμό της. Παρότι και στις άλλες θερμοκρασίες ο μεταβολισμός της είναι αργός, εκεί μεταβολίζεται πλήρως. Ως προς την παραγωγή τους, από το κινητικό πείραμα διαπιστώθηκε πως την πρώτη μέρα υπάρχει αύξηση σακχάρων, το οποίο επιβεβαιώνει ότι συμβαίνει μία υδρόλυση κατά την διάρκεια της διεργασίας αυτής.

Τα μεταβολικά προϊόντα που παρατηρούνται είναι το γαλακτικό οξύ, το οξικό οξύ, το προπιονικό οξύ και η αιθανόλη. Τα προϊόντα αυτά είναι σύνηθη προϊόντα της οξεογένεσης (\autoref{sec:acidogenesis}). Συγκεκριμένα, το γαλακτικό οξύ έχει παρατηρηθεί να παράγεται σε μεγάλες ποσότητες σε όξινα περιβάλλοντα και ιδιαίτερα σε \acrshort{fw}, στα οποία έχει παρατηρηθεί συχνά η ύπαρξη ενδογενών μικροοργανισμών του γένους Lactobacillus (λογικά citation εδώ). Αυτό παράγεται είτε από ομογαλακτική ή ετερογαλακτική ζύμωση. Είναι πιθανό πως στο σύστημα που εξετάζεται υπάρχουν και τα δύο, καθώς η παραγωγή μεγάλης ποσότητας αιθανόλης μπορεί να σημαίνει ότι παράχθηκε μαζί με το γαλακτικό οξύ κατά την ετερογαλακτική ζύμωση και το προπιονικό οξύ παράγεται από την περαιτέρω αναγωγή του γαλακτικού οξέος κατά την ομογαλακτική ζύμωση. Το οξικό οξύ είναι επίσης λογικό να παραχθεί καθώς παράγεται σχεδόν σε κάθε οξεογένεση και ειδικά στην περίπτωση που τα υπόλοιπα προϊόντα είναι αναγωγικά, είναι ένα απαραίτητο προϊόν για να ρυθμίσει το \acrfull{redox} της αντίδρασης. Τέλος, εφόσον παράγεται το Acetyl-CoA για τον σκοπό αυτόν, είναι πιθανό πως αιθανόλη παράγεται και από το αναγωγικό μονοπάτι από το οξικό οξύ.
  
Από τα αποτελέσματα του δοκιμαστικού πειράματος, παρατηρήθηκε πως η αιθανόλη και το γαλακτικό οξύ παράγονται σε μεγάλο βαθμό τις πρώτες μέρες, ενώ μετά τις 3 μέρες, αρχίζουν να συσσωρεύονται οξικό και προπιονικό οξύ. Η κατανάλωση της αιθανόλης σημαίνει λογικά πως έχει ενεργοποιηθεί η οξικογενετική αντίδραση της κατανάλωσης της (\autoref{sec:eth-aceto}) ενώ για το γαλακτικό οξύ, λογικά υπάρχει μία μικτή κατανάλωση προς οξικό και προπιονικό οξύ ανάλογα με το \acrshort{redox} (\autoref{sec:lact-aceto}).

Η μείωση της αιθανόλης παρατηρήθηκε σε κάθε πείραμα, ενώ η μείωση του γαλακτικού δεν επαναλήφθηκε σε κάποιο πείραμα. Αυτό σημαίνει πως η οξικογένεση της αιθανόλης είναι μία αντίδραση η οποία είναι ενεργοποιημένη σε όλο το εξεταζόμενο εύρος συνθηκών. Για το γαλακτικό οξύ, αυτό μπορεί είτε να σημαίνει ότι ο ρυθμός παραγωγής του είναι πολύ γρήγορος στις 2 αυτές θερμοκρασίες και δεν μπορεί να παρατηρηθεί μείωση ή ότι η οξικογενετική αντίδραση του, στις συνθήκες που εξετάζονται δεν είναι θερμοδυναμικά εφικτή.

Το προπιονικό οξύ φαίνεται να παράγεται σε παρόμοια ποσότητα ανεξαρτήτως ποσότητας μιξ και θερμοκρασίας, ενώ η αιθανόλη φαίνεται να παράγεται σε πολύ περισσότερη ποσότητα στους 35 \( ^oC \) σε σχέση με τα άλλα πειράματα. Οπότε, είναι πιθανό πως οι μικροοργανισμοί που καταλύουν την αντίδραση παραγωγής αιθανόλης αναστέλλονται σε υψηλότερη θερμοκρασία. Επίσης, έγινε και ένα διάγραμμα των προϊόντων που παράγονται σε κάθε συνθήκη (Σχήμα [[fig:comp-prod]]), από το οποίο είναι πιο εύκολο να φανούν τα συγκριτικά συμπεράσματα σε σχέση με τα προηγούμενα.

#+CAPTION: Προϊόντα της οξεογενούς ζύμωσης
#+NAME: fig:comp-prod
[[../plots/35_40_comp/final_products.svg]]

** Βαθμός Οξίνισης
Ένα ακόμη χρήσιμο συγκεντρωτικό κριτήριο που μπορεί να συμπεριληφθεί 

** Ανάλυση Ευαισθησίας
Με βάση την ανάλυση ευαισθησίας, διαπιστώθηκε πως η θερμοκρασία είναι ο σημαντικότερος παράγοντας που επιδρά στην διεργασία και πως η λειτουργία στους 40 \( ^oC \) είναι ευνοϊκή σε σχέση με τους 35 \( ^oC \) ή ακόμη και τους 45 \( ^oC \) (θέλει λίγο σχολιασμό το 45 \( ^oC \) αλλά με βάση όσα έχω δεί ισχύει). Η χαμηλότερη θερμοκρασία μπορεί να είναι επιθυμητή για άλλες εφαρμογές όπου είναι σημαντικότερη η παραγωγή αιθανόλης παρά οξικού οξέος.

Για την ποσότητα του μιξ θεωρήθηκε πως η βέλτιστη ποσότητα είναι 2 mL μιξ καθώς σε παραπάνω η βελτίωση είναι αρκετά μικρή. Αυτό φαίνεται ιδιαίτερα ξεκάθαρα στο Σχήμα [[fig:high-tornado]] όπου καμία ένωση δεν έχει θετική ευαισθησία στο εξεταζόμενο εύρος. Όμως, η διαφορά από το 1 mL στα 2 mL είναι στα περισσότερα πειράματα σημαντική.

** Υδρόλυση σε Πιλοτική Κλίμακα
Τα αποτελέσματα των πειραμάτων της πιλοτικής κλίμακας αναλύθηκαν κυρίως ως προς την απόδοση της υδρόλυσης, η οποία μετριέται από τον λόγο διαλυτού με ολικό \acrshort{cod}. Για τον πρώτο πειραματικό κύκλο, ο λόγος αυτός ήταν \( 46.1 \pm 12.2 \% \).

Έπειτα, εξετάστηκε η μεταβολή της ποσότητας νερού που προστίθεται στον αντιδραστήρα. Ο λόγος sCOD/tCOD στην περίπτωση αυτή ήταν \( 39.2 \pm 10.4 \% \) το οποίο φαινομενικά φαίνεται χειρότερο από το προηγούμενο, αλλά συγκρίνοντας τα με ένα t-test, φαίνεται πως δεν μπορεί να προκύψει ασφαλές συμπέρασμα για την επίδραση της αραίωσης στην υδρόλυση/βιοαποδόμηση (p-Value = 0.86). 

Τέλος, στο τρίτο πείραμα διπλασιάστηκε η ποσότητα του μιξ που προστίθεται και βρέθηκε πως ο λόγος sCOD/tCOD ήταν \( 32.7 \pm 10.3 \% \), μείωση η οποία είναι στατιστικά σημαντική σε σχέση με τις προηγούμενες τιμές (p-Value = 0.0002 και 0.0011 σε t-test με το 1ο και 2ο πείραμα αντίστοιχα). Οπότε, είναι ασφαλές να προκύψει το συμπέρασμα ότι η προσθήκη παραπάνω από 5 mL mix/kg FW δεν βοηθάει την υδρόλυση.

Ένα πιθανό αίτιο για αυτό είναι πως προστίθενται περισσότεροι μικροοργανισμοί, οι οποίοι καταναλώνουν διαλυτό \acrshort{cod} για να τραφούν. Ένα μεγάλο ποσοστό της τροφής αυτής μετατρέπεται στα οξεογενή προϊόντα, αλλά αν οι μικροοργανισμοί αυξηθούν πολύ, αρχίζει να παρατηρείται και η μείωση στο \acrshort{cod}. Αντίθετα, η υδρόλυση μπορεί να γίνεται κορεσμένη σε ένζυμα (δηλαδή να μην περιορίζεται πλέον από την ποσότητα αυτών) σε ποσότητα κοντά στα 5 mL mix/kg FW. Αυτό δείχνει μία ένδειξη πως παρότι στα εργαστηριακά πειράματα φάνηκε πιο αποτελεσματική η ποσότητα 10 mL mix/kg FW λόγω της βέλτιστης οξεογένεσης, αυτό μπορεί να μην συνάδει με το βέλτιστο της υδρόλυσης. Οπότε, έχει αρκετό ενδιαφέρον να βρεθεί τι από τα δύο είναι πιο σημαντικό για την \acrshort{ad}.

Βέβαια, υπάρχει και πιθανότητα αυτό να είναι μία διαφορά μεταξύ της εργαστηριακής και της πιλοτικής κλίμακας και στην κλίμακα αυτή, η ποσότητα 5 mL mix/kg FW να έχει και καλύτερη οξεογένεση. Για τον σκοπό αυτόν, τα 2 αυτά δείγματα αναλύθηκαν με \acrshort{hplc} για να διαλευκανθεί αυτό το θέμα.

** Αναερόβια Χώνευση
