#+TITLE: Ανάλυση στατιστικών δεδομένων από το Statista

* COMMENT Description
Αυτό το αρχείο έχει σκοπό να αναλύσει τα στατιστικά δεδομένα που έγιναν extracted από το Statista. Σε πολλά σημεία μπορεί απλώς να βάλω το διάγραμμα, αλλά επειδή έχω πολλά, κάποια θα είναι σε κείμενο. Σε πολλά σημεία, αυτό θα γίνει weaved στο αρχικό κείμενο που έχω της εισαγωγής.

* Υπολείμματα τροφών
Τα υπολείμματα τροφών αποτελούν μία από τις σημαντικότερες κατηγορίες οργανικών αποβλήτων. Ο οργανισμός τροφίμων και αγρονομίας των ηνωμένων πολιτείων (FAO) υπολογίζει πως περίπου το 1/3 της παγκόσμιας παραγωγής τροφών (περίπου 1.3 δις τόνοι ετησίως) χάνεται κατά την παραγωγική διαδικασία ή απορρίπτεται. Κάποιες από αυτές τις απώλειες είναι αναπόφευχτες, αλλά πολλές θα μπορούσαν να αποφευχθούν ή τα υπολείμματα να συλλεχθούν για μία καλύτερη αξιοποίηση, καθώς οι κλασσικές τεχνικές, όπως η υγειονομική ταφή ή η αποτέφρωση, δημιουργούν προβλήματα όπως οι ανεξέλεγκτες εκπομπές μεγάλων ποσοτήτων αερίων του θερμοκηπίου [cite:@wuPotentialityRecoveringBioresource2022; @zhangValorizationFoodWaste2020; @ishangulyyevUnderstandingFoodLoss2019].

Συγκεκριμένα, έχει προσδιοριστεί πως το ισοδύναμο διοξειδίου του άνθρακα που παράγεται λόγω της μη ορθής αυτής διαχείρισης των υπολείμματων ανέρχεται στους 3.3 δις τόνους [cite:@taheriEffectPretreatmentTechniques2021] . Ακόμη, έχει βρεθεί πως τα υπολείμματα τροφών που οφείλονται μόνο στην απόρριψη τροφών από καταναλωτές σε ανεπτυγμένες χώρες είναι σχεδόν όσα παράγουν οι υπό σακχάριες και αφρικανικές χώρες (περίπου 230 εκατομμύρια), όπου υπάρχουν σοβαρά προβλήματα υποσιτισμού. Αλλά ακόμη και αν κανείς αγνοήσει τις κοινωνικές και περιβαλλοντικές επιδράσεις που έχει αυτή η συμπεριφορά, το πρόβλημα μπορεί να αναχθεί και καθαρά στον οικονομικό τομέα. Η καθαρή αξία των τροφών που χάνονται ή απορρίπτονται σε κάποιο σημείο της εφοδιαστικής αλυσίδας είναι 936 δις δολλάρια ανά έτος [cite:@ishangulyyevUnderstandingFoodLoss2019] .

Μία από τις βασικότερες υποκατηγορίες υπολειμμάτων τροφών είναι τα οικιακά υπολείμματα τροφών. Μία πρόσφατη μελέτη έδειξε πως περίπου το \( 61 \% \) των υπολειμμάτων τροφών που παράγονται παγκοσμίως είναι από αυτόν τον τομέα. Η Ελλάδα είναι η χώρα με την δεύτερη μεγαλύτερη παραγωγή οικιακών υπολειμμάτων τροφών κατά κεφαλήν παγκοσμίως (142 κιλά/άτομο ετησίως). (cite statista)

Επομένως, είναι επιτακτική η ανάγκη εφαρμογής τεχνολογιών διαχείρισης ή/και αξιοποίησης των υπολειμμάτων αυτών, οι οποίες να είναι εύκολα εφαρμόσιμες σε μεγάλη κλίμακα. Η διαχείριση αποβλήτων έχει μία πολύ μεγάλη αγορά (1293 δις δολλάρια ετησίως το 2022), η οποία προβλέπεται να φτάσει τα 2000 δις δολλάρια μέχρι το 2030 (cite statista). Έτσι, η ανάπτυξη νέων τεχνολογιών διαχείρισης, οι οποίες να είναι αποτελεσματικές αλλά και οικονομικά εφικτές είναι ιδιαίτερα σημαντικό και αναμένεται να γίνει σε μεγάλο βαθμό τα επόμενα χρόνια.

Για τα υπολείμματα τροφών, οι βασικότερες τεχνολογίες βασίζονται στην βιολογική μετατροπή τους σε κάποιον ενεργειακό φορέα. Αυτές οι διεργασίες είναι αποτελεσματικές λόγω της πλούσιας περιεκτικότητας των υπολειμμάτων σε οργανικές ενώσεις αλλά και σε θρεπτικά, τα οποία τα καθιστούν πολύ καλά υποστρώματα για μικροβιακή ανάπτυξη. Εκτός όμως από το πλεονέκτημα της διαχείρισης των υπολειμμάτων, οι τεχνολογίες αυτές έχουν και ένα δεύτερο σημαντικό πλεονέκτημα, το οποίο είναι η παραγωγή βιοενέργειας.

Αυτή τη στιγμή, πάνω από το \( 80 \%\) της παγκόσμιας παραγωγής ενέργειας βασίζεται σε μη ανανεώσιμες πηγές όπως το πετρέλαιο και το φυσικό αέριο. Οι ενεργειακές απαιτήσεις συνεχώς αυξάνονται, ενώ οι πρώτες ύλες αυτές εξαλείφονται. Οπότε, τεχνολογίες παραγωγής ενέργειας από κάποια ανανεώσιμη πηγή είναι ιδιαίτερα επιθυμητή. Τα υπολείμματα τροφών είναι αρκετά άφθονα ώστε να καλύψουν ένα ικανό ποσοστό της ανάγκης αυτής. Αυτή τη στιγμή, μόνο ένα πολύ μικρό ποσοστό ενέργειας παράγεται από βιοδιεργασίες και το κύριο υπόστρωμα αυτών είναι στερεή βιομάζα.

Ως αποτέλεσμα, ένα από τα προβλήματα που μπορεί να παρουσιαστούν είναι η υψηλή περιεκτικότητα των υπολειμμάτων σε βιοπολυμερή (άμυλο, πρωτεΐνες, κυτταρίνη, ημικυτταρίνη) τα οποία δεν μπορούν να μεταβολιστούν. Για να γίνει επιτυχής βιοαποδόμηση των υπολειμμάτων αυτών και να χρησιμοποιηθούν στο έπακρο, απαιτείται ένα στάδιο υδρόλυσης.

